### ISSUE TITLE
Push notifications codelab missing content for subscribe step 7

### ISSUE THREAD

**Issue by samdutton** [googlecodelabs/feedback#1]
[Codelab step 7](https://www.code-labs.io/codelabs/push-notifications/#6) is missing all content from the [original doc](https://docs.google.com/document/d/1T2wnuojyxOL9bgWkFrtB8t9rWcTa2f0UckrCrnrqc08/edit#heading=h.slhob4o2unwd).

**Comment by x1ddos** [comment]
On it.

**Comment by samdutton** [comment]
In the original doc, I've now changed the style for the text after the intial callout section — preview looks OK

**Comment by x1ddos** [comment]
When did you change it, just now? What was it before that?

**Comment by x1ddos** [comment]
Ok, updated. It should be fine now.

I still don't understand how that happened. When did you notice it disappeared?

**Comment by x1ddos** [comment]
Looking at the content update logs, that section's always been like that since it got published the first time:

```
+      <google-codelab-step label="Subscribe to Push Notifications">
+
+          <p><strong>Duration: 3:30</strong></p>
+<aside class="special"><p>A completed version of this step is in the <a target="_blank" href="https://github.com/samdutton/push-notific
ations/tree/master/completed/step4">completed/step4</a><em></em>&#160;directory.</p></aside>
+
+
+      </google-codelab-step>
```

**Comment by x1ddos** [comment]
It must be a bug. Export tool didn't handle custom formatting properly. I'll keep it in mind.

**Comment by samdutton** [comment]
LGTM — thanks for quick fix!
