### ISSUE TITLE
Running the pod in the demo creates a deployment

### ISSUE THREAD

**Issue by garreeoke** [googlecodelabs/feedback#10]
Going through the steps of this tutorial work great until attempting to run the create/run the pod.  Instead of creating a replicationController it is creating a deployment.  Here is the command and message from the command line:

[root@docker1 hellonode]# kubectl run hello-node --image=gcr.io/aaron-projects-1259/hello-node:v1 --port=8080
deployment "hello-node" created

**Comment by hostirosti** [comment]
Thank you @aaronLariat for reporting this. I'll be looking into this and respond back here.

**Comment by garreeoke** [comment]
To make it work I just had to replace rc with deployment in the expose command.

-Aaron

On Mar 23, 2016, at 6:23 PM, Robert Kubis <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you @aaronLariathttps://github.com/aaronLariat for reporting this. I'll be looking into this and respond back here.

##

**Comment by erisod** [comment]
I ran into an issue in the tutorial related to this as well when running kubectl expose.

$ kubectl expose rc --type="LoadBalancer" hello-node
Error from server: replicationcontrollers "hello-node" not found

As garreeoke mentioned, the expose command works correctly replacing 'rc' with 'deployments':

$ kubectl expose deployments hello-node --type="LoadBalancer"
service "hello-node" exposed

**Comment by alexismp** [comment]
This was fixed a little while ago, sorry for not reporting earlier and thanks for the report.
See https://codelabs.developers.google.com/codelabs/cloud-hello-kubernetes/index.html?index=..%2F..%2Findex#6
