### ISSUE TITLE
[cloud-networking-101]: 16. Test Network Load Balancer 3/3 - there is no google-address-manager service

### ISSUE THREAD

**Issue by kluyg** [googlecodelabs/feedback#100]
1. Test Network Load Balancer 3/3

> You will see that you can reach the IP address in Asia via your web browser, but not the EU VM.

I can reach both

> To make the vm work, you could start the address manager by running the following command on eu-vm:
> `$ sudo service google-address-manager start`

There is no such service on any VM:
`Failed to start google-address-manager.service: Unit google-address-manager.service failed to load: No such file or directory.`

**Comment by thesmiler** [comment]
Thank you, this is since the google adress manager service has been renamed google-ip-forwarding. This broke the script stopping the service and the document. I have addressed both and this will be rolled out shortly with the next iteration.

**Comment by maksymov** [comment]
any news with this issue?
