### ISSUE TITLE
[cloud-vision-python]:

### ISSUE THREAD

**Issue by ghost** [googlecodelabs/feedback#1005]
The authentication with a saved key file makes no sense here and do not work: I created a key file and saved it to my local computer. But the lab's instructions are for the cloud console, which cannot access that local file.

**Comment by PicardParis** [comment]
You need to download the service account key to the Cloud Shell environment (using `gcloud`).
This should work:
```
export PROJECT_ID=$(gcloud config get-value core/project)

gcloud iam service-accounts create my-vision-sa \
  --display-name "my vision service account"

gcloud iam service-accounts keys create ~/key.json \
  --iam-account my-vision-sa@${PROJECT_ID}.iam.gserviceaccount.com

export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
```

**Comment by PicardParis** [comment]
I'm closing the issue. Feel free to reopen if needed.
