### ISSUE TITLE
[cloud-bq-campaign-finance]: Linking to Source Tables sed command fails

### ISSUE THREAD

**Issue by g-lok** [googlecodelabs/feedback#101]
"Linking to Source Tables"

sed -i 's/"fieldDelimiter": ","/"fieldDelimiter": "|"/g; s/"quote": "\""/"quote":""/g' indiv_def.json

sed: 1: "indiv_def.json": command i expects \ followed by text

Not knowing how to use sed, this seems like a confusing and error prone way to make "simple changes" the the json.  Why not just show the changes to the file directly?  The JSON doesn't look that complicated.

**Comment by alexismp** [comment]
Thanks. I'll add a note about what the file should contain in a version that will go out later this week.
FYI, this does command works with CloudShell. Sadly not all 'sed' were created equal - http://stackoverflow.com/questions/18527365/what-does-sed-i-option-do

**Comment by g-lok** [comment]
Thank you!
