### ISSUE TITLE
[cloud-video-intelligence-python3] The video is not accessible anymore

### ISSUE THREAD

**Issue by meteatamel** [googlecodelabs/feedback#1014]
The video in the codelab is not accessible anymore

**Comment by PicardParis** [comment]
Thanks Mete. The bucket has been made private. I'm looking for an alternative...

**Comment by meteatamel** [comment]
Cool. Let me know what you find out. We have the same problem for the C# codelab and some other Qwiklabs.

**Comment by PicardParis** [comment]
- This codelab was fixed & updated (#1020).
- 4 videos were restored so far: `gbikes_dinosaur.mp4`, `JaneGoodall.mp4`,  `animals.mp4`,  `visionapi.mp4`
  - Old path: `gs://cloudmleap/video/next/video.mp4`
  - New path: `gs://cloud-samples-data/video/video.mp4`
