### ISSUE TITLE
[cloud-text-speech-python3]:

### ISSUE THREAD

**Issue by Haagimus** [googlecodelabs/feedback#1018]
I keep getting an error in my ipython console that no matter what I do.

```
In [1]: import google.cloud.texttospeech as tts
   ...: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-c5cfe2983311> in <module>
----> 1 import google.cloud.texttospeech as tts

ModuleNotFoundError: No module named 'google.cloud.texttospeech'
```

I cannot be crazy, but I cannot find anything at all online about how to fix this problem. Everything close that I can find doesn't solve the issue. Any ideas?

**Comment by PicardParis** [comment]
Hi @Haagimus,
- I retried and it works as expected. Did you skip the installation of the client library (see [step 5](https://codelabs.developers.google.com/codelabs/cloud-text-speech-python3#4))?
- Before launching ipython, you can check that it's correctly installed with the following command:
  - `pip3 freeze | grep texttospeech`
- This should give the current version:
  - `google-cloud-texttospeech==2.5.3`
- I'm closing the issue. Feel free to reopen with more details if it doesn't work.

**Comment by Haagimus** [comment]
I figured it out about an hour after I posted this. Forgot to circle back and update. I did a step wrong with API keys. Once I fixed my JSON keys and pointed everything to the correct place it started working. Thank you for the help @PicardParis

**Comment by PicardParis** [comment]
👍
