### ISSUE TITLE
[cloud-windows-containers-computeengine]: specify more information on the tutorial

### ISSUE THREAD

**Issue by latra** [googlecodelabs/feedback#1022]
It's not exactly a mistake, but I think that will be better if you specify to the users that they have to open the port 80 from them VM Instance too, and not only from the GCP Firewall.

`netsh advfirewall firewall add rule name="TCP Port 80" dir=in action=allow protocol=TCP localport=80`
`netsh advfirewall firewall add rule name="TCP Port 80" dir=out action=allow protocol=TCP localport=80`

**Comment by meteatamel** [comment]
Thanks for reporting. I added a note before running the container to let users know.
