### ISSUE TITLE
Authentication popup blocked by AdBlock Chrome Extension

### ISSUE THREAD

**Issue by aperrad** [googlecodelabs/feedback#103]
Due to use of AdBlock, the sign-in popup is automatically close before login-in.

**Message in console :**  

> Uncaught Error: The popup has been closed by the user before finalizing the operation. firebase.js:79

[https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/index.html?index=..%2F..%2Findex#21](url)

**Comment by x1ddos** [comment]
@Pacman861 disable adblock for codelabs.developers.google.com.

**Comment by aperrad** [comment]
It could be mentioned to avoir unexpected behavior. Many people have adblock enabled
