### ISSUE TITLE
[cloud-vision-python]: Image= vision.Image(content=content)

### ISSUE THREAD

**Issue by theday-tech** [googlecodelabs/feedback#1030]
when I use this code 

from google.cloud.vision import ImageAnnotatorClient
client = ImageAnnotatorClient()

I got this error on Image= vision.Image(content=content), "vision" is not defined. 

Any help for fix this problem? THANK YOU

**Comment by PicardParis** [comment]
Hi,
- The following should work:
  ```
  from google.cloud import vision

  client = vision.ImageAnnotatorClient()
  image = vision.Image(content=content)
  ```
- Or maybe you prefer:
  ```
  from google.cloud.vision import Image, ImageAnnotatorClient

  client = ImageAnnotatorClient()
  image = Image(content=content)
  ```
- If your code sample comes from a public reference, can you provide a link?

**Comment by theday-tech** [comment]
Thank you for your help. I used the second choice but I got this error "ImportError: cannot import name 'Image' from 'google.cloud.vision". 

They are two links: 
https://towardsdatascience.com/implementing-optical-character-recognition-ocr-using-pytesseract-5f42cf62ddcc

https://codelabs.developers.google.com/codelabs/cloud-vision-api-python#7

**Comment by PicardParis** [comment]
Things to check...
- Do you have a recent version of the client library?
  -  `pip freeze` should return `google-cloud-vision==2.5.0`
  - To install/update it: `pip install --upgrade google-cloud-vision`
- Which version of Python are you using?

**Comment by theday-tech** [comment]
No I have a old version. I am using Python 3.8.3

**Comment by PicardParis** [comment]
- Per the [doc](https://googleapis.dev/python/vision/latest/index.html#supported-python-versions), it supports "3.6 <= Python", so 3.8 is perfect.
- I suggest you update the client library:
  `pip install --upgrade google-cloud-vision`

**Comment by theday-tech** [comment]
Yeah I updated client library and I got google-cloud-vision==2.5.0.

**Comment by PicardParis** [comment]
Cool, closing the issue (assuming it's fixed). Feel free to reopen it, with more details, if you still meet issues.

**Comment by theday-tech** [comment]
Hello PicardParis, 

I'm working now on Google Cloud Shell and I can't upgrade google-cloud-vision. When I run it: pip install --upgrade google-cloud-vision, I get this : Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python2.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.25.0->google-api-core[grpc]<2.0.0dev,>=1.14.0->google-cloud-vision) (0.4.8)

and pip freeze return : google-cloud-vision==1.0.0

I don't know what's wrong, any help?

**Comment by PicardParis** [comment]
- From the error message, it's because `pip` still points to the Python 2.7 version. If you use `pip3` instead, you should see that you already have the latest version. From Cloud Shell, I get:
  ```
  pip3 freeze | grep vision
  google-cloud-vision==2.5.0
  ```
- It's easy to be confused in mixed system environments. To avoid this, a best practice is to use `venv`.
  - See: https://cloud.google.com/python/docs/setup#installing_and_using_virtualenv

**Comment by theday-tech** [comment]
It's working. I got another error about cloud vision API: google.api_core.exceptions.InvalidArgument: 400 Request must specify image and features.

**Comment by PicardParis** [comment]
From the error message, the request seems to be empty. Without code sample, I cannot guess more...

**Comment by theday-tech** [comment]
Ho sorry, this is my code:

import os
from flask import Flask, render_template, request
#from ocr_core import ocr_core 
from google.cloud.vision import Image, ImageAnnotatorClient
import io

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = ' '

app = Flask(__name__)

ALLOWED_EXTENSIONS = ['png', 'jpg', 'jpeg']


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


path = os.getcwd()

UPLOAD_FOLDER = os.path.join(path, 'uploads\\')
if not os.path.isdir(UPLOAD_FOLDER):
    os.mkdir(UPLOAD_FOLDER)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

@app.route('/')
def index():
    return render_template('index.html')


@app.route('/', methods=['GET', 'POST'])
def detect_text():
    
    
#"""Detects text in the file."""
    
    client = ImageAnnotatorClient()
    
    
    #file_name = os.path.abspath(path)

    # [START vision_python_migration_text_detection]
    if request.method == 'POST':
        if 'file' not in request.files:
            return render_template('index.html', msg='No file selected')
        file = request.files['file']

    if file.filename == '':
        return render_template('index.html', msg='No file')


    if file and allowed_file(file.filename):
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], file.filename))
        content = file.read()
        

        image = Image(content=content)

        response = client.text_detection(image=image)

#print('Texts:')
        for text in response.text_annotations:
            print(text.description)
    
        return render_template('index.html',
                               msg='OCR completed',
                               #extracted=extracted,
                               img_src=UPLOAD_FOLDER + file.filename)
    else:
        return render_template('index.html')

    
if __name__ == "__main__":
    

    app.run("localhost", 5000, threaded=True, debug=True)
