### ISSUE TITLE
[cloud-run-hello-python3]: gcloud builds submit --tag $DOCKER_IMG

### ISSUE THREAD

**Issue by theday-tech** [googlecodelabs/feedback#1031]
When I run this code: gcloud builds submit --tag $DOCKER_IMG I get this error: 
ERROR: (gcloud.builds.submit) INVALID_ARGUMENT: invalid build: invalid image name "gcr.io/engineering-titan-palu-prod/home/armelyara/OCR": could not parse reference: gcr.io/engineering-titan-palu-prod/home/armelyara/OCR

Any help?

**Comment by PicardParis** [comment]
Hi @theday-tech,
- I made a full pass on the codelab and it is working as expected.
- The message is not clear, but the error comes from the upper case "OCR" part in your custom image name.
- Image names must be in lower case (the norm in the container world). The following will work:
  - Codelab instruction:
    `DOCKER_IMG="gcr.io/$PROJECT_ID/helloworld-python"`
  - Or, with your custom name:
    `DOCKER_IMG="gcr.io/$PROJECT_ID/home/armelyara/ocr"`
- Note: the image name is unrelated to the source path. The command `gcloud builds submit --tag $DOCKER_IMG` uses the current working directory but can also be launched with a source parameter (see `gcloud builds submit --help`).
- I've filed an internal issue to make the error message explicit in this case.
- Closing this issue. Feel free to reopen if anything is unclear.

**Comment by theday-tech** [comment]
Thank you.
