### ISSUE TITLE
[cloud-kubernetes-aspnetcore]: Deployment not created error

### ISSUE THREAD

**Issue by surinphaosen** [googlecodelabs/feedback#1044]
Hi, All
in the stpe 7:
I found the messsage from execute this command " kubectl get deployments"  and return message is "No resources found in default namespace."

and in the step 8 : 
I found the messsage from execute this command "kubectl expose deployment hello-dotnet --type="LoadBalancer" --port=8080"
is "Error from server (NotFound): deployments.apps "hello-dotnet" not found"

I think this document is not up to date for gcp,dotnet or kubernetes

Can you please help me for fix this. 

Best Regards,

**Comment by meteatamel** [comment]
Thanks for reporting it. In Kubernetes, "kubectl run" does not create a deployment anymore. I changed to manually create a deployment. Please try again.
