### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by hunszab** [googlecodelabs/feedback#1045]
Hi,

the following command produce an error: (the version is outdated/not supported)
curl https://start.spring.io/starter.tgz \
  -d bootVersion=2.1.8.RELEASE \
  -d dependencies=web \
  -d baseDir=gae-standard-example | tar -xzvf -
  
  Response:
  {"timestamp":"2021-11-23T13:55:10.384+00:00","status":400,"error":"Bad Request","message":"Invalid Spring Boot version '2.1.8.RELEASE', Spring Boot compatibility range is >=**2.3.0.RELEASE**","path":"/starter.tgz"}
  
  Changing the version to 2.3.0.RELEASE it works fine.
  
  regards

**Comment by meteatamel** [comment]
Fixing with cl/523700032

**Comment by meteatamel** [comment]
Fixed
