### ISSUE TITLE
[cloud-app-engine-springboot]: Image not present in the codelab training

### ISSUE THREAD

**Issue by vishal758** [googlecodelabs/feedback#1046]
In the codelab training: Deploy a Spring Boot app to App Engine standard environment
The images are not there.
<img width="788" alt="Screenshot 2021-11-26 at 9 57 10 PM" src="https://user-images.githubusercontent.com/31901198/143609540-fffc01d5-041c-41df-8f90-f885cf7be5ec.png">

**Comment by meteatamel** [comment]
The latest codelab has images: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot?hl=en#1
