### ISSUE TITLE
[cloud-spring-cloud-gcp-gcs]:

### ISSUE THREAD

**Issue by lxhiguera** [googlecodelabs/feedback#1050]
In the step 4 change this command:

`
$ curl https://start.spring.io/starter.tgz \
-d dependencies=web,cloud-gcp-storage -d baseDir=spring-gcs | tar -xzvf -
`

to:

`
$ curl https://start.spring.io/starter.tgz?bootVersion=2.5.8-SNAPSHOT  \
-d dependencies=web,cloud-gcp-storage  -d baseDir=spring-gcs | tar -xzvf -
`

The new springboot versions getting error for the cloud-gcp-storage dependency

**Comment by meteatamel** [comment]
Updated the codelab and tested that it works. Closing this issue.
