### ISSUE TITLE
[cloud-springboot-cloudshell]: Screenshots in cloud shell codelab for Spring Boot application doesn't load

### ISSUE THREAD

**Issue by prasannasv** [googlecodelabs/feedback#1052]
The screenshots in this codelab are broken:

https://developers.google.com/codelabs/cloud-springboot-cloudshell?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fspringboot-google-cloud%23codelab-https%3A%2F%2Fdevelopers.google.com%2Fcodelabs%2Fcloud-springboot-cloudshell#1

Screenshot:
<img width="1386" alt="Screen Shot 2021-12-12 at 12 43 49 PM" src="https://user-images.githubusercontent.com/305985/145728945-c0b63f37-9ad8-4172-a926-12717ebee0ab.png">

**Comment by meteatamel** [comment]
This is the old link. The new link works fine: https://codelabs.developers.google.com/codelabs/cloud-springboot-cloudshell
