### ISSUE TITLE
[cloud-spring-cloud-gcp-gcs]:

### ISSUE THREAD

**Issue by GThoonsen-U** [googlecodelabs/feedback#1059]
this tuto is obsolete

https://codelabs.developers.google.com/codelabs/spring-cloud-gcp-gcs/index.html#3
--> cloud-gcp-storage has been removed from the Spring Cloud release train

see https://spring.io/projects/spring-cloud-gcp

**Comment by meteatamel** [comment]
Updated the codelab and tested that it works. Closing this issue.
