### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by witmat** [googlecodelabs/feedback#1063]
There are no images in https://developers.google.com/codelabs/cloud-app-engine-springboot?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fspringboot-google-cloud%23codelab-https%3A%2F%2Fdevelopers.google.com%2Fcodelabs%2Fcloud-app-engine-springboot#1

**Comment by meteatamel** [comment]
The latest update of the codelab has images: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot?hl=en#1
