### ISSUE TITLE
[cloud-networking-102]:

### ISSUE THREAD

**Issue by marcoforese** [googlecodelabs/feedback#107]
The part:

"Note that you get the "Permission denied" error. We need to run an ssh agent.

<local>:~$ eval `ssh-agent`
<local>:~$ ssh-add ~/.ssh/google_compute_engine"

on page "7. Set up NAT"

can be done only if you are in Gcloud via shell of web console, not if via local machine Gcloud (I'm doin' it on a normal Windows7 Pc, not tried it via a Linux machine).

**Comment by thesmiler** [comment]
Hi,
good point - this only works on Linux or on Cloud Shell... In the new version we recommend Cloud Shell!
