### ISSUE TITLE
[cloud-run-django]: Unable to set secrets

### ISSUE THREAD

**Issue by verecahill** [googlecodelabs/feedback#1074]
[8. Deploy to Cloud Run](https://codelabs.developers.google.com/codelabs/cloud-run-django#7)

below command is not working

```
gcloud run deploy django-cloudrun \
  --platform managed \
  --region $REGION \
  --image gcr.io/${PROJECT_ID}/myimage \
  --set-cloudsql-instances ${PROJECT_ID}:${REGION}:myinstance \
  --set-secrets APPLICATION_SETTINGS=application_settings:latest \
  --service-account $SERVICE_ACCOUNT \
  --allow-unauthenticated
```

The `--[update|set|remove|clear]-secrets` flag is not supported on the fully managed version of Cloud Run

**Comment by glasnt** [comment]
Can you confirm what version of `gcloud` you are running? You may be running an older version from before these settings were available for managed Cloud Run
 
```
gcloud --version
```
