### ISSUE TITLE
[cloud-create-a-vm]: Invalid/wrong region given in ssh command

### ISSUE THREAD

**Issue by FearThe1337** [googlecodelabs/feedback#108]
The tutorial consistently tells the user to create the virtual machine in the region europe-west1-d, the ssh command however uses the zone us-central1-c.
This will result in the ssh command failing to find the virtual machine created by the user.

**Comment by alexismp** [comment]
One could argue that this is to check that users are not blindly copy-pasting commands :)
I'll get it fixed though.

**Comment by alexismp** [comment]
Updated!
