### ISSUE TITLE
[cloud-spring-spanner]:alexismp

### ISSUE THREAD

**Issue by jaidevchattre** [googlecodelabs/feedback#1087]
Running following command fails
curl https://start.spring.io/starter.tgz \
  -d packaging=jar \
  -d dependencies=cloud-gcp,web,lombok \
  -d baseDir=spanner-example \
  -d bootVersion=2.3.3.RELEASE | tar -xzvf -
-bash: $: command not found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
jaidevchattre@cloudshell:~ (jd-dev-343718)$ curl https://start.spring.io/starter.tgz \
  -d packaging=jar \
  -d dependencies=cloud-gcp,web,lombok \
  -d baseDir=spanner-example \
  -d bootVersion=2.3.3.RELEASE | tar -xzvf -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   283    0   186  100    97    620    323 --:--:-- --:--:-- --:--:--   946

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by meteatamel** [comment]
Thanks for reporting, this has been fixed.
