### ISSUE TITLE
[cloud-run-djangocms]: Uniform ACL issues applying migrations

### ISSUE THREAD

**Issue by localhost-rex** [googlecodelabs/feedback#1088]
Step 7, which command is: gcloud builds submit --config migrate.yaml, does not complete successfully due to Uniform ACL being present, the subsequent builds meant for django migration therefore fails

**Comment by glasnt** [comment]
Can you provide the full ACL error encountered? 

Also, try changing the `migrate.yaml` to include `--clear` in the collectstatic command: 

```
python manage.py collectstatic --noinput --clear
```
