### ISSUE TITLE
[cloud-bigquery-load-data]:

### ISSUE THREAD

**Issue by edskim** [googlecodelabs/feedback#11]
> Let’s find out the total number of Wikimedia views by writing this query:
> should be
> Let’s find out the total number of Wikimedia requests by writing this query:

`SELECT SUM(views)
FROM [bigquery-samples:wikimedia_pageviews.201112]`
should be:
`SELECT SUM(requests)
FROM lab.pagecounts_20160108_11`

**Comment by saturnism** [comment]
fixed.
