### ISSUE TITLE
[cloud-starting-cloudrun-jobs] Update for the latest gcloud changes

### ISSUE THREAD

**Issue by meteatamel** [googlecodelabs/feedback#1100]

**Comment by philipp-heinrich** [comment]
I encountered the following bugs in the codelab: 

1. philipp@cloudshell:~/jobs-demos/screenshot (philipph-playground)$ gcloud alpha run jobs execute screenshot
ERROR: (gcloud.alpha.run.jobs) Invalid choice: 'execute'.
Maybe you meant:
  gcloud alpha run jobs

i guess it should be:  gcloud alpha run jobs run screenshot

2. philipp@cloudshell:~/jobs-demos/screenshot (philipph-playground)$ gcloud alpha run jobs screenshot --wait
ERROR: (gcloud.alpha.run.jobs) Invalid choice: 'screenshot'.
Maybe you meant:
  gcloud alpha run jobs

seems that --wait is no longer supported?

**Comment by meteatamel** [comment]
Are you using the latest gcloud? 379.0.0

**Comment by meteatamel** [comment]
Closing this. Feel free to re-open, if you encounter the issue still.
