### ISSUE TITLE
Codelabs don't reflow on mobile screens

### ISSUE THREAD

**Issue by temple-ontherat** [googlecodelabs/feedback#1102]
Your webpage doesn't recognize the width of my cellphone screen. It only shows the left half of the page.

**Comment by PicardParis** [comment]
- Thank you for reporting the issue.
- I could reproduce it and filed an internal bug.
- In the meantime, a possible workaround is to view the codelabs in "Desktop site" mode (if your mobile browser has the option). In this mode, page responsiveness seems to work.
- I currently don't have an ETA for the fix. I'll keep this ticket open...

**Comment by PicardParis** [comment]
The issue was fixed. Marking this issue likewise.
