### ISSUE TITLE
[cloud-spring-spanner]:alexismp Spring Boot 2.3.3.RELEASE is no longer available

### ISSUE THREAD

**Issue by translucens** [googlecodelabs/feedback#1105]
Codelab specifies Spring Boot version `bootVersion=2.3.3.RELEASE`, but its version is no longer available. So we get error and cannot proceed.
When I use `2.6.7.RELEASE`, it works fine.

https://codelabs.developers.google.com/codelabs/cloud-spring-spanner#3

**Comment by meteatamel** [comment]
Thanks for reporting, this has been fixed.
