### ISSUE TITLE
[cloud-starting-cloudrun-jobs]: gcloud is failing to create a job

### ISSUE THREAD

**Issue by mark-russell-bossanova** [googlecodelabs/feedback#1111]
The command
```
gcloud beta run jobs create screenshot \
  --image=$REGION-docker.pkg.dev/$PROJECT_ID/containers/screenshot:v1 \
  --args="https://example.com" \
  --args="https://cloud.google.com" \
  --tasks=2 \
  --task-timeout=5m \
  --set-env-vars=BUCKET_NAME=screenshot-$PROJECT_ID \
  --service-account=screenshot-sa@$PROJECT_ID.iam.gserviceaccount.com
```
Fails to run.  Here is what I get when I run it:
```
Creating Cloud Run job [screenshot] in project [cloud-run-jobs-350018] region [us-central1]
X Creating job...
Job failed to deploy
ERROR: (gcloud.beta.run.jobs.create) Namespaces instance [cloud-run-jobs-350018] not found: Requested entity was not found.
```
This is keeping me from moving on with the tutorial.

I also had to run an upgrade to even get the create command.

**Comment by glasnt** [comment]
Cloud Run Jobs is currently in preview and only available in europe-west9. https://cloud.google.com/run/docs/create-jobs

Add `--region europe-west9` to your command and it should create the job. You do not have to change your image region for this command to work, just the region where the job is executed.
