### ISSUE TITLE
[cloud-starting-cloudrun-jobs] Region causing namespace issue

### ISSUE THREAD

**Issue by EZFRICA** [googlecodelabs/feedback#1115]
ERROR: (gcloud.beta.run.jobs) Invalid choice: 'create'.
This command is available in one or more alternate release tracks.  Try:
  gcloud alpha run jobs create

**Comment by meteatamel** [comment]
Is your gcloud up to date?

**Comment by EZFRICA** [comment]
I use the cloud shell with Google Cloud SDK 384.0.1

Le mar. 24 mai 2022 à 16:01, Mete Atamel ***@***.***> a
écrit :

**Comment by meteatamel** [comment]
Cloud Shell is not up to date yet then. You can use gcloud locally with 386 to get the beta commands

**Comment by EZFRICA** [comment]
Thanks, I have just upgraded to the 386 version but I get an error message
when creating the job.

ERROR: (gcloud.beta.run.jobs.create) Namespaces instance [ProjectID] not
found: Requested entity was not found.

But my namespace is correct.

Le mar. 24 mai 2022 à 16:51, Mete Atamel ***@***.***> a
écrit :

**Comment by meteatamel** [comment]
Hmmm..what is the namespace here in the context of Cloud Run? I'm not sure

**Comment by EZFRICA** [comment]
Th namespaces is projet ID

Le mar. 24 mai 2022 à 17:10, Mete Atamel ***@***.***> a
écrit :

**Comment by meteatamel** [comment]
Can you paste the exact command you're running and the full error you get?

**Comment by EZFRICA** [comment]
https://codelabs.developers.google.com/codelabs/cloud-starting-cloudrun-jobs-io#5

command: gcloud beta run jobs create screenshot \

  --image=$REGION-docker.pkg.dev/$PROJECT_ID/containers/screenshot:v1 \
  --args="https://example.com" \
  --args="https://cloud.google.com" \
  --tasks=2 \
  --task-timeout=5m \
  --set-env-vars=BUCKET_NAME=screenshot-$PROJECT_ID \
  --service-account=screenshot-sa@$PROJECT_ID.iam.gserviceaccount.com


Job failed to deploy
ERROR: (gcloud.beta.run.jobs.create) Namespaces instance [$PROJECT_ID]
not found: Requested entity was not found.


Le mer. 25 mai 2022 à 08:55, Mete Atamel ***@***.***> a
écrit :

**Comment by meteatamel** [comment]
Not sure why this is failing for you. It might be some permission issue but I'm not sure.

**Comment by EZFRICA** [comment]
The problem is in the region you choose. I get the error when I try to
deploy the Job in the *us-central1* region but when I use the *europe-west9*
region everything works fine. I think you have to specify the region to the
people doing the Lab.

**Comment by meteatamel** [comment]
Thanks for the update. Please use the following codelab that is more up to date: https://codelabs.developers.google.com/codelabs/cloud-starting-cloudrun-jobs

We'll delete the other codelab to avoid confusion.

**Comment by meteatamel** [comment]
Closing this as we identified as a region issue.
