### ISSUE TITLE
[cloud-functions-python-http]:

### ISSUE THREAD

**Issue by jsabor** [googlecodelabs/feedback#1116]
directory path change from `python-docs-samples-master` to `python-docs-samples-main`

**Comment by PicardParis** [comment]
- Thanks a lot for the feedback @jsabor
- Codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-functions-python-http
  - Branch `master` → `main`
  - Version `python38` → `python39`
  - Tests ✔
