### ISSUE TITLE
[cloud-app-engine-python3] 

### ISSUE THREAD

**Issue by peldridge-sfdc** [googlecodelabs/feedback#1119]
Hi folks! I'm authoring some codelabs too here, is there any way the markdown .md file for this one could be shared? I'd love to mirror some of the nicer style elements, like the light grey font, the survey integrated in the first page, etc.

Thank you!

**Comment by peldridge-sfdc** [comment]
I also love the in-line code highlighting in the font, `like this`, how does one do that? I don't see that in the official Format Guide.md :(

**Comment by glasnt** [comment]
This all should be detailed in https://github.com/googlecodelabs/tools/blob/main/FORMAT-GUIDE.md

**Comment by peldridge-sfdc** [comment]
@glasnt a lot of that[ format guide ](https://github.com/googlecodelabs/tools/blob/main/FORMAT-GUIDE.md) seems to assume someone is using the Google Doc workflow, we're working directly from the .md file in a code editor. 

Do most folks just use the Google Doc template with a bunch of those formatting elements, then use the Chrome extension to generate an example .md file from it and work from that instead? 

Also (maybe I'm dense and missing this) -- is the assumption then that if I want to get that nicer gentler dark grey font aesthetic on the official Google codelabs, I MUST use the Google doc and manually change the text color so the .md has that auto-embedded? 

Sorry for the n00b questions. :) 

EDIT: I found the answer for the in-line code, that's a single back-tick. `like this` (again, the official format-guide doesn't tell you ANY of this).
