### ISSUE TITLE
[cloud-route-datadog-eventarc-part-one] Add workflows.googleapis.com to the list of APIs enabled in Step 2

### ISSUE THREAD

**Issue by rominirani** [googlecodelabs/feedback#1124]
Couple of points:

1. Step 5: Create a workflow. When you execute the script to deploy the workload, it mentions the following:

```
API [workflows.googleapis.com] not enabled on project [<PROJECT_ID>]. Would you like to enable and retry (this will take a few minutes)? (y/N)?
```
It might be a good idea to enable the workflows.googleapis.com in Step 2 : Setup and Requirements itself, along with the other services that are enabled. 

2. Why do we have cloudbuild and run APIs enabled in Step 2 : Setup and Requirements?

**Comment by meteatamel** [comment]
I was using Cloud Run before as the event sink, that's why I had Cloud Build and didn't have Workflows APIs. Good patch. Fixed now.
