### ISSUE TITLE
[cloud-route-datadog-eventarc-part-one] Confusion around Full Channel Name and Activation Token

### ISSUE THREAD

**Issue by rominirani** [googlecodelabs/feedback#1126]
In Step 4 : Setup a channel, the lab does make a statement ```Note the channel full name and the activation token.```

We should highlight this in bold and tell the user that it is going to be used later on in the step. The reason for mentioning this is that if the user goes through it too quickly (which I did), then there is a slight confusion on what value to use to create the channel in Datadog. 

Maybe, we can annotate the image below that is used in the codelab and highlight in a red box : Channel full name and Activation token?

<img src="https://codelabs.developers.google.com/static/codelabs/cloud-route-datadog-eventarc-part-one/img/80d8b2b6a46cb4c5.png"/>

**Comment by meteatamel** [comment]
I put the "Note the channel full name and activation token" in a warning box
