### ISSUE TITLE
[cloud-route-datadog-eventarc-part-one] Error on adding Channel in Datadog

### ISSUE THREAD

**Issue by rominirani** [googlecodelabs/feedback#1127]
While executing Step 4 : Setup a Channel, the channel got added successfully but it also showed an error message as given below:

<img src="https://drive.google.com/uc?id=1mLODW-3t03VTZOiIQjivuNZgdEMsv7x_"/>

A refresh of the page made the error message go away. So it did not cause any issue.

**Comment by meteatamel** [comment]
I think this is a temporary glitch, nothing we can do in the codelab, so closing it
