### ISSUE TITLE
[cloud-route-datadog-eventarc-part-one] screenshot discrepancy between instructions in lab and actual datadog screens

### ISSUE THREAD

**Issue by rominirani** [googlecodelabs/feedback#1128]
In Step 7 : Create a Datadog monitor, the instructions include:

```
In step 4, set Notify your team to @eventarc_<your-project-id>_<your-region>_<your-channel-name>
In step 5, set Test monitor for Eventarc as the monitor name
```

The Datadog UI was different when I tried it out and both Step 4 and Step 5 in the instructions above were present in Step 4 itself as the screenshot below indicates:

<img src="https://drive.google.com/uc?id=1wjV8dcEvmmDsqz3WVQXbDf9mKRllZvOk"/>

**Comment by meteatamel** [comment]
Updated the instructions
