### ISSUE TITLE
Step 23 of "Build a Progressive Web App with Firebase, Polymerfire and Polymer Components": Cannot read property 'isNew' of undefined

### ISSUE THREAD

**Issue by tony19** [googlecodelabs/feedback#113]
> na-behavior.html:76 Uncaught TypeError: Cannot read property 'isNew' of undefined(…)

At [Step 23](https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/index.html?index=..%2F..%2Findex#22), after filling out a new note and clicking the **DONE** button, a `TypeError` occurs in `NoteAppBehaviorImpl.save()`. It appears `this.$.document` does not exist, and there wasn't a step in the codelab to add that element. (Was it supposed to be included in one of the `na-elements.html`?)

![screen shot 2016-11-25 at 12 25 09 am](https://cloud.githubusercontent.com/assets/26580/20616159/c9654118-b2a5-11e6-95f5-e66764f19978.png)

**Comment by tony19** [comment]
I think the codelab is missing a step to add `<firebase-document>`, as seen in the [`polymerfire` demo code for `<note-app>`](https://github.com/firebase/polymerfire/blob/03f64c2/demo/note-app.html#L65-L70).

But even after adding `<firebase-document>`, we hit another error:
> firebase-database.js:129 Uncaught (in promise) Error: Firebase.child failed: First argument was an invalid path: "". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"(…)

...caused by `NoteAppBehaviorImpl.notesPath` being an empty string:
![screen shot 2016-11-25 at 12 39 41 am](https://cloud.githubusercontent.com/assets/26580/20616399/b0bd17ba-b2a7-11e6-835a-906689ee7038.png)
![screen shot 2016-11-25 at 12 38 44 am](https://cloud.githubusercontent.com/assets/26580/20616388/9a2f4ffe-b2a7-11e6-8a01-4be9d0c0a4b1.png)

The workaround there is to edit `NoteAppBehaviorImpl.notesPath` in `bower_components/note-app-elements/na-behavior.html` to match the [`polymerfire` demo code](https://github.com/firebase/polymerfire/blob/03f64c2/demo/note-app.html#L94-L96):

    get notesPath() {
      return '/notes/' + this.user.uid;
    },

Make sure to unregister/delete the running service worker to reload this change.

**Comment by tony19** [comment]
Oh, duh. The necessary changes are described in [Step 24](https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/index.html?index=..%2F..%2Findex#23).

**Comment by gauravonly** [comment]
@tony19 --  thanks a lot. Its working fine for me now :)
