### ISSUE TITLE
[cloud-route-datadog-eventarc-part-two] Step 4 : Different Datadog screen

### ISSUE THREAD

**Issue by rominirani** [googlecodelabs/feedback#1130]
This is not per se a problem with the lab but the Step 4 in the lab mentions about a screen as shown below:

<img src="https://codelabs.developers.google.com/static/codelabs/cloud-route-datadog-eventarc-part-two/img/92e475e4da7f826.png"/>

Feedback to Datadog team: After the service account key is successfully uploaded, the message displayed by Datadog screen is as follows:

<img src="https://drive.google.com/uc?id=1-TXR8loGe6HtQH32_3w1v0eo4xGdeweP"/>

`Service account successfully uploaded. Click Update Configuration to save changes.`

Note that there is no `Update Configuration` on the screen here. 

I went back, refreshed and then it was fine.

**Comment by meteatamel** [comment]
Ok, I'll close this, as we can't really do anything about this in the codelab.
