### ISSUE TITLE
[cloud-route-datadog-eventarc-part-two] Step 5 - Datadog UI not displayed Compute Engine VMs

### ISSUE THREAD

**Issue by rominirani** [googlecodelabs/feedback#1131]
Followed the steps of Step 5 and created the VMs using `gcloud` commands. 

After a while, the data appeared inside of Datadog but only for the count of VMs i.e. 2. The other chart despite even selecting the dropdowns for project, etc is not getting updated and remains blank with the error as shown below:

<img src="https://drive.google.com/uc?id=1SXIvsawEhxZR9auUuBMHbTUqwAiocOE-"/>

It says `Node without metrics are hidden`.

**Comment by meteatamel** [comment]
Yes, it takes a while for Datadog UI to catch up with all metrics and charts. I'm closing this as there's not much we can do about it in the codelab.
