### ISSUE TITLE
[cloud-run-django]: python3 required

### ISSUE THREAD

**Issue by nhoussay** [googlecodelabs/feedback#1134]
when i ran this tutorial i had to use "python3" instead of "python" in the migrate.yaml file

**Comment by beandropcompany** [comment]
I believe I am having the same issue following the code labs cloud run django tutorial. Without modifying the migrate.yaml file and running the migration: gcloud builds submit --config migrate.yaml 

```
Step #1 - "migrate": bash: python: command not found
Finished Step #1 - "migrate"
ERROR
```

Changing the migrate.yaml file from
```
args: 
      - "bash"
      - "-c"
      - "(/cloudsql/cloud_sql_proxy -instances=${_INSTANCE_CONNECTION_NAME}=tcp:5432 & sleep 2) && 
          python manage.py migrate && 
          python manage.py collectstatic --noinput"
```

to python3

**Comment by glasnt** [comment]
The codelab has been updated with this change. Thanks for the report!
