### ISSUE TITLE
[cloud-spring-spanner]:alexismp

### ISSUE THREAD

**Issue by Edward-jbc** [googlecodelabs/feedback#1136]
curl https://start.spring.io/starter.tgz \
  -d packaging=jar \
  -d dependencies=cloud-gcp,web,lombok \
  -d baseDir=spanner-example \
  -d bootVersion=2.3.3.RELEASE
{"timestamp":"2022-08-05T05:23:37.284+00:00","status":400,"error":"Bad Request","message":"Dependency 'cloud-gcp' is not compatible with Spring Boot 2.3.3.RELEASE","path":"/starter.tgz"}

How to resolve this issue? It seems likt Spring Boot 2.3.3 has been deprecated

**Comment by meteatamel** [comment]
Thanks for reporting, this has been fixed.
