### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by rainbowbreeze** [googlecodelabs/feedback#114]
Managed VMs only work in US zone. The project has to be set to that zone, other ones doesn't work.

It is not specified in the instructions, so some people here in Italy are using EU as zone, and have an error when they deploy everything in step 8.

**Comment by meteatamel** [comment]
Hi @rainbowbreeze, sorry for the 6+ years delay to reply to the issue :-) But the codelab now shows instructions to deploy to us-central1, so this should not be an issue.
