### ISSUE TITLE
[secret-manager-python]: Notification of a small error 

### ISSUE THREAD

**Issue by imak-h** [googlecodelabs/feedback#1141]
Hello Google team, 

Just want to notify you a small error in this tutorial :
https://codelabs.developers.google.com/codelabs/secret-manager-python#9

The error
`ERROR: (gcloud.functions.deploy) unrecognized arguments:
  --set-env-var (did you mean '--set-env-vars'?)`

The code

```
gcloud functions deploy secret_hello \
    --runtime python39 \
    --set-env-var PROJECT_ID=${PROJECT_ID} \
    --trigger-http \
    --allow-unauthenticated
    
```
-> Lack a 's' to 'set-env-var'

Have a good day!

**Comment by glasnt** [comment]
Thanks for the report, @imak-h! We'll get that cleaned up for you.
