### ISSUE TITLE
[cloud-run-wagtail]: Migration failed, error 127

### ISSUE THREAD

**Issue by kryzpt** [googlecodelabs/feedback#1142]
Fails at the run the migrations step using command 'gcloud builds submit --config migrate.yaml'. 
ERROR: build step 1 "gcr.io/xxxxxxxxxxxxx/myimage-proxy" failed: step exited with non-zero status: 127

**Comment by glasnt** [comment]
Hi @kryzpt Are you able to provide more information about the error? There should be some additional error message along with the 127 code.
