### ISSUE TITLE
[cloud-slack-bot]: Port misconfig, maybe because of outdated resources?

### ISSUE THREAD

**Issue by NachoRondan** [googlecodelabs/feedback#1143]
Follow the tutorial step by step and got this error, tried A LOT OF THINGS but couldn't solve it. This might be outdated, here's the error:

`Cloud Run error: The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable.`

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
