### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by kswat** [googlecodelabs/feedback#1147]
Tried war based on the notes

"There are two ways to deploy a Java server app—either by using Maven App Engine Plugin or Gradle App Engine Plugin, or by deploying the war package directory"

Error

[INFO] GCLOUD: File upload done.
[INFO] GCLOUD: Updating service [default]...
[INFO] GCLOUD: ...................................................................................................................failed.
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build dd6######6b1e9 status: FAILURE
[INFO] GCLOUD: did not find any jar files with a Main-Class manifest entry

How to deploy war ?

**Comment by meteatamel** [comment]
Fixing with cl/523700032

**Comment by meteatamel** [comment]
Fixed
