### ISSUE TITLE
[cloud-vision-python]: typo in 

### ISSUE THREAD

**Issue by palladius** [googlecodelabs/feedback#1148]
page: https://codelabs.developers.google.com/codelabs/cloud-vision-api-python#7 

current: In this example, you will perform text detection on an image of an Otter Crossing. Copy the following snippet into your IPython session (or save locally as text_dectect.py):

should be: In this example, you will perform text detection on an image of an Otter Crossing. Copy the following snippet into your IPython session (or save locally as text_detect.py):

note code is ok: https://github.com/googlecodelabs/cloud-vision-python

**Comment by PicardParis** [comment]
Thanks for feedback. The codelab is being updated...

**Comment by PicardParis** [comment]
Typos have been fixed. Thanks again!
