### ISSUE TITLE
[cloud-run-django]:

### ISSUE THREAD

**Issue by BrianGreigAE** [googlecodelabs/feedback#1151]
When I run the command gcloud builds submit --config migrate.yaml I get the following error in the build based on your guidance inthe codelab. https://codelabs.developers.google.com/codelabs/cloud-run-django#6 Please can you explain what is going on? I followed your tutorial step-by-step and this fails every time

Step #1 - "migrate": 2022/09/24 21:54:04 Ready for new connections
Step #1 - "migrate": 2022/09/24 21:54:04 Generated RSA key in 121.745165ms
Step #1 - "migrate": bash: python: command not found
Finished Step #1 - "migrate"
ERROR

**Comment by Trashami** [comment]
Same issue here

**Comment by glasnt** [comment]
Hi @BrianGreigAE! Thanks for the report. 

The step should be running `python3`, not `python`. Your output doesn't match what the codelab says to run. Try `python3` and it should work.
