### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by sabuj-das** [googlecodelabs/feedback#1153]
The path to maven project is not on the root directory in gs-spring-boot.
Needed to change the directory to one of the following: 
drwxr-xr-x  6 sabuj_das sabuj_das  4096 Sep 30 08:59 complete
drwxr-xr-x  5 sabuj_das sabuj_das  4096 Sep 30 08:58 initial
drwxr-xr-x  2 sabuj_das sabuj_das  4096 Sep 30 08:58 test

A step should be added to `cd complete`

**Comment by meteatamel** [comment]
In step 3, there's `cd gs-spring-boot/complete`
