### ISSUE TITLE
[cloud-slack-bot]: Command to fetch SERVICE_ACCOUNT email address needs possible correction

### ISSUE THREAD

**Issue by AndrewZurn** [googlecodelabs/feedback#1154]
Hey there,

I was going through the Cloud Slack Bot code lab tutorial, and when trying to get the Service Account needed to install my application on cloud run using the command below, I noticed what could possibly be an error. The potential error is on this page: https://codelabs.developers.google.com/codelabs/cloud-slack-bot/index.html#7

Command in question:
```
export SERVICE_ACCOUNT=$(gcloud iam service-accounts list --format 'value(EMAIL)' --filter 'NAME:Default compute service account')
```

I noticed the variable had no value in it after running the above command. Looking at the account in question from the IAM Service Account UI, I noticed the name is different than the one above.

![image](https://user-images.githubusercontent.com/2126119/193353980-416d20ff-f5ea-4fbd-af1c-25c4d6269e97.png)

I'm not familiar enough to know if the name for this account is default across all new GCP projects or not, but if it is, the command above should be updated to:
```
export SERVICE_ACCOUNT=$(gcloud iam service-accounts list --format 'value(EMAIL)' --filter 'NAME:Compute Engine default service account')
```
which will produce the wanted result.

I'll open a Pull Request and link this issue sometime in the near future.

Thanks for the great tutorial!

**Comment by AndrewZurn** [comment]
It also looks like port 8080 needs to be exposed in the docker file and for some reason the 'requests' library needs to be installed (I'm surprised it wasn't brought in as a transitive dependencies of the slack libraries... but I'm no NPM expert 🤷‍♂️ ). Will include those in the PR as well.

**Comment by AndrewZurn** [comment]
Nevermind on submitting a PR - totally missed that this repo is just for tracking issues and doesn't have the actual samples in it.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.

**Comment by AndrewZurn** [comment]
Thanks, @PicardParis
