### ISSUE TITLE
[cloud-run-django]: walkthrough fails at the create the database step, timeout

### ISSUE THREAD

**Issue by shan-alexander** [googlecodelabs/feedback#1159]
On page: https://codelabs.developers.google.com/codelabs/cloud-run-django#4

Under the tutorial section "Create the database":

gcloud sql instances create myinstance --project $PROJECT_ID \
  --database-version POSTGRES_13 --tier db-f1-micro --region $REGION

This command gives me this error:

Creating Cloud SQL instance for POSTGRES_13...failed.   
ERROR: (gcloud.sql.instances.create) Operation https://sqladmin.googleapis.com/sql/v1beta4/projects/motobay-853211/operations/ef08b1e4-c0a7-4727-8f86-fd9d00000025 is taking longer than expected. You can continue waiting for the operation by running `gcloud beta sql operations wait --project motobay-853211 ef08b1e4-c0a7-4727-8f86-fd9d00000025` 

After running the suggested command for waiting, I wait a few minutes and then receive the same message.

The tutorial does not suggest what I should do to troubleshoot in this situation.

**Comment by glasnt** [comment]
Hi @shan-alexander. If you run the `gcloud beta sql operations wait` command suggested, that will let you know when the database provisioning step has finished.

**Comment by shan-alexander** [comment]
Thanks, I ran that command and it timed out again. But then I went over to
Cloud SQL and saw the instance existed normally, so it seems the
provisioning step finished, and I was able to continue the walkthrough.
That might be a nice one-liner note to add to the walkthrough. Thanks
