### ISSUE TITLE
[cloud-springboot-cloudshell]:

### ISSUE THREAD

**Issue by MirceaHalmagean** [googlecodelabs/feedback#1167]
sample contains gradle sample app not maven as specified in the guide - step 3 - 

https://codelabs.developers.google.com/codelabs/cloud-springboot-cloudshell?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fjava-cloud-fundamentals%3Fhl%3Den%23codelab-https%3A%2F%2Fcodelabs.developers.google.com%2Fcodelabs%2Fcloud-springboot-cloudshell#2

```
curl https://start.spring.io/starter.tgz \
  -d dependencies=web -d baseDir=helloworld | tar -xzvf -
```

**Comment by meteatamel** [comment]
Fixed with cl/523667511.
