### ISSUE TITLE
[cloud-run-django] Service Unavailable

### ISSUE THREAD

**Issue by ahmadzfaiz** [googlecodelabs/feedback#1169]
Hi, I try to follow the instruction to deploy Django on Cloud Run. After deploying, the service is unavailable like this 
![image](https://user-images.githubusercontent.com/75885530/199428317-14791f0f-1722-4316-b808-1fe706e9bf9c.png)
What wrong with my instance?

**Comment by glasnt** [comment]
Check the Logs against your Cloud Run service. That will show you the python traceback which can help you identify the issue. Without more details, I can't help diagnose your issue.
