### ISSUE TITLE
[cloud-networking-101]:

### ISSUE THREAD

**Issue by kylgoog** [googlecodelabs/feedback#117]
Slide 17: --http-health-checks instead of --http-health-check
gcloud compute backend-services create global-bs --protocol http --http-health-checks basic-check

Slide 21: --source-ranges instead of --source-range
gcloud compute firewall-rules create  NAME --allow=PROTOCOL[:PORT[-PORT]],[PROTOCOL[:PORT[-PORT]],...] [optional flags]
ERROR: (gcloud.compute.firewall-rules.create) unrecognized arguments:
  --source-range (did you mean '--source-ranges'?)

**Comment by thesmiler** [comment]
Hi,
thanks for your feedback. We completely rebuilt this lab and these commands are not part of it anymore.
