### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by DeeVine** [googlecodelabs/feedback#1170]
I've tried repurposing the kittenbot code for my own application. When trying to run deploy of my docker image I'm getting this error: "(gcloud.run.deploy) The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information."

I didn't see anything about ports in the Kittenbot code, so was wondering how the kittenbot code is handling the port container contract or is it? https://cloud.google.com/run/docs/container-contract

**Comment by hugo-ayala** [comment]
bumping this. I'm seeing the same error when following along the tutorial: 
https://codelabs.developers.google.com/codelabs/cloud-slack-bot#7

**Comment by DeeVine** [comment]
hey @hugo-ayala I was able to resolve the error by switching off of socket mode. I think the problem is that socket mode uses something like a dynamic websocket and doesn't listen on port 8080 so cloudrun never receives a response. 

I switched to http method instead of socket mode and then it deployed correctly. If you need help with this, let me know and I can give you a couple pointers.

**Comment by hugo-ayala** [comment]
Hi @DeeVine sorry for the late reply. I was able to solve this issue for my use case, I was doing something wrong with my cloud function definition.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
