### ISSUE TITLE
[cloud-app-engine-springboot]: java deploy spring boot codelab is confused between maven and gradle

### ISSUE THREAD

**Issue by bogdan-marian** [googlecodelabs/feedback#1171]
The tutorial assumes that the command from Sept 3 (create a new spring boot we app) generates a maven project but the project generated is a grade one. As a consequence, all the following instructions from step 3 as far as configuration and dependencies go are wrong. 

https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot#2

**Comment by meteatamel** [comment]
Fixing with cl/523700032

**Comment by meteatamel** [comment]
Fixed

**Comment by bogdan-marian** [comment]
@meteatamel Could we also have a Gradle appengine standard tutorial? App Engine development requires some extra configuration, and I think it's important to cover that. I recently started a project on App Engine Standard and found that configuring it was a bit challenging. Some configuration had to be done through yum files, while others required XML files. Unfortunately, the documentation for Java 11 and configuration can be inconsistent. Sometimes you get lucky, but other times it can take days of trial and error to figure out the right combination of config that works with Gradle and Java 11 on Standard App Engine.

**Comment by meteatamel** [comment]
Hi @bogdan-marian, could you please open a new issue with `[cloud-app-engine-springboot]` tag and summmarize what you're looking for? Let me know the issue number so I can assign to myself. I'll see what I can do. Not an expert in Gradle but I can look into it. Thanks.

**Comment by bogdan-marian** [comment]
Hi @meteatamel I created this issue here: https://github.com/googlecodelabs/feedback/issues/1218
Thank allot for your suggestion
