### ISSUE TITLE
[cloud-text-speech-python3] 

### ISSUE THREAD

**Issue by jharaldson** [googlecodelabs/feedback#1176]
Step 4 in the English version is missing a step to bind the correct role to enable step 7, listing languages.

`gcloud projects add-iam-policy-binding ${PROJECT_ID} --member serviceAccount:my-tts-sa@${PROJECT_ID}.iam.gserviceaccount.com   --role roles/serviceusage.serviceUsageConsumer`

**Comment by PicardParis** [comment]
Thanks @jharaldson for reporting the issue. The [codelab](https://codelabs.developers.google.com/codelabs/cloud-text-speech-python3#3) has just been fixed (+ minor versioning/result updates).
