### ISSUE TITLE
[cloud-springboot-cloudshell]:

### ISSUE THREAD

**Issue by qericdev** [googlecodelabs/feedback#1178]
Executing (Point 3) -> curl https://start.spring.io/starter.tgz \
  -d dependencies=web -d baseDir=helloworld | tar -xzvf -
Download files for app with Gradle.
After this, at point 5. The command is ./mvnw -DskipTests spring-boot:run (using Maven).

**Comment by meteatamel** [comment]
Fixed with cl/523667511.
