### ISSUE TITLE
[cloud-run-django]:

### ISSUE THREAD

**Issue by udbajaj7** [googlecodelabs/feedback#1179]
running the command- gcloud builds submit --pack image=gcr.io/${PROJECT_ID}/myimage

returns an error saying- 
python setup.py egg_info did not run successfully
Error: pg_config executable not found.
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51
ERROR
ERROR: build step 0 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zero status: 1

**Comment by glasnt** [comment]
This is probably the same as #1174 

Try the suggested fix in https://github.com/googlecodelabs/feedback/issues/1174#issuecomment-1339974971
