### ISSUE TITLE
[cloud-text-speech-python3] Non-breaking space present in code snippets

### ISSUE THREAD

**Issue by rejuvi-uk** [googlecodelabs/feedback#1184]
Tutorial code results in an error:

 Cell In[1], line 20
    
    ^
SyntaxError: invalid non-printable character U+00A0

**Comment by PicardParis** [comment]
Hi @rejuvi-uk
- There was a non-breaking space (`&nbsp;` in HTML, `U+00A0` in Unicode) at the end of the code snippets. Deleting the last line was the solution.
- The codelab has been fixed: https://codelabs.developers.google.com/codelabs/cloud-text-speech-python3
- Closing this ticket. Feel free to reopen it if anything else is incorrect.
