### ISSUE TITLE
[cloud-run-djangocms]:psycopg2-binary==2.9.2 install error

### ISSUE THREAD

**Issue by melissabonds** [googlecodelabs/feedback#1200]
This [psycopg2-binary==2.9.2] in requirements.txt fails in Step 7.   psycopg2-binary==2.9.5 seems to resolve the problem. 
Collecting psycopg2-binary==2.9.2

[builder]       Error: pg_config executable not found.
[builder]
[builder]       pg_config is required to build psycopg2 from source.  Please add the directory
[builder]       containing pg_config to the $PATH or specify the full executable path with the

**Comment by glasnt** [comment]
Yes, that's the correct fix. I'll see about updating this codelab to point to the correct version.
