### ISSUE TITLE
[cloud-springboot-cloudshell]: Spring Boot updated

### ISSUE THREAD

**Issue by efredericks** [googlecodelabs/feedback#1203]
Issue with **Build and launch a Spring Boot Java app from Cloud Shell** - Spring Boot updates.

Resolution:

1. Generate a new project from the spring boot starter site: https://start.spring.io/
    * Settings:
        * Project: Maven
        * Language: Java
        * Spring Boot: 2.7.9
        * Java Version: 11
2. Download the file (will come down as demo.zip) and upload to your Cloud Shell (you upload similar to the SSH upload).
3. Unzip:  unzip demo.zip
4. Go into the demo folder (will not be helloworld as mentioned).
5. Edit the pom.xml file:
    * Ensure the Java version is 11
    * Add the following dependency for Spring Boot:

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
```

Project *should* work after this point per the instructions.

**Comment by efredericks** [comment]
Note - this is working around the problem by downgrading to Java 11 and Spring Boot 2.7.9 instead of updating to the latest versions.

**Comment by meteatamel** [comment]
Fixed in the latest update by asking the user to set the JAVA_HOME
