### ISSUE TITLE
[cloud-picadaily-lab1]: choose "SELECT DATASTORE MODE" in Step 9

### ISSUE THREAD

**Issue by ikopyl** [googlecodelabs/feedback#1206]
Currently, choosing "SELECT NATIVE MODE" in [Lab 1 Step 9](https://codelabs.developers.google.com/codelabs/cloud-picadaily-lab1?hl=en#8) makes the results of the Lab 1 incompatible with Lab 4, as the native mode is not supported in the App Engine; it will also block users from [creating an App Engine instance in Lab 4](https://codelabs.developers.google.com/codelabs/cloud-picadaily-lab4?hl=en#6).

Opting to use "SELECT DATASTORE MODE" is a viable alternative.

**Comment by ikopyl** [comment]
The actual solution to the issue: do Lab 4 before Lab 1, i.e. create an App Engine instance before creating a Firestore database.

**Comment by meteatamel** [comment]
Hi @ikopyl, in a brand new project, I tried creating Firestore in native mode (Lab 1) and then tried to create an App Engine app afterwards (Lab 4) and it all worked fine for me. Not sure what was different in your case but closing it. Please comment if you have further feedback.
