### ISSUE TITLE
[cloud-spring-cloud-gcp-secret-manager]: Outdated tutorial

### ISSUE THREAD

**Issue by askvortcov** [googlecodelabs/feedback#1208]
This tutorial is no longer valid. It is missing the "spring.config.import" step of configuration, without which the secret manager is not getting initialized.

See https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager-config-data-resource for up-to-date documentation.

**Comment by askvortcov** [comment]
Tutorial at: https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-secret-manager#1

**Comment by meteatamel** [comment]
Fixed

**Comment by askvortcov** [comment]
I do not see the fix at https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-secret-manager#4

Can you specify how you fixed it?

**Comment by meteatamel** [comment]
I fixed the previous step and then went through the codelab and it all worked for me. Are you seeing something different?

**Comment by askvortcov** [comment]
I see that you just referred to the documentation which I provided. I was looking for a mention of "spring.config.import". 

Statement: 

> This will automatically configure a Spring Property Source, so that you can simply refer to secrets using a property value

is not true. 

Documentation is quite implicit about the matter, just putting the line `spring.config.import=sm://` in-between.

I've tried removing this line from my config, and the application becomes immediately broken.

Is it not better to include it in the tutorial?

eg:
  
>  In your application.properties file, you have to mention
>  
>     `spring.config.import=sm://`
>  to make Spring Boot aware of the secret manager.

**Comment by meteatamel** [comment]
No, what I meant is that, I fixed something broken in this step: https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-secret-manager#3

And I went through the codelab from beginning to end and it worked for me.

So, I'm not sure what is broken in the codelab. Could you clarify?
