### ISSUE TITLE
[cloud-functions-python-http]…

### ISSUE THREAD

**Issue by KAbakumov** [googlecodelabs/feedback#1212]
Samples which are referenced in this codelab are no longer maintained: https://github.com/GoogleCloudPlatform/python-docs-samples/commit/47929f934b4a00e0866b4a1d29af647fcd89aadb

**Comment by PicardParis** [comment]
Thanks Konstantin for reporting the issue. This will be fixed this week.

**Comment by PicardParis** [comment]
The codelab has just been updated:
- https://codelabs.developers.google.com/codelabs/cloud-functions-python-http

**Comment by KAbakumov** [comment]
Thank you!
