### ISSUE TITLE
[cloud-text-speech-python3]…

### ISSUE THREAD

**Issue by RandomMerlin** [googlecodelabs/feedback#1216]
I believe the line

from google.cloud import translate

should read

from google.cloud import texttospeech

**Comment by PicardParis** [comment]
Thank you @RandomMerlin for the feedback. I forgot to remove the related section (imports are correct in individual steps). Will update the codelab this week...

**Comment by PicardParis** [comment]
- The codelab has just been updated:
  - https://codelabs.developers.google.com/codelabs/cloud-text-speech-python3
- Thanks again!
