### ISSUE TITLE
[cloud-functions-python-http] Directory python-docs-samples-main/codelabs/functions/python_powered/ does not exist

### ISSUE THREAD

**Issue by alescuad-sqsp** [googlecodelabs/feedback#1217]
Hi! Currently following this tutorial: https://codelabs.developers.google.com/codelabs/cloud-functions-python-http

But when changing the directory to: python-docs-samples-main/codelabs/functions/python_powered, returns a 'directory does not exist' error.

**Comment by PicardParis** [comment]
Hi @alescuad-sqsp,
- Sorry about this, the source code was deleted in the original repo. I'm working on restoring it in another repo.
- This should be fixed this week. Will keep you updated...

**Comment by PicardParis** [comment]
Hi @alescuad-sqsp,
The codelab has just been updated:
- https://codelabs.developers.google.com/codelabs/cloud-functions-python-http
