### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by hrlwfres** [googlecodelabs/feedback#122]
Hi 
mvn gcloud:deploy fails. Please see the screenshot for details

![image](https://cloud.githubusercontent.com/assets/3857484/21429111/a843a7e0-c85d-11e6-965c-dfd634195197.png)

**Comment by hrlwfres** [comment]
the tutorial misses : 
* the command gcloud app create
* the information that a Billing Account must be set
* the project is deprecated (yaml stuff) and should probably be replaced by https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/helloworld-springboot 
* the information that flex deployment is not supported in europe-west

**Comment by meteatamel** [comment]
Fixed in the latest updates.
