### ISSUE TITLE
[cloud-speech-text-python3]…

### ISSUE THREAD

**Issue by ricardofunke** [googlecodelabs/feedback#1221]
Looks like both speech.RecognitionConfig and speech.RecognitionAudio requires a dictionary, not parameters.

**Comment by PicardParis** [comment]
Hi @ricardofunke,
- I just rechecked and everything seems correct.
-  `speech.RecognitionConfig` and `speech.RecognitionAudio` are based on `proto.message` that gets initialized as follows:
   - `(mapping=None, ignore_unknown_fields=False, **kwargs)`
   - You can alternatively use a dict (`mapping=`) or parameters (`**kwargs`).
   - I'm not getting any linter warning (both local VS Code or online Cloud Shell Editor).
- Closing this ticket. Please feel free to reopen it with more details if you're still meeting any issue.
