### ISSUE TITLE
[secret-manager-python]:

### ISSUE THREAD

**Issue by bmurphy34** [googlecodelabs/feedback#1222]
Is the line
from google.cloud import secretmanager
missing from this example?

**Comment by PicardParis** [comment]
Hi @bmurphy34,
- The code is entered in interactive mode under IPython: it's cumulative and the import has already been done earlier.
- Does it answer your concern? If you're meeting an issue, can you please provide more details?

**Comment by bmurphy34** [comment]
That answers my question, thanks for taking a look!
