### ISSUE TITLE
[cloud-slack-bot]: Codelab updates needed

### ISSUE THREAD

**Issue by mikhailbahdashych** [googlecodelabs/feedback#1225]
Here is the page where the issue has been discovered: [https://codelabs.developers.google.com/codelabs/cloud-slack-bot#4](https://codelabs.developers.google.com/codelabs/cloud-slack-bot#4)

In your guideline on page 5, at the bottom of the page, you gave a link to the Cloud Console Secret Manager page, but the link leads to [https://pantheon.corp.google.com/security/secret-manager](https://pantheon.corp.google.com/security/secret-manager), which doesn't seem to be true Cloud Console Secret Manager (because the Secret Manager is available under this link: [https://console.cloud.google.com/security/secret-manager](https://console.cloud.google.com/security/secret-manager))

![image](https://github.com/googlecodelabs/feedback/assets/77570020/15b1fae3-8566-47df-91a5-e88b8bb6b523)

**Comment by PicardParis** [comment]
Thanks for reporting the issue. You're correct, the link should be https://console.cloud.google.com/security/secret-manager. I'll have a look asap.

**Comment by PicardParis** [comment]
FYI, the source code also needs to be fixed/updated. This should be published a bit later this week...

**Comment by mikhailbahdashych** [comment]
I have noticed that many things need to be updated/their documentation needs to be updated, including used packages.

**Comment by PicardParis** [comment]
Agreed. The tutorial can also be simplified. Stay tuned...

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback. Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
