### ISSUE TITLE
[your-first-webgpu-app] Chapter 8 has errors in code

### ISSUE THREAD

**Issue by kassu11** [googlecodelabs/feedback#1235]
# Description

- Chapter 8 has two coding snippets errors. One is a minor error and the other breaks the code.

## The code breaking error

- The `Use Bind Group and Pipeline Layouts` section shows this code snippet

```js
// Create the bind group layout and pipeline layout.
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [{
    binding: 0,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
    buffer: {} // Grid uniform buffer
  }, {
    binding: 1,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
    buffer: { type: "read-only-storage"} // Cell state input buffer
  }, {
    binding: 2,
    visibility: GPUShaderStage.COMPUTE,
    buffer: { type: "storage"} // Cell state output buffer
  }]
});
```

- When you get to the `Compute passes` section, your code is supposed work, but instead, you get these errors:

```
Entry point's stage (ShaderStage::Fragment) is not in the binding visibility in the layout (ShaderStage::(Vertex|Compute)).
 - While validating that the entry-point's declaration for @group(0) @binding(0) matches [BindGroupLayout "Cell Bind Group Layout"]
 - While validating the entry-point's compatibility for group 0 with [BindGroupLayout "Cell Bind Group Layout"]
 - While validating fragment stage ([ShaderModule "Cell shader"], entryPoint: fragmentMain).
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "Cell pipeline"]).

[Invalid RenderPipeline "Cell pipeline"] is invalid.
 - While encoding [RenderPassEncoder].SetPipeline([Invalid RenderPipeline "Cell pipeline"]).

[Invalid CommandBuffer] is invalid.
    at ValidateObject (..\..\third_party\dawn\src\dawn\native\Device.cpp:689)
    at ValidateSubmit (..\..\third_party\dawn\src\dawn\native\Queue.cpp:444)
```

- The error is created in the snippet code above and the code should be like this:

```js
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [{
    binding: 0,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT | GPUShaderStage.COMPUTE,
    buffer: {} // Grid uniform buffer
  }, {
    binding: 1,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT | GPUShaderStage.COMPUTE,
    buffer: { type: "read-only-storage" } // Cell state input buffer
  }, {
    binding: 2,
    visibility: GPUShaderStage.COMPUTE,
    buffer: { type: "storage" } // Cell state output buffer
  }]
});
```

- So the `GPUShaderStage.FRAGMENT` is missing from visibility, which breaks the code

## Second minor fix

- Under the `Compute passes` section there are two code snippets where a semicolon has been replaced with a comma
- First snippet:

```js
const computePass = encoder.beginComputePass();

// New lines
computePass.setPipeline(simulationPipeline),
computePass.setBindGroup(0, bindGroups[step % 2]);

computePass.end();
```

- Second snippet:

```js
const computePass = encoder.beginComputePass();

computePass.setPipeline(simulationPipeline),
computePass.setBindGroup(0, bindGroups[step % 2]);

// New lines
const workgroupCount = Math.ceil(GRID_SIZE / WORKGROUP_SIZE);
computePass.dispatchWorkgroups(workgroupCount, workgroupCount);

computePass.end();
``` 

- After the `computePass.setPipeline(simulationPipeline)` command, there should be a semicolon and not a comma
- Like this:

```js
computePass.setPipeline(simulationPipeline);
computePass.setBindGroup(0, bindGroups[step % 2]);
```

**Comment by beaufortfrancois** [comment]
Thank you @kassu11 for the feedback!

Re: "The code breaking error", I can't reproduce your issue. As you can see in https://glitch.com/edit/#!/your-first-webgpu-app?path=05-game-simulation.html%3A64%3A10, `GPUShaderStage.FRAGMENT` is not required for https://your-first-webgpu-app.glitch.me/05-game-simulation.html to work fine.

Re: "Second minor fix", I'll update the codelab and will let you know when it's updated.

**Comment by kassu11** [comment]
Thanks @beaufortfrancois for the response!

- I have compared my and your solutions and the only difference is inside the `cellShaderModule` variables shader code 
- My fragment shader code is written as `Chapter 6` instructed:

```wgsl
@fragment
fn fragmentMain(input: VertexOutput) -> @location(0) vec4f {
  let c = input.cell / grid;
  return vec4f(c, 1-c.x, 1);
}
```

- Your `fragment` code doesn't use the uniform `grid` variable
- You do the division calculation inside the `vertex` shader:

```wgsl
@vertex
fn vertexMain(@location(0) position: vec2f, @builtin(instance_index) instance: u32) -> VertexOutput {
  var output: VertexOutput;
  //...

  output.cell = cell / grid; // Math is done here
  return output;
}

@fragment
fn fragmentMain(input: VertexOutput) -> @location(0) vec4f {
  return vec4f(input.cell, 1.0 - input.cell.x, 1);
}
```
- Because I used the uniform `grid` variable inside the `fragment` shader I was getting the error
- Based on the `Chapter 6` code shown above and the `Chapter 7` code shown below, I believe I have done as the instructions say
- Chapter 7 code:

```wgsl
@vertex
fn vertexMain(@location(0) pos: vec2f,
              @builtin(instance_index) instance: u32) -> VertexOutput {
  let i = f32(instance);
  let cell = vec2f(i % grid.x, floor(i / grid.x));
  let state = f32(cellState[instance]); // New line!

  let cellOffset = cell / grid * 2;
  // New: Scale the position by the cell's active state.
  let gridPos = (pos*state+1) / grid - 1 + cellOffset;

  var output: VertexOutput;
  output.pos = vec4f(gridPos, 0, 1);
  output.cell = cell; // No math is done here
  return output;
}
```
- **Notice** that the cell is int vector and the color math is still needed to be done inside the `fragment` shader
  - Your code does the math in the `vertex` shader `output.cell = cell / grid;` and the code snippet does the math inside `fragment` shader
- It's possible that there is a text that says to remove the uniform `grid` math inside the fragment shader, but after a quick look, I couldn't find it
- I believe that the code snippets should show the math inside the `vertex` shader if it is supposed to be moved there at the end anyway

Thank you again for the quick response, and sorry if the instructions told to move the math and I'm just too blind to see it. If something was unclear here is my [old source code](https://pastebin.com/5ggZubAP) that had the issue.

**Comment by beaufortfrancois** [comment]
Oh I get it now! Thanks for the detailed answer @kassu11 

We'll update the codelab shortly to include the note below. 

> Note: You may need to make resources accessible to fragment shaders by adding `GPUShaderStage.FRAGMENT` for the uniform and first storage buffer if your fragment shader code uses the uniform `grid` variable as explained in the previous section.

I believe there is some confusion because the Section 6 is optional.

> [6. Extra credit: make it more colorful!](https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#5)
>
> At this point, you can **easily skip to the next section** since you've laid the groundwork for the rest of the codelab. But while the grid of squares all sharing the same color is serviceable, it's not exactly exciting, is it? Fortunately you can make things a bit brighter with a little more math and shader code!

**Comment by beaufortfrancois** [comment]
The codelab is now updated at https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7:~:text=GPUShaderStage.FRAGMENT

Thank you folks!
