### ISSUE TITLE
[your-first-webgpu-app]

### ISSUE THREAD

**Issue by kriyanshii** [googlecodelabs/feedback#1237]
The code lab on glitch isn't opening.

**Comment by beaufortfrancois** [comment]
https://glitch.com/edit/#!/your-first-webgpu-app works for me. Can you try again?

<img width="1840" alt="Screenshot 2023-06-21 at 16 21 20" src="https://github.com/googlecodelabs/feedback/assets/634478/cac22bca-e27b-428b-8fba-919a97a545b5">

**Comment by beaufortfrancois** [comment]
Feel free to re-open if you're still having the issue.
