### ISSUE TITLE
[cloud-run-wagtail]: no-acccess of storage.objects.get

### ISSUE THREAD

**Issue by metaswang** [googlecodelabs/feedback#1238]
To read the resource from gcloud storage, you can add a role with read access to the service account.
I encountered no-acccess ( storage.objects.get ) issue when load the page.

`gcloud projects add-iam-policy-binding $PROJECT_ID --member=serviceAccount:$SERVICE_ACCOUNT --role=roles/storage.objectAdmin` or objectViewer

**Comment by glasnt** [comment]
Thanks for the report! We'll make sure this is updated in the codelab.
