### ISSUE TITLE
[cloud-speech-text-python3]…

### ISSUE THREAD

**Issue by resul-ai** [googlecodelabs/feedback#1247]
`print_response(response)` should be ` print_result(response)`

**Comment by PicardParis** [comment]
Hi,
I believe this works as it should (`print_response` calls `print_result` in a loop).
Do you get an error message?

**Comment by PicardParis** [comment]
Hi
- I couldn't reproduce/guess a potential problem.
- I'm closing the issue for now. Please reopen it if you see an error.
