### ISSUE TITLE
[your-first-webgpu-app]

### ISSUE THREAD

**Issue by dynamite-bud** [googlecodelabs/feedback#1248]
In the `bindGroupLayout`:

The tutorial says on the **8th** page when first constructing the `bindGroupLayout`:

```ts
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [
    {
      binding: 0,
      visibility:
        GPUShaderStage.VERTEX |
        GPUShaderStage.COMPUTE,
      buffer: {}, // Grid uniform buffer
    },
    {
      binding: 1,
      visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
      buffer: { type: "read-only-storage" }, // Cell state input buffer
    },
    {
      binding: 2,
      visibility: GPUShaderStage.COMPUTE,
      buffer: { type: "storage" }, // Cell state output buffer
    },
  ],
});
```

The above code results in an error:
```console
Entry points stage (Shader Stage::Fragment) is not in the binding visibility in the layout (Shader Stage::(Vertex|Compute))
```
This is because the `uniformBuffer` bound on `0` is `GRID_SIZE*GRID_SIZE` is also used in the Fragment shader. So this should be updated to:

```ts
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [
    {
      binding: 0,
      visibility:
        GPUShaderStage.VERTEX |
        GPUShaderStage.COMPUTE |   //  👈🏼 Added a `|` operator
        GPUShaderStage.FRAGMENT,    //  👈🏼 Added a `FRAGMENT` flag
      buffer: {}, // Grid uniform buffer
    },
    {
      binding: 1,
      visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
      buffer: { type: "read-only-storage" }, // Cell state input buffer
    },
    {
      binding: 2,
      visibility: GPUShaderStage.COMPUTE,
      buffer: { type: "storage" }, // Cell state output buffer
    },
  ],
});
```

The paragraph below this code snippet also need to be modified:

"In each entry, you give the binding number for the resource, which (as you learned when you created the bind group) matches the @binding value in the shaders. You also provide the visibility, which are [GPUShaderStage](https://gpuweb.github.io/gpuweb/#typedefdef-gpushaderstageflags) flags that indicate which shader stages can use the resource. _**You want both the uniform and first storage buffer to be accessible in the vertex and compute shaders, but the second storage buffer only needs to be accessible in compute shaders. You can also make resources accessible to fragment shaders with these flags, but you have no need to do so here.**_"

The bold-italic content needs to be updated to include the use of `FRAGMENT` flag in the `uniformBuffer` binding.

**Comment by beaufortfrancois** [comment]
Thank you @dynamite-bud! 

This issue has been raised in https://github.com/googlecodelabs/feedback/issues/1235 and we're updating the codelab as we speak.
