### ISSUE TITLE
[cloud-bigquery-python]:

### ISSUE THREAD

**Issue by spencerkmarley** [googlecodelabs/feedback#1249]
You need to also grant the Service Usage Consumer role to the user, otherwise it returns a 403 error.

**Comment by glasnt** [comment]
I'm able to successfully query BigQuery using a service account with only the `roles/bigquery.user`. 

The account that you use to _create_ the service account may require the Service Usage Consumer role, but our codelabs presume you're an owner of the project you're using, so this permission is inherited.
