### ISSUE TITLE
[your-first-webgpu-app] Entry point's stage (ShaderStage::Fragment) is not in the binding visibility in the layout (ShaderStage::(Vertex|Compute))

### ISSUE THREAD

**Issue by billkie** [googlecodelabs/feedback#1253]
The code for `bindGroupLayout` is missing the visibility for fragment stage and gives the following error:

Entry point's stage (ShaderStage::Fragment) is not in the binding visibility in the layout (ShaderStage::(Vertex|Compute)).
 - While validating that the entry-point's declaration for @group(0) @binding(0) matches [BindGroupLayout "Cell Bind Group Layout"]
 - While validating the entry-point's compatibility for group 0 with [BindGroupLayout "Cell Bind Group Layout"]
 - While validating fragment stage ([ShaderModule "Cell shader"], entryPoint: fragmentMain).
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "Cell pipeline"]).

I fixed this by using the following code:

```
      const bindGroupLayout = device.createBindGroupLayout({
        label: "Cell Bind Group Layout",
        entries: [{
          binding: 0,
          visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE | GPUShaderStage.FRAGMENT,
          buffer: {} // Grid uniform buffer
        }, {
          binding: 1,
          visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
          buffer: { type: "read-only-storage"} // Cell state input buffer
        }, {
          binding: 2,
          visibility: GPUShaderStage.COMPUTE,
          buffer: { type: "storage"} // Cell state output buffer
        }]
      });
```

**Comment by beaufortfrancois** [comment]
Thank you @willbo! 

This issue has been raised in https://github.com/googlecodelabs/feedback/issues/1235 and we're updating the codelab as we speak.
