### ISSUE TITLE
[your-first-webgpu-app]

### ISSUE THREAD

**Issue by ruigil** [googlecodelabs/feedback#1260]
There is one mistake on step 8 of this codelab.

It is the omission of the fragment shader visibility on the definition of the binding 0 in the binfGroupLayout
Without it, the shader doesn't compile because the fragment shader needs the uniform grid size.

```javascript
// Create the bind group layout and pipeline layout.
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [{
    binding: 0,
   // this binding needs to be visible for the fragment shader !
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT | GPUShaderStage.COMPUTE,
    buffer: {} // Grid uniform buffer
  }, {
    binding: 1,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
    buffer: { type: "read-only-storage"} // Cell state input buffer
  }, {
    binding: 2,
    visibility: GPUShaderStage.COMPUTE,
    buffer: { type: "storage"} // Cell state output buffer
  }]
});
```

After that change everything works fine.
Thank you for this codelab.

**Comment by beaufortfrancois** [comment]
See https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7:~:text=Note%3A%20You%20may%20need%20to%20make%20resources%20accessible%20to%20fragment%20shaders%20by%20adding%20GPUShaderStage.FRAGMENT%20for%20the%20uniform%20and%20first%20storage%20buffer%20if%20your%20fragment%20shader%20code%20uses%20the%20uniform%20grid%20variable%20as%20explained%20in%20the%20previous%20section.

![image](https://github.com/googlecodelabs/feedback/assets/634478/94ba8333-459e-48c8-9769-170a764fef48)
