### ISSUE TITLE
[your-first-webgpu-app] blank page

### ISSUE THREAD

**Issue by SimonSiefke** [googlecodelabs/feedback#1261]
When visiting https://your-first-webgpu-app.glitch.me/02-drawing-a-square.html and WebGPU is not supported, a blank page is shown:

![webgpu-blank-page](https://github.com/googlecodelabs/feedback/assets/23744935/a6487c4e-4e55-46cf-97f0-bf094586b107)

## Expected behaviour
When WebGPU is not supported, a friendly error message is displayed on screen that WebGPU is not supported

## Actual behaviour
When WebGPU is not supported, a blank page is shown

**Comment by beaufortfrancois** [comment]
In Chrome, Edge, and Firefox browsers, you can see an error message in DevTools.

<img width="1267" alt="image" src="https://github.com/googlecodelabs/feedback/assets/634478/7bb7f536-7486-4229-a201-21a4ffd8c37c">

In WebKit, I've just filed a bug https://bugs.webkit.org/show_bug.cgi?id=259439

**Comment by SimonSiefke** [comment]
I was thinking more of a dialog or similar. I quite liked how [WebGPU fundamentals](https://webgpufundamentals.org/webgpu/lessons/webgpu-textures.html) does it 

![webgpu-fundamentals](https://github.com/googlecodelabs/feedback/assets/23744935/7ca0485b-713d-4a84-8cc5-24974c093594)

I think this makes it more obvious at first glance what is going wrong.

**Comment by beaufortfrancois** [comment]
https://your-first-webgpu-app.glitch.me/02-drawing-a-square.html is a companion to the codelab. You're right that in the context of a real web app, we should show a warning dialog explaining WebGPU is not supported. In that specific context, we added a simple note:

![image](https://github.com/googlecodelabs/feedback/assets/634478/126f1a1a-969c-4e19-bb5f-d9db6ec32184)
