### ISSUE TITLE
[cloud-run-django]:

### ISSUE THREAD

**Issue by celestialmk** [googlecodelabs/feedback#1265]
command provided for cloud sql proxy is different from that in the documentation, unless maybe if someone renames the executable file

**Comment by glasnt** [comment]
Ah! Looks like the executable changed in v1 vs v2 (https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md#listen-on-tcp-socket)! I'll be sure to update the codelab accordingly. Thanks for reporting!
