### ISSUE TITLE
[cloud-run-django]: pack failed: step exited with non-zero status: 1

### ISSUE THREAD

**Issue by chrisgathuthi** [googlecodelabs/feedback#1268]
I am following along step-by-step tutorial on how to deploy a django application on google cloud run but I keep getting the following error 
`ERROR: build step 1 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zero status: 1` [A similar issue has been raised on StackOverflow](https://stackoverflow.com/questions/74695841/cloud-build-error-failed-to-build-executing-lifecycle-this-may-be-the-result#:~:text=build%3A%20executing%20lifecycle.-,This%20may%20be%20the%20result%20of%20using%20an%20untrusted,failed%20with%20status%20code%3A%2051&text=The%20file%20migration.,they%20were%20in%20the%20tutorial.)

**Comment by chrisgathuthi** [comment]
I got the error when I executed the following command `gcloud builds submit --pack image=gcr.io/${PROJECT_ID}/myimage`

**Comment by glasnt** [comment]
Hi @chrisgathuthi; can you please provide the detail of the error message? There is no information currently available to help me debug your issue.

**Comment by chrisgathuthi** [comment]
The following is a screenshot of the error from cloud shell terminal
```bash
Step #1: Timer: Saving gcr.io//foundationimage... started at 2023-08-15T10:52:51Z
Step #1: *** Images (3562ca06093a):
Step #1:       gcr.io//foundationimage - loading image "gcr.io//foundationimage". first error: embedded daemon response: invalid reference format
Step #1: Timer: Saving gcr.io//foundationimage... ran for 20.304428978s and ended at 2023-08-15T10:53:12ZStep #1: Timer: Exporter ran for 27.203931824s and ended at 2023-08-15T10:53:12Z
Step #1: ERROR: failed to export: failed to write image to the following tags: [gcr.io//foundationimage: loading image "gcr.io//foundationimage". first error: embedded daemon response: invalid reference format]
Step #1: ERROR: failed to build: executing lifecycle: failed with status code: 62
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zero status: 1--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

BUILD FAILURE: Build step failure: build step 1 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zer
```

**Comment by glasnt** [comment]
From that error, you can see the image `gcr.io//foundationimage`. You're missing the declaration of the `$PROJECT_ID` variable, so the image isn't being found. You set this value in Step 5, but getting this error later in Step 7. 

It also appears you've renamed the image to `foundationimage` not `myimage`, so make sure you continue to make that change throughout the rest of the codelab.
