### ISSUE TITLE
[your-first-webgpu-app]

### ISSUE THREAD

**Issue by JussaMouse** [googlecodelabs/feedback#1271]
In part 5 "Draw a Grid", in the section "Manipulate Geometry in the Shader", in the sentence "This moves every vertex up and to the **left** by one (which, remember, is half of the clip space) before dividing it by the grid size", there is a mistake. It should say "up and to the **right**".

**Comment by beaufortfrancois** [comment]
Thank you @JussaMouse again! We'll be fixing the typo soon.
