### ISSUE TITLE
[your-first-webgpu-app]

### ISSUE THREAD

**Issue by JussaMouse** [googlecodelabs/feedback#1272]
In part 7 "Manage Cell State", in the section "Read the Storage Buffer in the Shader", in the sentence "The state value must be cast **_the state_** to a f32 in order to satisfy WGSL's type safety requirements:", there is a mistake. The extra "the state" in the middle of the sentence should be removed, so that it reads:  "The state value must be cast to a f32 in order to satisfy WGSL's type safety requirements:"

**Comment by beaufortfrancois** [comment]
Thank you @JussaMouse! We'll be fixing the typo soon.
