### ISSUE TITLE
[cloud-run-django]:10 - Developing your application

### ISSUE THREAD

**Issue by tonycurra** [googlecodelabs/feedback#1275]
Hi, 

I'm having trouble accessing the app from my local machine. There are some errors in this page. Here's one thing that doesn't work for me:

Connect to your production database
You can connect to your Cloud SQL instances by using the [Cloud SQL Auth Proxy](https://cloud.google.com/sql/docs/postgres/quickstart-proxy-test#install-proxy). This application creates a connection from your local machine to the database.

Once you have installed the Cloud SQL Auth Proxy, follow these steps:

# Create a virtualenv
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt

# Copy the application settings to your local machine
gcloud secrets versions access latest --secret application_settings > temp_settings

# Run the Cloud SQL Auth Proxy
./cloud_sql_proxy --instances=${PROJECT_ID}:${REGION}:myinstance=tcp:5432

I always get stuck at this point. Cant really connect and develop. I've been trying from yesterday.

Any tips? 
Thank you so much for this codelab!

**Comment by glasnt** [comment]
You need to ensure you change the `temp_settings` to point Django to your local database, not the production database. Hope this helps!
