### ISSUE TITLE
[cloud-run-django]:

### ISSUE THREAD

**Issue by nlafevers** [googlecodelabs/feedback#1289]
Django on Cloud Run  > 6. [Configure your application](https://codelabs.developers.google.com/codelabs/cloud-run-django#5) > Configure settings

The wording here is very confusing.  Instead of:
"Find the generated settings.py file, and rename it to basesettings.py:
`commands`"

Say something like:
"Backup the generated settings.py file by renaming it to basesettings.py:
`commands`"

Which gives some context to the next instruction, which currently reads:
"Next, use the Cloud Shell web editor to open the file and replace the entire file's contents the(sic) the following:
`commands`"

When you say "the file" here it implies the basesettings file, and you are instructing the user to replace the entire contents of the file with the next two commands.

Instead it should say:
"Next, create a new settings.py file and use the Cloud Shell web editor to open the file:
`commands`
Paste the following code in the new settings.py file in the Cloud Shell web editor:
`code`"

**Comment by glasnt** [comment]
Thanks for the feedback, @nlafevers! I'll address these suggestions in the next update of this codelab.
