### ISSUE TITLE
[cloud-run-django]: Issue running migration

### ISSUE THREAD

**Issue by nlafevers** [googlecodelabs/feedback#1290]
I've gotten to the point of running the migrate and createsuperuser jobs twice now, and just get errors both times.  First time the error was no Django module.  That run I did over multiple sittings and changed the names of some things, so assumed it was mistake.  Second time, I ran the tutorial straight through, just copying and pasting, still got an error.  Didn't specify this time, the log just said error.

**Comment by glasnt** [comment]
Hi @nlafevers. Are you able to provide the error message you received? That will help me identify the issue.
