### ISSUE TITLE
[your-first-webgpu-app] translation code error

### ISSUE THREAD

**Issue by UTSUHO** [googlecodelabs/feedback#1295]
For the Chinese translation of the  'your-first-webgpu-app' lab, in the 8th chapter 'compute pass' part, the 'encoder' has been replaced by 'computeEnocder' and won't work properly. The 'encoder' works correctly.

- which chapter: 8th chapter
- which part: Compute Pass
- affected source: Chinese translation

Here is the screenshot.
![image](https://github.com/googlecodelabs/feedback/assets/9929655/c060900f-286f-4000-9ce4-592c000ac9ac)
![image](https://github.com/googlecodelabs/feedback/assets/9929655/71190068-4d00-4395-bee9-51a0d2fc9525)

**Comment by beaufortfrancois** [comment]
Thank you @UTSUHO for raising this issue. I'll ping the translation team folks as it not only impacts the chinese translated codelab but all translated codelabs.

**Comment by beaufortfrancois** [comment]
It is now fixed.
