### ISSUE TITLE
[your-first-webgpu-app] the bindGroupLayout entry visibility seems wrong.

### ISSUE THREAD

**Issue by ChenShihao** [googlecodelabs/feedback#1297]
https://codelabs.developers.google.com/your-first-webgpu-app#7

Step 8 - Run the simulation

```
// Create the bind group layout and pipeline layout.
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [{
    binding: 0,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
    buffer: {} // Grid uniform buffer
  },
  ...
});
```

The visibility of first entry which binding is 0 seems wrong.
It shows warnings in Chrome Console.
```
Entry point's stage (ShaderStage::Fragment) is not in the binding visibility in the layout (ShaderStage::(Vertex|Compute)).
 - While validating that the entry-point's declaration for @group(0) @binding(0) matches [BindGroupLayout "Cell Bind Group Layout"]
 - While validating the entry-point's compatibility for group 0 with [BindGroupLayout "Cell Bind Group Layout"]
 - While validating fragment stage ([ShaderModule "Cell Shader"], entryPoint: fragmentMain).
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "Cell pipeline"]).
```

And then I try to add `GPUShaderStage.FRAGMENT` for it. It works.

```
 const bindGroupLayout = device.createBindGroupLayout({
    label: "Cell Bind Group Layout",
    entries: [
      {
        binding: 0,
        visibility:
          GPUShaderStage.VERTEX |
          GPUShaderStage.COMPUTE |
          GPUShaderStage.FRAGMENT,
        buffer: {},
      },
    ...
```

Does it right?

**Comment by beaufortfrancois** [comment]
You're right. See the note below in the english version: https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7:~:text=by%20adding%20GPUShaderStage.-,FRAGMENT,-for%20the%20uniform

> Note: You may need to make resources accessible to fragment shaders by adding GPUShaderStage.FRAGMENT for the uniform and first storage buffer if your fragment shader code uses the uniform grid variable as explained in the previous section.

It will be in all translated versions soon.
