### ISSUE TITLE
[your-first-webgpu-app] encoder.beginRenderPass mistake

### ISSUE THREAD

**Issue by TaoSc** [googlecodelabs/feedback#1300]
In section [3. Initialize WebGPU](https://codelabs.developers.google.com/your-first-webgpu-app#2)

Under **Pick a color!**

It should be **encoder.beginRenderPass()** instead of **device.beginRenderPass()**

**Comment by beaufortfrancois** [comment]
Thank you @TaoSc. I'll be updating the codelab in the coming days!

**Comment by beaufortfrancois** [comment]
And we're good now!
