### ISSUE TITLE
[your-first-webgpu-app]

### ISSUE THREAD

**Issue by mavibirdesmi** [googlecodelabs/feedback#1305]
In the codelab for [webgpu](https://codelabs.developers.google.com/your-first-webgpu-app#3), the vertex module code is invalid and it will throw error when you try to use it. The reason behind this error is that the vec4f expects a float literal (I guess?) instead of a int literal and can't convert between them.

I just started learning webgpu, so there can be a different reason why the code fails, but it definitely doesn't work on its own right now.

![image](https://github.com/googlecodelabs/feedback/assets/57793244/2169509c-3e32-4f9a-8812-3f2cc75ae733)

```wgsl

// wrong
@vertex
fn vertexMain(@location(0) pos: vec2f) ->
  @builtin(position) vec4f {
  return vec4f(pos.x, pos.y, 0, 1);
}

// correct
@vertex
fn vertexMain(@location(0) pos: vec2f) ->
  @builtin(position) vec4f {
  return vec4f(pos.x, pos.y, 0.0, 1.0);
}
```

**Comment by beaufortfrancois** [comment]
This seems to be an issue with Naga, the Rust shader translation library used in Firefox. I can't reproduce this issue with Tint library, used in Chrome browser. 
FYI I've filed https://github.com/gfx-rs/wgpu/issues/4727

**Comment by mavibirdesmi** [comment]
Thanks @beaufortfrancois !
