### ISSUE TITLE
[cloud-networking-101]:  The --health-check flag is deprecated

### ISSUE THREAD

**Issue by Juxtaposedwords** [googlecodelabs/feedback#131]
https://codelabs.developers.google.com/codelabs/cloud-networking-101/index.html?index=..%2F..%2Findex#13

The line 
gcloud compute target-pools create apaches --region us-central1 --health-check basic-check

should now be:
 gcloud compute target-pools create apaches --region us-central1 --http-health-check=basic-check

Reasoning "
 'The --health-check flag is deprecated'

**Comment by thesmiler** [comment]
Hi, thanks for your feedback. In the meantime we completely rebuilt this lab. This section is not part of the lab anymore!
