### ISSUE TITLE
[cloud-functions-csharp]:

### ISSUE THREAD

**Issue by Funka** [googlecodelabs/feedback#1312]
The very first sentence in step 1 says to go to the URL console.cloud.google.com.  When I do, my view looks completely different than what is shown in this tutorial. (Yes, I am signed in.) Therefore, I cannot even start this tutorial.

**Comment by meteatamel** [comment]
Yes, the screenshots usually go stale and the console changes quite often. What issue are you running into? You basically need to either select a project or create one.

**Comment by meteatamel** [comment]
Please reopen with more details.
