### ISSUE TITLE
[your-first-webgpu-app]

### ISSUE THREAD

**Issue by leomchan** [googlecodelabs/feedback#1313]
In the [Run the simulation step](https://codelabs.developers.google.com/your-first-webgpu-app#7), there is an error in the section *Use Bind Group and Pipeline Layouts*

Binding 0 of the bind group layout is missing visibility for `GPUShaderStage.FRAGMENT`, and buffer should be `uniform`.

```javascript
// Create the bind group layout and pipeline layout.
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [{
    binding: 0,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT | GPUShaderStage.COMPUTE,
    buffer: { type: "uniform" } // Grid uniform buffer
  }, {
    binding: 1,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
    buffer: { type: "read-only-storage"} // Cell state input buffer
  }, {
    binding: 2,
    visibility: GPUShaderStage.COMPUTE,
    buffer: { type: "storage"} // Cell state output buffer
  }]
});
```

**Comment by beaufortfrancois** [comment]
There's a note for this in https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7:
<img width="851" alt="image" src="https://github.com/googlecodelabs/feedback/assets/634478/7c9b8db5-b10d-42d9-a7a5-9439139faf14">
