### ISSUE TITLE
[your-first-webgpu-app] two small errors?

### ISSUE THREAD

**Issue by bartgdeboer** [googlecodelabs/feedback#1314]
Dear webgpu codelab,
I learned a lot from your excellent codelab. However, I ran into two small issues:

Under "// Create the bind group layout and pipeline layout." I had to add the visibility flag for the fragment shader
```
    binding: 0,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,

```
into
```
    binding: 0,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT | GPUShaderStage.COMPUTE,

```
and under the random initialization of the Game-of-Life buffer I had to change the index from 0 to 1, i.e.
`  device.queue.writeBuffer(cellStateStorage[0], 0, cellStateArray);
`
into
`  device.queue.writeBuffer(cellStateStorage[1], 0, cellStateArray);
`
Figuring out how to repair the errors was a very useful exercise though.
Thanks for the codelab,
Bart.

**Comment by beaufortfrancois** [comment]
For the first issue, you're right. See the note below in the english version: https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7:~:text=by%20adding%20GPUShaderStage.-,FRAGMENT,-for%20the%20uniform

> Note: You may need to make resources accessible to fragment shaders by adding GPUShaderStage.FRAGMENT for the uniform and first storage buffer if your fragment shader code uses the uniform grid variable as explained in the previous section.

It will be in all translated versions soon.

For the second issue, I'm surprised as https://glitch.com/edit/#!/your-first-webgpu-app?path=05-game-simulation.html%3A229%3A3 shows it uses index 0 in `device.queue.writeBuffer(cellStateStorage[0], 0, cellStateArray);`

**Comment by beaufortfrancois** [comment]
> It will be in all translated versions soon.

And it's done now.

Feel free to re-open for the second issue if I misunderstood it.
