### ISSUE TITLE
[cloud-networking-101]: The --zone flag is deprecated.

### ISSUE THREAD

**Issue by Juxtaposedwords** [googlecodelabs/feedback#132]
The --zone flag is deprecated,  use --instances-zones is recommended.

Page in which i found this:
https://codelabs.developers.google.com/codelabs/cloud-networking-101/index.html?index=..%2F..%2Findex#13

ye olde gnu sed one liner:
"s/\-\-zone\ /\-\-instances\-zones\=/g"

**Comment by thesmiler** [comment]
We've rebuilt this lab, I think this part is completely gone! Thanks for filing the bug!
