### ISSUE TITLE
[cloud-run-django]: How to develop application further

### ISSUE THREAD

**Issue by gitfun-ash** [googlecodelabs/feedback#1320]
I have been able to deploy the default django project to gcloud

But i don't see any details about how to add a new app to the project which is generally done by using the following command 
'python manage.py startapp <appname>
also don't know how to run python manage.py makemigrations from the cloud shell.  
Must we run this command in the local development environment

**Comment by glasnt** [comment]
Hi @gitfun-ash 

In [Step 10 "Developing your application"](https://codelabs.developers.google.com/codelabs/cloud-run-django#9), it shows you how you'd setup a typical python development environment (using virtualenv). That step also shows you how to connect your production database to a development environment. This should set you up for success when further developing your application.
