### ISSUE TITLE
[cloud-run-django]:  Inconsistent instructions for building application image

### ISSUE THREAD

**Issue by joshwizzy** [googlecodelabs/feedback#1323]
In **Step 10** the command for updating the application image uses container registry instead of artifact registry
`gcloud builds submit --pack image=gcr.io/${PROJECT_ID}/myimage`

Previously in **Step 7** the command to build the image is
`gcloud builds submit --pack image=${ARTIFACT_REGISTRY}/myimage`

In **Step 10** the command to update the service is given as
```
gcloud run services update django-cloudrun \
  --platform managed \
  --region $REGION \
  --image ${ARTIFACT_REGISTRY}/myimage
  ```
  
  Since the codelab uses artifact registry the command should be
`gcloud builds submit --pack image=${ARTIFACT_REGISTRY}/myimage`

**Comment by glasnt** [comment]
Good catch! I missed a Container Registry URL when updating this codelab to use Artifact Registry. I'll get this updated!

**Comment by glasnt** [comment]
This should be resolved now!
