### ISSUE TITLE
[your-first-webgpu-app]

### ISSUE THREAD

**Issue by renato-mauro** [googlecodelabs/feedback#1329]
In the following code snippet, in the first entry, I had to include GPUShaderStage.FRAGMENT, because it corresponds to the  GRID uniform variable, also used by fragment shader. This code is in the section 8. BTW, really nice tutorial <3.

```javascript
// Create the bind group layout and pipeline layout.
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [{
    binding: 0,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT | GPUShaderStage.COMPUTE,
    buffer: {} // Grid uniform buffer
  }, {
    binding: 1,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
    buffer: { type: "read-only-storage"} // Cell state input buffer
  }, {
    binding: 2,
    visibility: GPUShaderStage.COMPUTE,
    buffer: { type: "storage"} // Cell state output buffer
  }]
});
```

**Comment by beaufortfrancois** [comment]
There's a note for this in https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7:
<img width="851" alt="image" src="https://github.com/googlecodelabs/feedback/assets/634478/7c9b8db5-b10d-42d9-a7a5-9439139faf14">
