### ISSUE TITLE
[your-first-webgpu-app] bind group 0 not visible to fragment shader

### ISSUE THREAD

**Issue by Reldeam** [googlecodelabs/feedback#1336]
Part 8. Run the simulation

**bindGroupLayout** sets the visibility of **binding 0** to: `GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE`
I think it needs to be visible to the fragment shader as well: `GPUShaderStage.VERTEX | GPUShaderStage.FRAGMENT | GPUShaderStage.COMPUTE`

**Comment by beaufortfrancois** [comment]
There's a note for this in https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7:
<img width="851" alt="image" src="https://github.com/googlecodelabs/feedback/assets/634478/7c9b8db5-b10d-42d9-a7a5-9439139faf14">
