### ISSUE TITLE
[cloud-run-wagtail]: "Build your application image" fails in step 7

### ISSUE THREAD

**Issue by JethroCooper** [googlecodelabs/feedback#1348]
When I reach the following step in the tutorial:

**Build your application image**

With your Procfile updates in place, build the image:
`
$ gcloud builds submit --pack image=${ARTIFACT_REGISTRY}/myimage`

The step fails with the following error message:

`ERROR: (gcloud.builds.submit) Invalid value for [--pack]: Image value must be in the *gcr.io* or *pkg.dev* namespace`

Investigating, the environment variable is empty and is not set anywhere in the tutorial:

`$ echo ${ARTIFACT_REGISTRY}
`
`
`

When I manually set the variable to my project, the step completes sucessfully:

```
$ gcloud builds submit --pack image=gcr.io/my-project/myimage
Creating temporary tarball archive of 26 file(s) totalling 24.9 KiB before compression.
...
```

How am I supposed to correctly set ARTIFACT_REGISTRY?

**Comment by JethroCooper** [comment]
To further this point, in step 8 you're supposed to run the following command:

```
gcloud run deploy wagtail-cloudrun \
  --platform managed \
  --region $REGION \
  --image gcr.io/${PROJECT_ID}/myimage \
  --set-cloudsql-instances ${PROJECT_ID}:${REGION}:myinstance \
  --set-secrets APPLICATION_SETTINGS=application_settings:latest \
  --service-account $SERVICE_ACCOUNT \
  --allow-unauthenticated
```

This leads me to strongly believe that there is a step missing earlier in the tutorial:

`ARTIFACT_REGISTRY=gcr.io/${PROJECT_ID}`

or all mentions of ${ARTIFACT_REGISTRY} should be replaced with gcr.io/${PROJECT_ID}

**Comment by glasnt** [comment]
My apologies, it looks like the Wagtail tutorial is missing the section from part 5. 

> To store the built container image, create a container registry in your chosen region:
> `gcloud artifacts repositories create containers --repository-format docker --location $REGION`
> You will reference this registry by name in future sections of this codelab:
> `ARTIFACT_REGISTRY=${REGION}-docker.pkg.dev/${PROJECT_ID}/containers`

I'll make sure this gets addressed
