### ISSUE TITLE
[your-first-webgpu-app] Missing flag at stage 8

### ISSUE THREAD

**Issue by sp-droid** [googlecodelabs/feedback#1359]
Hello!
As of February 2024, the codelabs "Your first webgpu app" has a mistake in the last part "Part 8 Run the Simulation":

The flag **GPUShaderStage.FRAGMENT** that lets the fragment shader access the grid value stored in the 0 binded-uniform buffer is missing in the provided code at stage 8. I've written MISSING! where it should go:
```
// Create the bind group layout and pipeline layout.
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [{
    binding: 0,
    visibility: GPUShaderStage.VERTEX | MISSING! | GPUShaderStage.COMPUTE,
    buffer: {} // Grid uniform buffer
  }, {
    binding: 1,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
    buffer: { type: "read-only-storage"} // Cell state input buffer
  }, {
    binding: 2,
    visibility: GPUShaderStage.COMPUTE,
    buffer: { type: "storage"} // Cell state output buffer
  }]
});
```

This is the fragment shader at this stage of the tutorial:
```
@fragment
fn fragmentMain (input: VertexOutput) -> @location(0) vec4f {
    let c = input.cell / grid;
    return vec4f(c, 1-c.x, 1);
}
```
It uses the grid value as you can see. The code provided at the very end doesn't use grid but I think it's a mistake. This makes it so if you follow the tutorial sequentially at one point you get a black screen and multiple errors. The errors however are very detailed which pointed me to the solution even as a complete novice.

Otherwise, extremely nice tutorial. I have never in my life seen anything like this and I'm not exaggerating. Props to Brandon Jones & François Beaufort!

**Comment by beaufortfrancois** [comment]
There's a note for this in https://codelabs.developers.google.com/your-first-webgpu-app#7:
<img width="851" alt="image" src="https://github.com/googlecodelabs/feedback/assets/634478/7c9b8db5-b10d-42d9-a7a5-9439139faf14">
