### ISSUE TITLE
[your-first-webgpu-app] Mistake in Bind Group Layout

### ISSUE THREAD

**Issue by stevenr4** [googlecodelabs/feedback#1365]
In Step 1 for the section "Use Bind Group and Pipeline Layouts", this code example exists:
```js
// Create the bind group layout and pipeline layout.
const bindGroupLayout = device.createBindGroupLayout({
  label: "Cell Bind Group Layout",
  entries: [{
    binding: 0,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
    buffer: {} // Grid uniform buffer
  }, {
    binding: 1,
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
    buffer: { type: "read-only-storage"} // Cell state input buffer
  }, {
    binding: 2,
    visibility: GPUShaderStage.COMPUTE,
    buffer: { type: "storage"} // Cell state output buffer
  }]
});
```

I think this bug is in binding 0 on this line: `visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,`. When following the tutorial, the FRAGMENT stage also reads the grid value in order to determine the color.

This is my first introduction to GPU programming and shaders, and it took me a while to figure out what was wrong here. I'm not 100% sure if I messed something up elsewhere or if there is a better fix for this, but I was able to fix this issue by adding the fragment flag to this line, changing this line to `visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE | GPUShaderStage.FRAGMENT,`

**Comment by beaufortfrancois** [comment]
There's a note for this in https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7:
<img width="851" alt="image" src="https://github.com/googlecodelabs/feedback/assets/634478/7c9b8db5-b10d-42d9-a7a5-9439139faf14">

**Comment by stevenr4** [comment]
> There's a note for this in https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7: <img alt="image" width="851" src="https://private-user-images.githubusercontent.com/634478/288355038-7c9b8db5-b10d-42d9-a7a5-9439139faf14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMzE4NTUsIm5iZiI6MTcwOTIzMTU1NSwicGF0aCI6Ii82MzQ0NzgvMjg4MzU1MDM4LTdjOWI4ZGI1LWIxMGQtNDJkOS1hN2E1LTk0MzkxMzlmYWYxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQxODMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWFiOWNkYWIwY2U5NmJlNGU2YzE2NmFjNzJmMWMzNmM1NGY1MTE1YTU2NGU3OGIyN2M3ZGU0ODcyZTM2ODkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aC_ifPd7JYMnbg6Sor4SJk4k7lWnPNVk4ye1CC3_fdI">

Thank you for clearing this up! Yes, I completely missed this.

If there is reason to have the code not match the examples or the previous steps, I would love to know why that is. Like I mentioned previously, I'm new to shaders, and missing the note you mentioned resulted in an hour of confusion. I am worried that other people similar to me might run into the same issue.

Is there a reason for the fragment visibility to be mentioned in a note instead of included in the code?


If it is necessary to leave the visibility as it is, then could I suggest a compromise like this?
```js
     // Add GPUShaderStage.FRAGMENT here if you are using the `grid` uniform in the fragment shader
    visibility: GPUShaderStage.VERTEX | GPUShaderStage.COMPUTE,
```

**Comment by beaufortfrancois** [comment]
The "Extra credit: make it more colorful!" section is optional. See https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#5

We didn't want to force developers to add colors.

> If it is necessary to leave the visibility as it is, then could I suggest a compromise like this?

👍 I'll update the codelab with your suggestion.

**Comment by beaufortfrancois** [comment]
I've updated the codelab. See https://codelabs.developers.google.com/your-first-webgpu-app?hl=en#7
