### ISSUE TITLE
[cloud-run-django]: Execute Cloud Run Job

### ISSUE THREAD

**Issue by esotericelf** [googlecodelabs/feedback#1369]
gcloud run jobs execute migrate --region $REGION --wait
X  Creating execution... Task migrate-vnttt-task0 failed with message: The container exited with an error.                                                                         
  OK Provisioning resources...                                                                                                                                                     
  OK Starting execution...                                                                                                                                                         
  X  Running execution... 0 / 1 complete                                                                                                                                           
Executing job failed                                                                                                                                                               
ERROR: (gcloud.run.jobs.execute) The execution failed.
View details about this execution by running:
gcloud run jobs executions describe migrate-vnttt

i looked at the log and couldn't quite figure out what to do. Please kindly advise

**Comment by glasnt** [comment]
I'm unable to help unless you take a look at the Cloud Logs for the execution to find the issue. Any issue should look like either a Python traceback (if it's an issue with the code), or a Google API error (for permissions issues)
