### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by LaurieTrichet** [googlecodelabs/feedback#137]
Hi,

I have followed the codelab (https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..%2Findex#0) steps, but when I call `mvn gcloud:deploy` I got an error:
[INFO] ERROR: (gcloud.preview.app.deploy) INVALID_ARGUMENT: Deployments to App Engine Flexible require `env: flex` in app.yaml.  The `vm:true` setting has been deprecated. To learn m
ore, please visit https://cloud.google.com/appengine/docs/flexible/python/upgrading.
[ERROR] Error: gcloud app command with exit code : 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:04 min
[INFO] Finished at: 2017-01-19T08:44:51+11:00
[INFO] Final Memory: 24M/58M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.106.v20160420:deploy (default-cli) on project gs-spring-boot: Error: gcloud app command exit code is: 1 
-> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException 

What went wrong, thank you by advance.

Laurie

**Comment by saturnism** [comment]
The lab has been updated w/ the new java11 runtime (beta) and JAR deployment, and a new plugin.
