### ISSUE TITLE
[cloud-run-hello-python3] Update Flask version

### ISSUE THREAD

**Issue by nxorable** [googlecodelabs/feedback#1383]
Nice tutorial - be sure to update requirements.txt to avoid an error. E.g. `Werkzeug==2.2.2` in your requirements.txt and it should work.

**Comment by PicardParis** [comment]
Thank you very much for your feedback. Will update the notebook asap.

**Comment by PicardParis** [comment]
✅ Updated the codelab: https://codelabs.devsite.corp.google.com/codelabs/cloud-run-hello-python3
🔧 Python 3.12 runtime
🔧 `Flask==3.0.2` (which fixed the Werkzeug dependency)
