### ISSUE TITLE
[bookshelf-duetai-bigquery] 

### ISSUE THREAD

**Issue by retr0ripper** [googlecodelabs/feedback#1384]
Step 4 now requires the use of "aiplatform.googleapis.com" to enable cloud functions, as "vertexai.googleapis.com" is no longer valid.

![Screenshot 2024-03-27 202309](https://github.com/googlecodelabs/feedback/assets/26818106/896fd8d2-e171-4d97-a914-dcbc5d0ea478)

**Comment by PicardParis** [comment]
Thank you for the feedback. The codelab has been updated.
