### ISSUE TITLE
[bookshelf-duetai-bigquery] typo in the last line of step 4

### ISSUE THREAD

**Issue by MrCsabaToth** [googlecodelabs/feedback#1394]
URL: https://codelabs.developers.google.com/bookshelf-duetai-bigquery#3
Step 4 ends with four API enabling instructions. The 4th has a typo: an extra i: `aiplatformi` instead of `aiplatform`

**Comment by PicardParis** [comment]
Thank you for the feedback. The codelab has been updated.
