### ISSUE TITLE
[how-to-configure-cloud-run-service-direct-vpc-egress]: typo

### ISSUE THREAD

**Issue by david-codento** [googlecodelabs/feedback#1398]
In https://codelabs.developers.google.com/codelabs/how-to-configure-cloud-run-service-direct-vpc-egress#0 , the first sentence of section 1. Introduction: Virtual Private Cloud is abbreviated as VCP (should be VPC). Subsequent occurrences are correctly written VPC.

**Comment by PicardParis** [comment]
Thanks for the feedback! The codelab has been updated.
