### ISSUE TITLE
[cloud-spring-spanner]:alexismp

### ISSUE THREAD

**Issue by GopalArvind** [googlecodelabs/feedback#1401]
curl https://start.spring.io/starter.tgz \
>   -d packaging=jar \
>   -d dependencies=cloud-gcp,web,lombok \
>   -d baseDir=spanner-example \
>   -d type=maven-project \
>   -d bootVersion=3.0.5

results in an error

{"timestamp":"2024-05-09T13:50:03.949+00:00","status":400,"error":"Bad Request","message":"Invalid Spring Boot version '3.0.5', Spring Boot compatibility range is >=3.1.0","path":"/start
er.tgz"}

**Comment by alexismp** [comment]
SpringBoot version has been updated to version 3.2.6
Thanks for the report.
