### ISSUE TITLE
[genai-chat-java-palm-langchain4j] Deprecated information

### ISSUE THREAD

**Issue by hwangkyle** [googlecodelabs/feedback#1413]
An example of deprecation is in the RAG section:
```
ConversationalRetrievalChain rag = ConversationalRetrievalChain.builder()
    .chatLanguageModel(model)

    // .retriever and .promptTemplate are deprecated. .retrievalAugmentor is used instead.
    .retriever(retriever)
    .promptTemplate(PromptTemplate.from("""
        Answer to the following query the best as you can: {{question}}
        Base your answer on the information provided below:
        {{information}}
        """
    ))
    .build();
```
Please update.

**Comment by glaforge** [comment]
I've stopped maintaining the PaLM / Java codelabs, and I'm now focusing on the Gemini codelab.
You can find a similar RAG example here with Gemini, which is not using LangChain4j's deprecated chains:
https://github.com/glaforge/gemini-workshop-for-java-developers/blob/main/app/src/main/java/gemini/workshop/RAG.java
