### ISSUE TITLE
[your-first-webgpu-app] Minor code comment mistake

### ISSUE THREAD

**Issue by beefchimi** [googlecodelabs/feedback#1420]
- **On the following page:** https://codelabs.developers.google.com/your-first-webgpu-app#4
- **At this section:** `#index.html_25`
- **On the following line:** `let cellOffset = cell / grid * 2; // Updated`

It is in fact the line PRIOR that has updated, and therefor should have the `// Updated` comment:
`let cell = vec2f(i, i);`

**Comment by beaufortfrancois** [comment]
Thanks for raising this issue @beefchimi!

I'm going to update the codelab and will let you know when the fix is deployed.

**Comment by beaufortfrancois** [comment]
And we're good now!
