### ISSUE TITLE
webgpu context configure doesn't work after any await func

### ISSUE THREAD

**Issue by syple000** [googlecodelabs/feedback#1425]
for example.
context.configure({
    ... any conf
})
await 1; // here, await
const pass = encoder.beginRenderPass({
   colorAttachments: [{
        view: ctx.getCurrentTexture().createView(),
        ... 
    } as GPURenderPassColorAttachment]
});

browser report warning:
[TextureView of Texture (unlabeled 300x150 px, TextureFormat::BGRA8Unorm)] is associated with [Device], and cannot be used with [Device].
 - While validating colorAttachments[0].
 - While encoding [CommandEncoder (unlabeled)].BeginRenderPass([null]).

localhost/:1 [Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])

**Comment by syple000** [comment]
i must configure again after await to deliminate the warning

**Comment by beaufortfrancois** [comment]
I wonder if it's a bug in Chromium. Can you file one at https://issues.chromium.org/issues/new?noWizard=true&component=1456980&template=0?
