### ISSUE TITLE
[cloud-run-djangocms]: ImportErrors on migrate or createuser from freshly built docker image

### ISSUE THREAD

**Issue by dreucifer** [googlecodelabs/feedback#1428]
Trying to run migrate or create user gives me some import errors.
The requirements.txt seems to be working and setting up the docker environment just fine but then...

"ImportError: cannot import name 'get_storage_class' from 'django.core.files.storage' (/layers/google.python.pip/pip/lib/python3.12/site-packages/django/core/files/storage/__init__.py)"

**Comment by glasnt** [comment]
Minimum replication steps: 

```
python -m venv venv
source venv/bin/activate
pip install djangocms-frontend\[cms-3]
django-admin startproject --template https://github.com/django-cms/cms-template/archive/3.11.zip myproject .
python manage.py runserver
```

Issue: This codelab is pinned to Django CMS 3 (both the frontend package and template project), but the underlying Django is unpinned to Django 5, causing inconsistencies with older Django CMS code newer Django code (I believe there's a deprecation related issue here). 

If you update the commands to use DjangoCMS 4, you no longer get this issue: 

```
pip install djangocms-frontend\[cms-4]
django-admin startproject --template https://github.com/django-cms/cms-template/archive/4.1.zip myproject .
```

I'll update the codelab to suit.
