### ISSUE TITLE
[passkey-form-autofill] glitch link broken

### ISSUE THREAD

**Issue by KyGuy2002** [googlecodelabs/feedback#1438]
https://developers.google.com/codelabs/passkey-form-autofill#1

The link to the Glitch project does not work.  Reloading (as suggested) does not fix the issue:
![image](https://github.com/user-attachments/assets/afa46f81-3a35-45e7-8668-9e7e1628f7cd)

![image](https://github.com/user-attachments/assets/9d841e0a-0fcf-44c7-ad15-04526eef5521)

**Comment by agektmr** [comment]
Thank you for the feedback. Glitch is very unstable. Please try again later.
We are considering migrating to another platform.
