### ISSUE TITLE
[cloud-slack-bot]: imported fragments are not imported properly

### ISSUE THREAD

**Issue by ianlewis** [googlecodelabs/feedback#144]
Some of the sections include a [[import __link__]] which are not being processed by the codelab generator.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
