### ISSUE TITLE
[cloud-run-wagtail]: Error: unknown flag: --instances

### ISSUE THREAD

**Issue by songproducer** [googlecodelabs/feedback#1443]
Hello,

Running:
`./cloud-sql-proxy --instances=${PROJECT_ID}:${REGION}:myinstance=tcp:5432
`
returns
`Error: unknown flag: --instances`

**Comment by glasnt** [comment]
Hi @songproducer

Try the same command, but without the `--instances`. 

Looks like depending on which version of Cloud SQL Auth Proxy you're using, `--instances` is now the default input, no longer on a parameter. https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md

**Comment by songproducer** [comment]
@glasnt Thanks, I was able to run the command but I don't understand how to move from Google cloud shell to local terminal. Do I need to go through the tutorial again from local terminal?

**Comment by glasnt** [comment]
If you have completed the tutorial in Cloud Shell, the only local config you will need is re-asserting your environment variables (project id, region, etc)

**Comment by songproducer** [comment]
That makes sense, thanks!

**Comment by songproducer** [comment]
I ran this in my local terminal:

`gcloud run jobs execute migrate --region $REGION --wait
`
and got this

`django.core.exceptions.ImproperlyConfigured: STATICFILES_STORAGE/STORAGES are mutually exclusive.
`

**Comment by glasnt** [comment]
`STORAGES` as a dict config replaced many of the `STATICFILES_` settings a [few versions ago](https://github.com/wagtail/wagtail/commit/a631d6bb72150d40e98f05d6732295f8ba0e7fc2); make sure you're using the most recent version of Wagtail when you generate your project. 

This codelab opts to copy the wagtail template settings with ones specific for this solution, and doesn't define `STATICFILES_STORAGE`, so I can only presume it's coming from the wagtail template.

**Comment by songproducer** [comment]
Thanks for explaining that @glasnt

I'm having a lot of trouble though moving from google cloud shell to terminal with the goal of uploading my own wagtail project.

When I do 
gcloud builds submit --pack image=${ARTIFACT_REGISTRY}/myimage
I get
ERROR: (gcloud.builds.submit) PERMISSION_DENIED: permission denied on resource project "investincrypto-438509". This command is authenticated as ********@gmail.com which is the active account specified by the [core/account] property and it looks like it's not uploading the files from my local directory still.

**Comment by glasnt** [comment]
Cloud Shell does a lot of things for you, like handling authentication. Make sure you follow the full [user login process](https://cloud.google.com/docs/authentication/gcloud) when running on your local terminal
