### ISSUE TITLE
[cloud-text-speech-python3] Issue description

### ISSUE THREAD

**Issue by EduardVidalTulsa** [googlecodelabs/feedback#1445]
This not show how i put my api key

**Comment by PicardParis** [comment]
Hi @EduardVidalTulsa,
- The tutorial runs in Cloud Shell where users are already authenticated
- If you want to run the tutorial locally, you can authenticate with the [gcloud command-line tool](https://cloud.google.com/docs/authentication/gcloud)
- To answer your question, if you are using an API key, you can specify it in the client options:
  ```py
  import google.api_core.client_options
  import google.cloud.texttospeech as tts
  
  API_KEY = "..."
  client_options = google.api_core.client_options.ClientOptions(api_key=API_KEY)
  client = tts.TextToSpeechClient(client_options=client_options)
  ```
- More info on [using API keys](https://cloud.google.com/docs/authentication/api-keys-use)
