### ISSUE TITLE
[your-first-webgpu-app]

### ISSUE THREAD

**Issue by kpiascik** [googlecodelabs/feedback#1453]
On step 8 "Run the simulation" the code for the bindGroupLayout does not include the fragment shader in the visibility for binding 0.  This causes a problem since we are definitely referencing the grid uniform in the fragment shader as per the previous instructions.

**Comment by beaufortfrancois** [comment]
See https://github.com/googlecodelabs/feedback/issues/1313#issuecomment-1842489965
