### ISSUE TITLE
[cloud-networking-101]:

### ISSUE THREAD

**Issue by jeffeharris** [googlecodelabs/feedback#148]
Section 14: Test Network Load Balancer 1/3

This command:
gcloud compute target-pools create apaches --region us-central1 --health-check basic-check

Returns a warning:
WARNING: The --health-check flag is deprecated. Use equivalent --http-health-check=basic-check flag.

The command still completes but may need to be updated.

**Comment by jeffeharris** [comment]
This command:
gcloud compute target-pools add-instances apaches --instances us-vm1,us-vm2 --zone us-central1-f

Returns a warning as well:
WARNING: The --zone flag is deprecated. Use equivalent --instances-zone=us-central1-f flag.

Still works as well

**Comment by jeffeharris** [comment]
Just in general, several flags have been deprecated for these APIs, still works, good lab!

**Comment by thesmiler** [comment]
Hi this lab has been completely redone, the Networking Load Balancer didn't make it into the new one....
