### ISSUE TITLE
[cloud-running-a-container]: Error from server: replicationcontrollers "wordpress" not found

### ISSUE THREAD

**Issue by isoughtajam** [googlecodelabs/feedback#16]
In step 4 of "Running a Container with GKE", when I try to execute `kubectl expose rc wordpress --type=LoadBalancer` I get the above error.

I know the pod exists and is running (as set up in previous steps) because:

```
$ kubectl get pods
NAME                        READY     STATUS    RESTARTS   AGE
wordpress-297829341-rp88v   1/1       Running   0          3h
```

and also:

```
$ kubectl describe pods wordpress
Name:           wordpress-297829341-rp88v
Namespace:      default
Node:           gke-hello-world-caf65fc7-node-ww0b/10.128.0.2
Start Time:     Sat, 26 Mar 2016 20:32:58 -0700
Labels:         pod-template-hash=297829341,run=wordpress
Status:         Running
IP:             10.48.1.3
Controllers:    ReplicaSet/wordpress-297829341
Containers:
  wordpress:
    Container ID:       docker://c32f13203c59fc7a26955bd9cfa7b354586198749e93803ed609ca77d8859033
    Image:              tutum/wordpress
    Image ID:           docker://20c52a34e232b5f2f2baf2a8029e1e4dad6dea7a6edb80d5e499b02d277cabc7
    Port:               80/TCP
    QoS Tier:
      cpu:      Burstable
      memory:   BestEffort
    Requests:
      cpu:              100m
    State:              Running
      Started:          Sat, 26 Mar 2016 20:33:16 -0700
    Ready:              True
    Restart Count:      0
    Environment Variables:
Conditions:
  Type          Status
  Ready         True 
Volumes:
  default-token-nq5z1:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-nq5z1
No events.
```

Replacing "wordpress" with "wordpress-297829341-rp88v" does not change matters. I found https://github.com/kubernetes/kubernetes/issues/13173 but I'm not completely sure where to go from there. I did confirm that I have no running replicationcontrollers using `kubectl get rc`.

**Comment by isoughtajam** [comment]
`kubectl create` I'm guessing :)

Figuring out how that needs to be configured.

**Comment by isoughtajam** [comment]
I didn't create a replication controller.

Steps to complete the codelab:
1. I exposed the pod using `kubectl expose pod <full-pod-name> --type=LoadBalancer`. Full-pod-name meaning "wordpress-297829341-i8g3" instead of "wordpress".
2. `kubectl describe services wordpress` did not show me the LoadBalancer Ingress, but `kubectl get service` showed me the external IP.

**Comment by x1ddos** [comment]
@hostirosti take a look in case the codelab needs some tweaking.
