### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by wclock** [googlecodelabs/feedback#164]
kubectl get pods - status stuck in ContainerCreating. Tested with busybox and all was fine. Reset VM instances. Deleted slack-codelab deployment and started over. No luck with anything. 

------------------------

NAME                             READY     STATUS              RESTARTS   AGE
busybox                          1/1       Running             0          46m
slack-codelab-2013566803-tt9ng   0/1       ContainerCreating   0          14m

------------------------

Ran kubectl describe po and the result was:

------------------------

Name:           slack-codelab-2013566803-zs1pm
Namespace:      default
Node:           gke-my-cluster-default-pool-f878fd4a-8lp9/10.128.0.3
Start Time:     Tue, 28 Feb 2017 10:55:13 -0600
Labels:         app=slack-codelab
                pod-template-hash=2013566803
Status:         Pending
IP:
Controllers:    ReplicaSet/slack-codelab-2013566803
Containers:
  master:
    Container ID:
    Image:              gcr.io/wes-bot/slack-codelab:v1
    Image ID:
    Port:
    Requests:
      cpu:              100m
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Volume Mounts:
      /etc/slack-token from slack-token (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-07qqr (ro)
    Environment Variables:
      slack_token_path: /etc/slack-token/slack-token
Conditions:
  Type          Status
  Initialized   True 
  Ready         False 
  PodScheduled  True 
Volumes:
  slack-token:
    Type:       Secret (a volume populated by a Secret)
    SecretName: slack-token
  default-token-07qqr:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-07qqr
QoS Class:      Burstable
Tolerations:    <none>
Controllers:    ReplicaSet/slack-codelab-2013566803
Events:
  FirstSeen     LastSeen        Count   From                                                    SubObjectPath   Type            Reason          Message
  ---------     --------        -----   ----                                                    -------------   --------        ------          -------
  20m           20m             1       {default-scheduler }                                                    Normal          Scheduled       Successfully assigned slack-codelab-2013566803-zs1pm to gke-my-cluster-default-pool-f878fd4a-8
lp9
  18m           37s             9       {kubelet gke-my-cluster-default-pool-f878fd4a-8lp9}                     Warning         FailedMount     Unable to mount volumes for pod "slack-codelab-2013566803-zs1pm_default(ac6704f8-fdd6-11e6-884
5-42010a800fc5)": timeout expired waiting for volumes to attach/mount for pod "default"/"slack-codelab-2013566803-zs1pm". list of unattached/unmounted volumes=[slack-token]
  18m           37s             9       {kubelet gke-my-cluster-default-pool-f878fd4a-8lp9}                     Warning         FailedSync      Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "defa
ult"/"slack-codelab-2013566803-zs1pm". list of unattached/unmounted volumes=[slack-token]
  20m           25s             18      {kubelet gke-my-cluster-default-pool-f878fd4a-8lp9}                     Warning         FailedMount     MountVolume.SetUp failed for volume "kubernetes.io/secret/ac6704f8-fdd6-11e6-8845-42010a800fc5
-slack-token" (spec.Name: "slack-token") pod "ac6704f8-fdd6-11e6-8845-42010a800fc5" (UID: "ac6704f8-fdd6-11e6-8845-42010a800fc5") with: secrets "slack-token" not found

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
