### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by rsingla** [googlecodelabs/feedback#166]
Bug1:   

Dependency missing in the docmentation to be added in Pom.xml

<dependency>
                <groupId>com.google.appengine</groupId>
                <artifactId>gcloud-maven-plugin</artifactId>
                <version>2.0.9.133.v201611104</version>
        </dependency>

    <build>
        <plugins>
       
            <plugin>
                <groupId>com.google.appengine</groupId>
                <artifactId>gcloud-maven-plugin</artifactId>
                <version>2.0.9.133.v201611104</version>
            </plugin>

Bug2:  Version is not updated to the latest version 

Bug3: Even after updating above its didnt start a VM - Rather gave error as below
ERROR: (gcloud.app.deploy) The current Google Cloud project [cp100-160XXX] does not contain an App Engine application. Use `gcloud app create` to initialize an App Engine 
application within the project.

From the instruction it mentioned that your VM will automatically get started. (Unless there is some security setting which could be missing) - Again not provided as part of the instruction.

I had to do this first:

Creating App Engine application in project [cp100-160XXX] and region [us-central]....done.                                                                                        
Success! The app is now created. Please use `gcloud app deploy` to deploy your first app.

**Comment by meteatamel** [comment]
Please try the latest codelab.
