### ISSUE TITLE
Step 4: Broken link for pushing to the registry docs in Hello Node Kubernetes

### ISSUE THREAD

**Issue by Splaktar** [googlecodelabs/feedback#17]
On [step 4](https://codelabs.developers.google.com/codelabs/hello-kubernetes/index.html?index=..%2F..%2Fgcp-next#3) in the bottom green panel the link is broken.

Broken:
https://cloud.google.com/container-registry/#pushing_to_the_registry

Correct:
https://cloud.google.com/container-registry/docs/#pushing_to_the_registry

Would love to have submitted the PR to fix this, but I can't find the source code anywhere.

**Comment by alexismp** [comment]
I have fixed this in this updated version (note the new URL):
https://codelabs.developers.google.com/codelabs/cloud-hello-kubernetes/index.html
