### ISSUE TITLE
[cloud-create-a-vm]:

### ISSUE THREAD

**Issue by joblini** [googlecodelabs/feedback#171]
I enrolled in the Qwiklabs  GCP Essentials Quest, which is advertised as free, but I can't access the lab because it prompts for Lab Access Code when the "Start Lab" button is pressed.

https://google.qwiklabs.com/focuses/3149

**Comment by shamidrasool** [comment]
Same issue here! Despite this announcement:

http://blog.qwiklabs.com/2017/03/08/1209/

**Comment by kahveci** [comment]
Any updates on this? Honestly, I'm struggling to understand what makes it so difficult to close this issue. It has been over one year now. @marcacohen @hostirosti 

For those who want to access the Qwiklabs GCP free of charge, [the offer](http://blog.qwiklabs.com/2017/03/08/1209/) was available just for a limited period of time. Apparently, you need to purchase credits or get an access code (e.g. from GCP instructors in a training) to complete a lab.

**Comment by mco-gh** [comment]
Sorry, but this repo has nothing to do with Qwiklabs. I've reached out to the Qwiklabs team at Google and they replied thusly:
---
That blog post is from well over a year ago and we completely changed how self-paced labs are taken about a month ago. The recommended support channel for Qwiklabs is go to https://qwiklabs.com/faq. If you still have questions, click on "Ask your Own Question" in the bottom right corner.

Please re-open if you disagree with how I've handled this issue.
