### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by Nsikaktopdown** [googlecodelabs/feedback#173]
please how can i get the lab access code?

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
