### ISSUE TITLE
[cloud-app-engine-aspnetcore]: Unrecognized Directory when entering gcloud command

### ISSUE THREAD

**Issue by tmccal2** [googlecodelabs/feedback#174]
`gcloud beta app gen-config --custom` returns:
`(gcloud.beta.app.gen-config) Unrecognized directory type: [/home/tmccal2/HelloWorldAspNetCore/bin/Release/netco
reapp1.0/publish]`

**Comment by meteatamel** [comment]
This is not relevant anymore for the codelab. That instruction was removed.
