### ISSUE TITLE
[cloud-app-engine-springboot]: No plugin found for prefix 'gcloud' in the current project and in the plugin groups

### ISSUE THREAD

**Issue by laszlocsontos** [googlecodelabs/feedback#176]
Hi,

I'm experimenting with deploying Spring Boot apps to the Flexible App Engine env. using this tutorial: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html

This is only a documentation mistake, it's possible to complete the tutorial after some tweaking.

*REPRODUCE*

Step #7 says that `mvn gcloud:deploy` needs to be issued and when you do it, the following error appears.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.128 s
[INFO] Finished at: 2017-03-18T18:05:09+01:00
[INFO] Final Memory: 19M/47M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'gcloud' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/serviceprovider/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

While trying to find out what might have caused the problem, I found this suggestion: http://stackoverflow.com/a/39628112

*WORDAROUND*

Upgraded the Google Cloud maven plugin's version like this.

```
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>appengine-maven-plugin</artifactId>
  <version>1.2.1</version>
</plugin>
```

When submitting `mvn appengine:deploy` another error appears.

```
[INFO] <<< appengine-maven-plugin:1.2.1:deploy (default-cli) < package @ gs-spring-boot <<<
[INFO] 
[INFO] --- appengine-maven-plugin:1.2.1:deploy (default-cli) @ gs-spring-boot ---
[INFO] Deleting the staging directory: /home/serviceprovider/gs-spring-boot/complete/target/appengine-staging
[INFO] Staging the application to: /home/serviceprovider/gs-spring-boot/complete/target/appengine-staging
[INFO] Detected App Engine flexible environment application.
Mar 18, 2017 6:09:54 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: /google/google-cloud-sdk/bin/gcloud app deploy
[INFO] GCLOUD: WARNING: Automatic app detection is currently in Beta
[INFO] GCLOUD: Writing [app.yaml] to [/home/serviceprovider/gs-spring-boot/complete/target/appengine-staging].
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) The current Google Cloud project [marketing-161910] does not contain an App Engine application. Use `gcloud app create` to initialize an App Engine application within the project.
```

After executing `gcloud app deploy` as the error message suggests and retrying `mvn appengine:deploy` deployment succeeds eventually.

Cheers,
László

**Comment by alagambhat** [comment]
https://stackoverflow.com/a/46915784/3426884

**Comment by ireneclare** [comment]
I have added the plugin to the pom.xml

 <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>1.3.1</version>
</plugin>

When I run in terminal using mvn gcloud:run 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.433 s
[INFO] Finished at: 2017-10-25T17:11:14+05:30
[INFO] Final Memory: 13M/206M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'gcloud' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/irene/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

Why is the plugin not considered?

**Comment by RubenBaez** [comment]
This works for me. Put it in your pom.xml

<build>
    <plugins>
        <plugin>
            <groupId>com.google.appengine</groupId>
            <artifactId>appengine-maven-plugin</artifactId>
            <version>1.3.1</version>
        </plugin>
    </plugins>
</build>

**Comment by alonyb** [comment]
This works for me, put it in your pom.xml

```
<build>
    <plugins>
        <plugin>
            <groupId>com.google.appengine</groupId>
            <artifactId>appengine-maven-plugin</artifactId>
            <version>1.9.9</version>
        </plugin>
    </plugins>
</build>
```

**Comment by saturnism** [comment]
The code lab has been updated to use the new java11 runtime (beta) w/ JAR deployment (and a new version of the plugin)
