### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by kurohouou** [googlecodelabs/feedback#178]
After creating the slack-token on page 7 the permissions are not configured correctly.  This should be documented to fix this problem.

**Comment by tswast** [comment]
Could you give more details on what the permissions error you are getting is?

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
