### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by kurohouou** [googlecodelabs/feedback#179]
On Page 9, the extra credit section for pushing a message to the Incoming Webhooks gives an error saying https not supported or disabled in libcurl.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
