### ISSUE TITLE
Step 7: Error from server: replicationcontrollers "hello-node" not found

### ISSUE THREAD

**Issue by Splaktar** [googlecodelabs/feedback#18]
On [step 7](https://codelabs.developers.google.com/codelabs/hello-kubernetes/index.html?index=..%2F..%2Fgcp-next#6) of the Hello Node Kubernetes code lab:

```
kubectl expose rc hello-node --type="LoadBalancer"
Error from server: replicationcontrollers "hello-node" not found
```

This seems to be related to https://github.com/googlecodelabs/feedback/issues/16.

Running `kubectl get rc` returns nothing.

The correct command appears to be `kubectl expose pod <full-pod-name> --type="LoadBalancer"` using the pod name from `kubectl get pods`.

There is an alternative workaround posted in https://github.com/googlecodelabs/feedback/issues/10.

**Comment by alexismp** [comment]
Codelab update [posted](https://codelabs.developers.google.com/codelabs/cloud-hello-kubernetes/index.html) to use `$ kubectl expose deployment hello-node --type="LoadBalancer"`
