### ISSUE TITLE
[cloud-springboot-kubernetes]: gs-spring-boot-0.1.0.jar is missing

### ISSUE THREAD

**Issue by komljen** [googlecodelabs/feedback#181]
Missing command in guide before building Docker image for the first time:
```~/gs-spring-boot/complete$ ./mvnw -DskipTests package```

**Comment by saturnism** [comment]
This was prob fixed a while back.
https://codelabs.developers.google.com/codelabs/cloud-springboot-kubernetes/index.html?index=..%2F..spring#4
