### ISSUE TITLE
Step 7: Error from server: services "hello-node" not found

### ISSUE THREAD

**Issue by Splaktar** [googlecodelabs/feedback#19]
On [step 7](https://codelabs.developers.google.com/codelabs/hello-kubernetes/index.html?index=..%2F..%2Fgcp-next#6) of the Hello Node Kubernetes code lab:

```
kubectl get services hello-node
Error from server: services "hello-node" not found
```

The correct command appears to be `kubectl get services` which gives:

```
NAME                       CLUSTER-IP    EXTERNAL-IP       PORT(S)    AGE
hello-node-2122614146-x8   10.41.242.1   130.211.177.101   8080/TCP   3m
kubernetes                 10.41.230.1   <none>            443/TCP    21m
```

Or using the full service name like `kubectl get service hello-node-2142604176-x8`:

```
NAME                       CLUSTER-IP    EXTERNAL-IP       PORT(S)    AGE
hello-node-2122614146-x8   10.41.242.1   130.211.177.101   8080/TCP   3m
```

NOTE: IPs modified to be bogus.

**Comment by alexismp** [comment]
Fixed in staging, @crhym3 should push it soon to prod.
Thanks for all the reports.
