### ISSUE TITLE
[cloud-app-engine-springboot]: missing cleanup section.

### ISSUE THREAD

**Issue by pekelund** [googlecodelabs/feedback#192]
From: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..%2Findex#1:

"Running through this codelab shouldn't cost you more than a few dollars, but it could be more if you decide to use more resources or if you leave them running (see "cleanup" section at the end of this document)."

Cannot find this cleanup section.

**Comment by meteatamel** [comment]
Thanks for reporting, cleanup section added.
