### ISSUE TITLE
Escaping problems in code samples

### ISSUE THREAD

**Issue by samdutton** [googlecodelabs/feedback#2]
In [this step](https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-10?hl=en), for example, I see `for (var i = 0; i & lt; windowClients.length; i++)`.

Looks OK in [preview](https://codelabs-preview.appspot.com/?file_id=1T2wnuojyxOL9bgWkFrtB8t9rWcTa2f0UckrCrnrqc08#10).

**Comment by x1ddos** [comment]
Sam, https://developers.google.com/web/ are doing on their own at the moment. The content on that site is not generated by codelabs platform, unfortunately.

**Comment by ryanseys** [comment]
@samdutton what makes you think that the feedback for that site should go here? Is there a link somewhere in web fundamentals that is pointing you to this repo?

**Comment by samdutton** [comment]
Sorry Ryan — as per other thread, got link to WF site, thought I was
looking at CDS.

:/

**Comment by ryanseys** [comment]
Thanks Sam, no worries. Just making sure this link isn't floating around in the wrong documentation :smile:

**Comment by samdutton** [comment]
Cheers Ryan!
