### ISSUE TITLE
Step 8: Hello Node Kubernetes: Change rc to deployment

### ISSUE THREAD

**Issue by Splaktar** [googlecodelabs/feedback#20]
On [step 8](https://codelabs.developers.google.com/codelabs/hello-kubernetes/index.html?index=..%2F..%2Fgcp-next#7) of the Hello Node Kubernetes code lab:

```
kubectl scale rc hello-node --replicas=3
Error from server: replicationcontrollers "hello-node" not found
```

This seems to be related to https://github.com/googlecodelabs/feedback/issues/16 and this [comment](https://github.com/googlecodelabs/feedback/issues/10#issuecomment-207900790).

As indicated by the comment, changing `rc` to `deployment` fixed the issue:

```
kubectl scale deployment hello-node --replicas=3
deployment "hello-node" scaled
kubectl get pods
NAME                          READY     STATUS              RESTARTS   AGE
hello-node-2142604176-6wvvo   1/1       Running             0          10s
hello-node-2142604176-i8huy   0/1       ContainerCreating   0          10s
hello-node-2142604176-x8htk   1/1       Running             0          40m
```

**Comment by alexismp** [comment]
Hi @Splaktar and sorry for the delay. An updated version of this codelab has been posted here:
https://codelabs.developers.google.com/codelabs/cloud-hello-kubernetes/index.html
It should fix this issue and most (if not all) of the others you have filed.

**Comment by alexismp** [comment]
Closing the issue. Feel free to reopen of file a new one if you see something that needs an update.
cc @Splaktar
