### ISSUE TITLE
Step 24/25 "Build a Progressive Web App with Firebase, Polymerfire and Polymer Components" no data entry in the database

### ISSUE THREAD

**Issue by gianmarcogiummarra** [googlecodelabs/feedback#205]
Hello everyone, I followed the tutorial until the step 24, so far so good. But when I verify (step 25) if the notes that I create actually go in the Firebase database, I don't have a tree structure, because no entry was put there.
Both in Safari and Chrome, when I add a note, the console shows me this error: 

> [Error] TypeError: this.$.document.save is not a function. (In 'this.$.document.save(this.notesPath)', 'this.$.document.save' is undefined)
	save (data:text/javascript;charset=utf-8,%0A…%0A:70)
	commitChange (data:text/javascript;charset=utf-8,%0A…%0A:49)
	handler (data:text/javascript;charset=utf-8,(fu…%0A:491)
	dispatchEvent
	fire (data:text/javascript;charset=utf-8,(fu…%0A:1268)
	close (data:text/javascript;charset=utf-8,%0A…%0A:50)
	save (data:text/javascript;charset=utf-8,%0A…%0A:37)
	handler (data:text/javascript;charset=utf-8,(fu…%0A:491)
	dispatchEvent
	fire (data:text/javascript;charset=utf-8,(fu…%0A:1268)
	fire (data:text/javascript;charset=utf-8,(fu…%0A:840)
	forward (data:text/javascript;charset=utf-8,(fu…%0A:1137)
	click (data:text/javascript;charset=utf-8,(fu…%0A:1122)
	handleNative (data:text/javascript;charset=utf-8,(fu…%0A:730)

Plus, other errors are given when starting the web app, the screenshot is attached.
Maybe the problem is that the bower_components are obsolete?

![screen shot 2017-04-22 at 13 15 04](https://cloud.githubusercontent.com/assets/9169021/25303967/bd6962c2-275d-11e7-9fff-6b6995febba2.png)

**Comment by Connor-Macdonald** [comment]
If you change this.$.document.save(this.notesPath) to this.$.document.saveValue(this.notesPath) It will work.

**Comment by FluorescentHallucinogen** [comment]
I think this issue can be closed. Fixed in https://github.com/PolymerLabs/note-app-elements/commit/4992c5ff801c08e511b38e64e63773d7521d3f0a.

**Comment by surj08** [comment]
I'd like to report I had the same issue (I thought there was a button for that) and that @Connor-Macdonald adding in Value worked perfectly after a empty cache and hard reload.

Thanks so much! I'm new to this and wasn't exactly sure what the problem was. Is there a way for me to update my current environment/working folder to the new working version?
