### ISSUE TITLE
[polymer-firebase-pwa] this.$.document.save is not a function

### ISSUE THREAD

**Issue by Anid4u2c** [googlecodelabs/feedback#209]
Hi,

Looks like a good tutorial, and I know others were able get it going.  I tried troubleshooting my firebase-app configuration (was not the issue), and looked over my code more than twice - still I'm getting this wonky error that prevents me from creating notes.  I've logged out, cleared the cache, and logged back in, so I don't think it's an auth issue.

> na-behavior.html:80 Uncaught TypeError: this.$.document.save is not a function
    at HTMLElement.save (na-behavior.html:80)
    at HTMLElement.commitChange (na-behavior.html:59)
    at HTMLElement.handler (polymer.html:507)
    at HTMLElement.fire (polymer.html:1284)
    at HTMLElement.close (na-editor.html:139)
    at HTMLElement.save (na-editor.html:126)
    at HTMLElement.handler (polymer.html:507)
    at HTMLElement.fire (polymer.html:1284)
    at Object.fire (polymer.html:856)
    at Object.forward (polymer.html:1153)<

From Windows, I used "polymer analyze > analysis.json" and I can saw that "save" is declared:

>
...
{
          "name": "save",
          "type": "Function",
          "description": "",
          "privacy": "public",
          "sourceRange": {
            "file": "bower_components\\note-app-elements\\na-behavior.html",
            "start": {
              "line": 75,
              "column": 6
            },
            "end": {
              "line": 85,
              "column": 7
            }
          },
          "metadata": {
            "polymer": {}
          },
          "inheritedFrom": "Polymer.NoteAppBehaviorImpl"
        },
...
<

I'd really like to figure out what is going on... please reply!

Thanks!

**Comment by jansink** [comment]
I also have this issue

**Comment by Anid4u2c** [comment]
Just found & copied this (here:  https://github.com/PolymerLabs/note-app/issues/8). Turns out the tutorial code needs an update:
https://stackoverflow.com/questions/43449313/issues-in-saving-document-using-polymerfire

To fix, find bower_components/note-app-elements/na-behaviour.html and change:
`return this.$.document.save(this.notesPath).then(function() {`
to
`return this.$.document.saveValue(this.notesPath).then(function() {`

TESTED AND WORKED :+1:

**Comment by enjikaka** [comment]
Also having this issue. Modifying the lib is a bit dirty... Good if note-app-elements was updated!
