### ISSUE TITLE
Step 9: error: couldn't find a replication controller with source id == default/hello-node

### ISSUE THREAD

**Issue by Splaktar** [googlecodelabs/feedback#21]
On [step 9](https://codelabs.developers.google.com/codelabs/hello-kubernetes/index.html?index=..%2F..%2Fgcp-next#8) of the Hello Node Kubernetes code lab:

```
kubectl rolling-update hello-node --image=gcr.io/gdgx-cloud/hello-node:v2 --update-period=2s
error: couldn't find a replication controller with source id == default/hello-node
```

This seems to be related to https://github.com/googlecodelabs/feedback/issues/18 where a replicationcontroller was not automatically created as the code lab said it would be.

To create the Replication Controller, the following needs to be done:
1. `nano replicationController.json`
1. Paste the contents of [this gist](https://gist.github.com/Splaktar/47a76f2dc9e053073e6278bdb5dfec5c) into the file and save it.
1. `kubectl create -f replicationController.json`

```
replicationcontroller "hello-node" created
```

Then re-run the `rolling-update` and it will succeed.

This really should be done in [step 7](https://codelabs.developers.google.com/codelabs/hello-kubernetes/index.html?index=..%2F..%2Fgcp-next#6) so that step 8 and 9 don't fail due to the missing replication controller.

**Comment by alexismp** [comment]
The [codelab](https://codelabs.developers.google.com/codelabs/cloud-hello-kubernetes/index.html) "Roll out an upgrade to your website" section has been updated to use `$ kubectl edit deployment hello-node`
