### ISSUE TITLE
Step 10: KubeUI does not exist in output of kubectl cluster-info

### ISSUE THREAD

**Issue by Splaktar** [googlecodelabs/feedback#22]
On [step 10](https://codelabs.developers.google.com/codelabs/hello-kubernetes/index.html?index=..%2F..%2Fgcp-next#9) of the Hello Node Kubernetes code lab:

```
kubectl cluster-info
Kubernetes master is running at https://107.39.81.152
GLBCDefaultBackend is running at https://107.39.81.152/api/v1/proxy/namespaces/kube-system/services/default-http-backend
Heapster is running at https://107.39.81.152/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://107.39.81.152/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://107.39.81.152/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
```

Using the URL from the code lab `https://107.39.81.152/api/v1/proxy/namespaces/kube-system/services/kube-ui` gives an error:

```
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "endpoints \"kube-ui\" not found",
"reason": "NotFound",
"details": {
"name": "kube-ui",
"kind": "endpoints"
},
"code": 404
}
```

`kubernetes-dashboard` seems to be what it is called now. Opening this using the admin/password explained does work, but the view is much different:

![screen shot 2016-04-16 at 12 57 42 am](https://cloud.githubusercontent.com/assets/3506071/14579197/55ea61c8-036e-11e6-92ac-f00dc3463536.png)

NOTE: IPs changed to be bogus.

**Comment by alexismp** [comment]
Codelab updated and [published](https://codelabs.developers.google.com/codelabs/cloud-hello-kubernetes/index.html) to the new dashboard feature from Kubernetes 1.2
