### ISSUE TITLE
[cloud-tensorflow-mnist]: A small typo

### ISSUE THREAD

**Issue by Eulerianial** [googlecodelabs/feedback#222]
In the sixth slide: comptation should be computation.

However, as soon as you execute a Session.run command, the values it returns are Numpy tensors, i.e. numpy.ndarray objects that can be consumed by Numpy and all the scientific **comptation** libraries based on it. That is how the real-time visualisation was built for this lab, using matplotlib, the standard Python plotting library, which is based on Numpy.

**Comment by mbrukman** [comment]
@martin-gorner — I don't see this text anywhere in the codelab anymore, so looks like it was rewritten and there are no such misspellings anymore, so this issue can be closed.
