### ISSUE TITLE
Step 22: Build a Progressive Web App with Firebase, Polymerfire and Polymer Components

### ISSUE THREAD

**Issue by eleonorsomosot** [googlecodelabs/feedback#227]
Hi, I am new to polymer as well as firebase.. I stumbled upon step 22 where Google sign in will popup and should sign you in. But in my case after that, it does not sign in and get this error in the console instead. Hope someone could help me with this.. Just let me know any further info to provide. Thanks..

![image](https://cloud.githubusercontent.com/assets/13271143/26612995/fced4340-45ea-11e7-8fbf-52365c691cf1.png)

**Comment by alexlopes** [comment]
Hi @eleonorsomosot what browser are you using?

**Comment by eleonorsomosot** [comment]
Hi @alexlopes thanks for responding. I am using google chrome browser. I have already found what caused the error. I discovered that the chrome setting on blocking third party cookie should be un-ticked. That seem to work. any way, thanks again for noticing the issue. :D
