### ISSUE TITLE
Step 11: Error from server: services "hello-node" not found when cleaning up

### ISSUE THREAD

**Issue by Splaktar** [googlecodelabs/feedback#23]
On [step 11](https://codelabs.developers.google.com/codelabs/hello-kubernetes/index.html?index=..%2F..%2Fgcp-next#10) of the Hello Node Kubernetes code lab:

```
kubectl delete services hello-node
Error from server: services "hello-node" not found
```

You actually need to get the full service name from `kubectl get service`:

```
NAME                       CLUSTER-IP    EXTERNAL-IP       PORT(S)    AGE
hello-node-2142604176-x8   10.124.132.1   123.132.123.151   8080/TCP   1h
```

Then do `kubectl delete services hello-node-2142604176-x8`:

```
service "hello-node-2142604176-x8" deleted
```

Note: IPs changed to be bogus.

**Comment by alexismp** [comment]
Fixed in this updated version of codelab:
https://codelabs.developers.google.com/codelabs/cloud-hello-kubernetes/index.html
thanks for reporting this.
