### ISSUE TITLE
[cloud-kubernetes-aspnetcore]:

### ISSUE THREAD

**Issue by mschwa** [googlecodelabs/feedback#232]
I have followed this guide step by step and word for word. 

When I get to step 6 "Package the ASP.NET Core app as a Docker container" and I execute the command "docker run -d -p 8080:8080 gcr.io/PROJECT_ID/hello-dotnet:v1" (with my correct project id), nothing happens...

![image](https://user-images.githubusercontent.com/3912569/26904609-efb3957a-4b9f-11e7-9fc8-674c2e210608.png)
 
If I remove the -d option I get this...

![image](https://user-images.githubusercontent.com/3912569/26904649-227fe170-4ba0-11e7-8777-75ed60c30021.png)

**Comment by meteatamel** [comment]
You need to run with ${PROJECT_ID}. The instructions were updated the reflect this.
