### ISSUE TITLE
Repository path change

### ISSUE THREAD

**Issue by buraksivrikaya** [googlecodelabs/feedback#238]
repository  path below is wrong

`sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded` <------Wrong one

it was changed to 

`sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa`

**Comment by x1ddos** [comment]
@buraksivrikaya which codelab is it?
Can you post a link to the page.

**Comment by buraksivrikaya** [comment]
https://launchpad.net/gcc-arm-embedded/+announcement/13824

**Comment by x1ddos** [comment]
I meant the link to the codelab. Where did you find these instructions?

**Comment by buraksivrikaya** [comment]
Oh sorry, it's in simulation.  
https://codelabs.developers.google.com/codelabs/openthread-simulation/index.html#1

**Comment by x1ddos** [comment]
Ah, apparently the feedback link in that codelab is incorrect. It should point to https://github.com/openthread/openthread/issues.

Could you please create a new issue in there? Make sure to mention https://codelabs.developers.google.com/codelabs/openthread-simulation/index.html#1.

Sorry for this. I'll ask the codelab owners to fix the feedback link.

**Comment by buraksivrikaya** [comment]
Sorry for my confusion
