### ISSUE TITLE
Hello-JNI failure generating JNI classes

### ISSUE THREAD

**Issue by billchurch76** [googlecodelabs/feedback#24]
I was following your example and when I got to the step on generating the C function from the Java, the process failed.  The only thing that happened is that I got a hello-android-jni.c file with the single line "#include <jni.h>".  No function declaration/implementation was created.

I'm using the latest Android Studio 2.0 and NDK (says version 12 in Studio's SDK Manager).

**Comment by x1ddos** [comment]
@ggfan could you take this.

**Comment by ggfan** [comment]
I will take a look with 2.0 and 2.1 preview

**Comment by ggfan** [comment]
while I was trying to use 2.0 android studio, met some strange issue, filed a bug:
  https://code.google.com/p/android/issues/detail?id=207484
Hope to get some more info from Android Team.  thanks

Oh, one check, maybe, is: make sure the names are the same:
1.  build.gradle: 
         moduleName = "hello-android-jni"
2. Java file:
        System.loadLibrary("hello-android-jni");  
   The two names must be the same. Android Studio might be confused if the name mis-match.  
   kindly let me know.

**Comment by LoveraSantiago** [comment]
First I had the problem with gradle plugin. In codelabs says to replace 'com.android.tools.build:gradle-experimental:0.4.0' which causes the Gradle piece by an old version. 
So I used 'com.android.tools.build:gradle-experimental:0.7.0-rc1' then worked in the emulator device.
Now I'm having the same problem that Mr. billchurch76. The only thing that happened is that I got a hello-android-jni.c file with the single line "#include ". No function declaration/implementation was created. And even implementing the method in hello-android-jni.c file is still giving the error Cannot resolve corresponding JNI function Java_com_google_sample_hell....

I've tried too generate method signature with javah and nothing.
Any answer?

**Comment by LoveraSantiago** [comment]
On gradle build.gradle add 

android.ndk {
        moduleName = "hello-android-jni"
        toolchain = 'clang'
        CFlags.addAll(['-Wall'])
    }

And works. Dont know why but...

**Comment by ggfan** [comment]
yes, it is known issue:  I was in the middle of the updating to the 0.7.0, but found it is broken in 2.0/2.1;  it is fixed internally in 2.2.  thank you for your finding, will try to request a back port for the fix to 2.1. The related bug is @: 
https://code.google.com/p/android/issues/detail?id=208371

thank you for reporting the issue again.

There is no workaround for this for now, just copy in the prototype for now and move along with the rest of the codelab.

**Comment by ggfan** [comment]
yeah, looks like it is too late to back port the fix to 2.1.  the fix will be in future version 2.2 [need workaround the issues in android studio 2.0/2.1].  Sorry about the inconvenience...

**Comment by LoveraSantiago** [comment]
I appreciate the answer

**Comment by x1ddos** [comment]
Closing for now. Thanks all.

**Comment by craftbox2245** [comment]
Cannot resolve corresponding JNI function Java_com_example_superpoweredsample_MainActivity_SuperpoweredExample less... (Ctrl+F1) 
Reports native method declarations in Java where no corresponding JNI function is found in the project.

**Comment by ggfan** [comment]
What is the Android Studio version you are using? Also the steps to see it or share your code somewhere I could have a  look.

Version 3.1.1/2 studio IDE high lighted all native functions to error ( not found ) even there are all works fine. Just ignore that and go ahead compile and run, it should be ok. It is annoying, Studio team knew about it. If you are talking about this, yeah, please ignore it for now. 

If it is not the above case, please get more details, be interesting to see it. Thanks
