### ISSUE TITLE
[cloud-compute-kubernetes]: Command isn't right: gcloud docker push

### ISSUE THREAD

**Issue by hqt** [googlecodelabs/feedback#243]
Step 23:
```
$ cd ~/spring-boot-docker/examples/helloworld-ui
$ vim templates/index.html
$ docker build -t gcr.io/<your-project-id>/helloworld-ui:v2 .
$ gcloud docker push gcr.io/<your-project-id>/helloworld-ui:v2
```

Command `gcloud docker push gcr.io/<your-project-id>/helloworld-ui:v2` doesn't work. It should be:

```gcloud docker -- push gcr.io/<your-project-id>/helloworld-ui:v2```

**Comment by saturnism** [comment]
this has been since updated to use jib plugin.
