### ISSUE TITLE
[cloud-aspnetcore-cloudshell]:

### ISSUE THREAD

**Issue by zachcasper** [googlecodelabs/feedback#244]
Ran through this codelab and found the following things needing updated:

Instruction:
`dotnet new -t web`

Error:
> Invalid input switch:
>   -t

Instruction:
> Open Eclipse Orion by clicking 'Files'

Confusion:
The UI has changed and I had trouble finding the editor.  It's now under a dedicated button which isn't labeled.

Instruction:

> You'll see the default ASP.NET Core webpage

Confusion:
I only saw a "Hello World!".  I think this is still right since the console request log is growing when I hit refresh in the web preview.  But it's hard to tell this is working right.  The instructions seem out of date.

**Comment by meteatamel** [comment]
All these issues have been fixed..
