### ISSUE TITLE
[cloud-compute-kubernets]: Step 14 - kubectl run doesn't create a replication controller anymore

### ISSUE THREAD

**Issue by FTWynn** [googlecodelabs/feedback#25]
Kubernetes run doesn't create a replication controller anymore, and running the command as written will create a deployment instead. This is probably most easily fixed by specifying the older generator instead.

```
kubectl run nginx --image=nginx --replicas=3
```

becomes...

```
kubectl run nginx --image=nginx --replicas=3 --generator=run/v1
```

**Comment by saturnism** [comment]
Thanks! This is addressed in the upcoming revision where we'll use deployments instead.
