### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by holachuy** [googlecodelabs/feedback#262]
In Step 6, in the command "$ docker build -t gcr.io/PROJECT_ID/hello-java:v1 .", shouldn't PROJECT_ID be ${PROJECT_ID} ? Is this Cloud Shell specific? What if not running in Cloud Shell? 
![docker_feedback](https://user-images.githubusercontent.com/26009975/30121004-075665e4-92f0-11e7-8e99-9c5e6ab855f8.png)

**Comment by meteatamel** [comment]
The codelab assumes Cloud Shell.
