### ISSUE TITLE
[cloud-app-engine-python]: Codelabs seem to be broken on Chrome v52

### ISSUE THREAD

**Issue by AlaaMohammad** [googlecodelabs/feedback#27]
I tried to open many code labs but there is no content, a blank page appear 
Here is  a link for the code lab that I have tried to open 

https://codelabs.developers.google.com/codelabs/cloud-app-engine-python/index.html?index=..%2F..%2Findex#2

and I am using Google Chrome Version 52.0.2725.0 canary (64-bit)

**Comment by x1ddos** [comment]
Can you post here links of the codelabs you've tried opening?
Also, which browser/version did you use?

/cc @ebidel

**Comment by AlaaMohammad** [comment]
Here is a link for the code lab that I have tried to open

https://codelabs.developers.google.com/codelabs/cloud-app-engine-python/index.html?index=..%2F..%2Findex#2

and I am using Google Chrome Version 52.0.2725.0 canary (64-bit)

**Comment by x1ddos** [comment]
Can you try the same link with Chrome stable? v50

**Comment by AlaaMohammad** [comment]
Yes it works fine on Google Chrome Version 50.0.2661.94 m

**Comment by x1ddos** [comment]
@ebidel could you check it out? can it be google-codelabs polymer components?

**Comment by ebidel** [comment]
That link works fine for me in Chrome Canary 52.0.2729.0.

**Comment by AlaaMohammad** [comment]
it works now after the updates !
