### ISSUE TITLE
[cloud-slack-bot]: Incorrect documentation, other issues

### ISSUE THREAD

**Issue by heathkit** [googlecodelabs/feedback#273]
I did this codelab with students at UTD as part of a recruiting event. Using Cloud Shell was awesome! No matter what machine students had, they had a consistent environment. Most people finshed in two hours (with a long pizza break), but we were hampered by some issues

- (Step 5) Slack has changed their management interface, and this page needs to be updated to how Slack works now.
- (Step 9) Container Registry is no longer under Container Engine, it's a top-level product now. The screenshots are incorrect.
- (Step 9) You need to have the Compute and Container APIs enabled in order to actually push the Docker image to a repo. This was confusing and blocked a lot of people when they got weird error messages. I made sure everyone opened the GKE, GCE, and Container Registry pages, then had them log out and back on. That fixed almost everyone, but one student was still never able to complete this step.
- (Step 10) Quite a few people missed that they had to replace PROJECT_ID in slack-codelab-deployment.yaml. Maybe that should be mentioned in the text as well as the code.
- (Step 10) Wouldn't the bot run just fine on f1-micros? That would also be a good place to show people `--preemptible`.

Thanks for the great codelab! Despite the issues, the students really enjoyed it.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
