### ISSUE TITLE
[cloud-app-engine-python]:

### ISSUE THREAD

**Issue by rsarathy101** [googlecodelabs/feedback#280]
For testing this application , for starting a dev instance of the application server
$ dev_appserver.py ./

Where is this script ?

**Comment by PicardParis** [comment]
This is part of our Cloud SDK:
- This comes preinstalled with Cloud Shell (easiest way to do most codelabs).
- You can also install it in your own environment: <[Installing Google Cloud SDK](https://cloud.google.com/sdk/install)>.
