### ISSUE TITLE
[cloud-compute-kubernets]: "Step 4: Create a Compute Engine instance" needs update

### ISSUE THREAD

**Issue by Juxtaposedwords** [googlecodelabs/feedback#29]
# Error location:
- Step 4:  Create a Compute Engine instance
# Command:
- While run from the google shell in browser 

```
$gcloud compute instances create Remba
```
# Error:

```
ERROR: (gcloud.compute.instances.create) Failed to find image for alias [debian-8] in public image project [debian-cloud].
 - Access Not Configured. Compute Engine API has not been used in project [removed] before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/
```
# Expected behavior:

Non-error state. Though the error message is excellent as it tells me exactly how to fix the issue.
# Recommend Fix:
- A step informing me to enable Compute Engine API
  -  As the last step, walked me through making a new project

**Comment by hostirosti** [comment]
Hi @Juxtaposedwords,

thank you for reporting this. There are instructions to enable the API on Step 2 "Next, you'll need to enable billing in the Developers Console in order to use Google Cloud resources and enable the Container Engine API." 

We're looking into making it more prominent.
