### ISSUE TITLE
[cloud-vision-intro]:

### ISSUE THREAD

**Issue by kerwinkfs** [googlecodelabs/feedback#299]
I copies the code right from the example and it returns the error code 400, Invalid json payload received. Unexpected token. \nFasdUAS 1.101.10\u000e\u0000\u0000\n"

request.json - file name
{
	"requests": [
		{
			"image": {
				"source": {
					"gcsImageUri": "gs://kerwintest/donuts.png"
				}
			},
			"features": [
				{
					"type": "LABEL_DETECTION",
					"maxResults": 10
				}
			]
		}
	]
}

Command line -  curl -s -X POST -H "Content-Type: application/json" --data-binary @request.json  https://vision.googleapis.com/v1/images:annotate?key=${API_KEY}

**Comment by PicardParis** [comment]
- Thank you for your feedback.
- I couldn't reproduce your issue. This looks like you edited `request.json` with a different editor/encoding (AppleScript Editor?).
- You can directly create the `json` request from the embedded editor as well as from `nano`, `vim`, `emacs`...
