### ISSUE TITLE
Two dashes parsed as Markdown

### ISSUE THREAD

**Issue by samdutton** [googlecodelabs/feedback#3]
In [this step](https://developers.google.com/web/fundamentals/getting-started/push-notifications/step-07?hl=en) the two dashes have been parsed as Markdown and converted to an en dash.

I've updated the doc so this text is in Courier New, which seems to work OK in preview.

(Someone else mentioned odd quote marks — maybe being converted to apostrophes or curly quotes? I can't see this though.)

**Comment by ryanseys** [comment]
DId you link to the right step? I'm struggling to find the two dashes you're talking about.

**Comment by samdutton** [comment]
Yeah — it's the sentence that begins like this: 'The cURL command to send a
request to GCM to is ...'

**Comment by x1ddos** [comment]
Sam, like I mentioned in #2 https://developers.google.com/web/fundamentals/ is not related to codelabs platform.

This needs to be filed somewhere in https://github.com/google/webfundamentals.

/cc @petele @gauntface

**Comment by samdutton** [comment]
AAGH! Sorry.

I got the URL for the WF codelab and thought I was looking at the CDS one.

I plead lack of sleep...
