### ISSUE TITLE
[cloud-monitoring-alerting]: small docs bug

### ISSUE THREAD

**Issue by Juxtaposedwords** [googlecodelabs/feedback#30]
# Error location:
- https://codelabs.developers.google.com/codelabs/cloud-monitoring-alerting/index.html?index=..%2F..%2Findex#1
# Error:

"Create" button is shown in the documentation but "deploy" is shown in the page.
# Expected behavior:

Should be a deploy button to match the workflow process.
# Recommend Fix:
- Replace "Create" button in docs with "Deploy" button

**Comment by hostirosti** [comment]
@Juxtaposedwords thank you for reporting this. We will update shortly. 
@crhym3 can you repush this codelab?

**Comment by x1ddos** [comment]
Should be updated now:
https://codelabs.developers.google.com/codelabs/cloud-monitoring-alerting/
