### ISSUE TITLE
[cloud-vision-intro]:

### ISSUE THREAD

**Issue by BigNom** [googlecodelabs/feedback#304]
The codelab for the detect faces vision api states to make a call with curl
`curl -s -X POST -H "Content-Type: application/json" --data-binary @request.json  https://vision.googleapis.com/v1/images:annotate?key=${API_KEY}`

The above returned an invalid API Key so I looked up the docs and it states to run the below, which worked for me
`curl -v -s -H "Content-Type: application/json" \
    https://vision.googleapis.com/v1/images:annotate?key=API_KEY \
    --data-binary @request.json`

**Comment by PicardParis** [comment]
- Rechecked the codelab: `curl` requests work as expected.
- Both the codelab command and your command work if:
  - `API_KEY` is correctly defined
  - request uses parameter `key=$API_KEY` (with `$`) or `key=${API_KEY}`
