### ISSUE TITLE
[cloud-kubernetes-aspnetcore]:

### ISSUE THREAD

**Issue by alancapc** [googlecodelabs/feedback#305]
[![image](https://user-images.githubusercontent.com/7346073/32866023-9cb9e706-ca5d-11e7-88aa-671c3380e7a4.png)](https://codelabs.developers.google.com/codelabs/cloud-kubernetes-aspnetcore/index.html?index=..%2F..%2Findex#5)

**Container engine has been renamed to Kubernetes Engine:**
[![image](https://user-images.githubusercontent.com/7346073/32866073-cacf3a92-ca5d-11e7-988a-c2beb797adcd.png)](https://cloud.google.com/kubernetes-engine/release-notes)

**Comment by meteatamel** [comment]
Fixed
