### ISSUE TITLE
HELLO-JNI Step 6 - Add an ID to the existing TextView

### ISSUE THREAD

**Issue by twalmsley** [googlecodelabs/feedback#31]
Step 6 says modify the activity_main.xml file to add an id, and that this will be the only layout file in the folder.

When I tried this I had two layout files - the second one is called content_main.xml, and this is the file I needed to add the id to.

If you update the wrong file the app will crash.

**Comment by crhym3** [comment]
@ggfun can you please take this.

**Comment by x1ddos** [comment]
@ggfan can you please take this.

**Comment by ggfan** [comment]
yes, twalmsley is correct: this indeed needs to be updated.  The difference comes from which template iwas chosen in step "Create Java Sample App", if chose "Empty Activity", the codelab is correct; if chose "Basic Activity" template, there will be 2 xml files and content_main.xml is the one.  Updated the codelab, once republish, it will be more accurate:
  1) callout to choose the "basic activity" template
  2) changed file to content_main.xml, and reminder that if chose "Empty Activity", the file is activity_main.xml

good catch, thanks  twalmsley!

**Comment by x1ddos** [comment]
Pushed the updated codelab: https://codelabs.developers.google.com/codelabs/android-studio-jni/
May take 10-30 min to clear the cache.
Reopen the issue if that doesn't happen.
