### ISSUE TITLE
[cloud-springboot-cloudshell]:

### ISSUE THREAD

**Issue by danielpall** [googlecodelabs/feedback#315]
Lab: _Build and Launch Spring Boot Java-based Web Application from Google Cloud Shell_
Page 3: It says that to switch from java 7 to java 8, but when you enter the command: 
`sudo update-alternatives --config javac`

you get the following message:
```
There is only one alternative in link group javac (providing /usr/bin/javac): /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
Nothing to configure.
```

instead of what the lab shows, which is says should be:
```
There are 2 choices for the alternative javac (providing /usr/bin/javac).
  Selection    Path                                         Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-7-openjdk-amd64/bin/javac   ...
  1            /usr/lib/jvm/java-7-openjdk-amd64/bin/javac   ...
  2            /usr/lib/jvm/java-8-openjdk-amd64/bin/javac   ...
Press enter to keep the current choice[*], or type selection number: 2
```

**Comment by flmessier** [comment]
Seems like the Google cloud shell uses java 8 by default now, so that step should probably be removed.

**Comment by Froren** [comment]
In the same tutorial on `Step 6`, it says to: 

`Open Eclipse Orion by clicking Files and then Launch code editor from the Cloud Shell menu.`

But the Cloud Shell menu is now opened from the top left nav bar.

**Comment by saturnism** [comment]
the redundant command was removed a while back.
