### ISSUE TITLE
https://codelabs.developers.google.com/codelabs/android-studio-jni/index.html

### ISSUE THREAD

**Issue by bharatiadkar** [googlecodelabs/feedback#32]
Guys, this tutorial does not work.

Please clarify
 Add JNI Build Capability to HelloAndroidJni Project
If I follow these steps, I get
Error:(3, 0) Gradle DSL method not found: 'android()'
Possible causes:<ul><li>The project 'HelloAndroidJni' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Fix plugin version and sync project</a></li><li>The project 'HelloAndroidJni' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by x1ddos** [comment]
@ggfan can you take a look, please
