### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by nicktunac** [googlecodelabs/feedback#324]
Container Engine Screenshot is not updated.

Here's the actual screen of Kubernetes Engine 

![screen shot 2017-12-28 at 3 27 59 am](https://user-images.githubusercontent.com/7882308/34391216-4ae7e0fc-eb7f-11e7-9ad3-b0dfbc701d7f.png)

**Comment by meteatamel** [comment]
This has been fixed
