### ISSUE TITLE
[cloud-app-engine-springboot]: Missing steps in tutorial and 403 in final result.

### ISSUE THREAD

**Issue by Leejjon** [googlecodelabs/feedback#327]
Hi,

When following the tutorial at step at:
https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..%2Findex#5

I have to add these dependencies to make it compile:
```
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-core</artifactId>
    <version>5.0.2.RELEASE</version>
</dependency>
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-web</artifactId>
    <version>5.0.2.RELEASE</version>
</dependency>
```

Next when I follow the step described in the tutorial:
`mvnw -DskipTests appengine:run`

When I run it now I'm getting a 403 and no error:
https://i.imgur.com/HvhLrhZ.png

I use JDK8 on Windows 10 with the 1.5.9 (default) spring boot version.

**Comment by Leejjon** [comment]
Update: I fixed it by changing the following in the pom.xml:
`<packaging>jar</packaging>` to `<packaging>war</packaging>` 

Source: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/191

**Comment by Leejjon** [comment]
When I run it now I'm getting a 403 and no error:
https://i.imgur.com/HvhLrhZ.png

Is this tutorial outdated or something?

**Comment by Leejjon** [comment]
Okay I got it working now. The tutorial works if you use the latest 2.0.0M7 release instead of the default selected 1.5.9, that version will give errors. I do notice a nullpointer in the start up logs:

```
[INFO] GCLOUD: 2018-01-01 17:48:19.788:INFO:oejs.Server:main: jetty-9.3.18.v20170406
[INFO] GCLOUD: 2018-01-01 17:48:20.101:WARN:oeja.ClassInheritanceHandler:qtp434091818-16:
[INFO] GCLOUD: java.lang.NullPointerException
[INFO] GCLOUD:  at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
[INFO] GCLOUD:  at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:72)
[INFO] GCLOUD:  at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:58)
[INFO] GCLOUD:  at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:476)
[INFO] GCLOUD:  at org.objectweb.asm.ClassReader.accept(ClassReader.java:650)
[INFO] GCLOUD:  at org.objectweb.asm.ClassReader.accept(ClassReader.java:525)
[INFO] GCLOUD:  at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:978)
[INFO] GCLOUD:  at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
[INFO] GCLOUD:  at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
[INFO] GCLOUD:  at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
[INFO] GCLOUD:  at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
[INFO] GCLOUD:  at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
[INFO] GCLOUD:  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO] GCLOUD:  at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO] GCLOUD:  at java.lang.Thread.run(Thread.java:745)
```

But it works so I am going to ignore it for now.

**Comment by rahul7471** [comment]
@Leejjon Can you please provide the solution to above error.
I am getting that error. 
I am using spring-boot version 2.0.2.RELEASE and java 8 and trying to run server on google app engine.

**Comment by Leejjon** [comment]
@rahul7471 even though this problem showed up in my logs it would still just run. So I don't really have a solution. Maybe check if there is some other error or something else wrong in your project.
