### ISSUE TITLE
[cloud-spring-petclinic-cloudsql]:

### ISSUE THREAD

**Issue by ramimmadi** [googlecodelabs/feedback#334]
This is not working with ./mvnw spring-boot:run this command locally.
 INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.springframework.samples:spring-petclinic:2.0.0: Could not find artifact org.springframework.boot:spring-boot-starter-parent:po
m:2.0.0.BUILD-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.springframework.samples:spring-petclinic:2.0.0 (/home/rakesh_pal/spring-petclinic/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.springframework.samples:spring-petclinic:2.0.0: Could not find artifact org.springframework.boot:spring-boot-starter-paren
t:pom:2.0.0.BUILD-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 10, column 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by joaoandremartins** [comment]
Couldn't reproduce.
Please start from the beginning and make sure you're not skipping any steps.
Thanks!

**Comment by meteatamel** [comment]
Tested the codelab and it work. Please reopen if you still see the issue.
