### ISSUE TITLE
[Simulating a Thread network using OpenThread]: Set up the build system - missing step

### ISSUE THREAD

**Issue by sc1ent** [googlecodelabs/feedback#336]
In the [Simulating a Thread network using OpenThread](https://codelabs.developers.google.com/codelabs/openthread-simulation/#1) in *Step 2. Set up the build system*, there are clear instructions for downloading and installing Virtual Box and Vagrant on a Windows and Mac. After that you jump to a step on cloning a git repository.  It is not immediately obvious that you need to have git installed as its not installed by default on Windows. It would be nice to call that out.

**Comment by Vyrastas** [comment]
Hi @sc1ent thanks for letting us know.  I made an update to Step 2 based on your feedback.
