### ISSUE TITLE
[cloud-hello-istio]:

### ISSUE THREAD

**Issue by tsadoklf** [googlecodelabs/feedback#343]
Step 4 "Installing Istio" could not be completed becauase the file "install/kubernetes/istio-initializer.yaml" is missing.

**Comment by kenthua** [comment]
Workaround here: https://github.com/googlecodelabs/feedback/issues/350

**Comment by alexismp** [comment]
A new version of the codelab was recently pushed out, updating to Istio 0.5.1

**Comment by meteatamel** [comment]
This bug is not relevant anymore as the instructions are different now. Closing.
