### ISSUE TITLE
[cloud-app-engine-aspnetcore]: gcloud app deploy fails

### ISSUE THREAD

**Issue by bgrainger** [googlecodelabs/feedback#344]
I ran `gcloud app deploy  --version v0` as instructed in [step 7](https://codelabs.developers.google.com/codelabs/cloud-app-engine-aspnetcore/#6). It failed with the following error:

```
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
Error:
  An assembly specified in the application dependencies manifest (HelloWorldAspNetCore.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Mvc.Abstractions', version: '2.0.2'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Abstractions.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.5.xml
```

I applied the workaround from dotnet/coreclr#13542, specifically, adding the following to `HelloWorldAspNetCore.csproj`:

```
<PropertyGroup>
  <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
</PropertyGroup>
```

This allowed the application to be published. Not sure if this is related to the installed SDK version GoogleCloudPlatform/aspnet-docker#84.

**Comment by meteatamel** [comment]
Sorry for the delay in realizing this bug. This shouldn't be an issue anymore. Can you try again and let us know if you still see the issue?

**Comment by meteatamel** [comment]
Closing. Please re-open if you still see the issue.

**Comment by bgrainger** [comment]
I missed your earlier message. I haven't noticed any problems with `gcloud app deploy` recently.
