### ISSUE TITLE
[cloud-app-engine-aspnetcore]:

### ISSUE THREAD

**Issue by mjlietzke** [googlecodelabs/feedback#347]
Currently, with the 2.0 library installed, there are issues when you go to publish stating that you do not have the requisite libs installed:

Updating service [default] (this may take several minutes)...failed.
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
Error:
  An assembly specified in the application dependencies manifest (HelloWorldAspNetCore.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Mvc.Abstractions', version: '2.0.2'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Abstractions.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.5.xml

This will occur due the targets referenced in the manifest not matching the ones on the target system. See Implicit store for more details on why this happens [1]. This can occur when only the runtime and not the full sdk are installed on a host, and you have the need for  an installed lib in the manifest that you do not have. The easiest fix is outlined in the article, and that is to add the following to your project file:

<PropertyGroup>
  <PublishWithAspNetCoreTargetManifest>false</PublishWithAspNetCoreTargetManifest>
</PropertyGroup>

To produce this issue, simply follow the instructions verbatim. You will now see this issue in the cloud console.

[1] https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store#aspnet-core-implicit-store

**Comment by meteatamel** [comment]
Sorry for the delay in realizing this bug. This shouldn't be an issue anymore. Can you try again and let us know if you still see the issue?

**Comment by meteatamel** [comment]
Closing. Please re-open if you still see the issue.
