### ISSUE TITLE
[cloud-app-engine-aspnetcore]:

### ISSUE THREAD

**Issue by ElcioMello** [googlecodelabs/feedback#349]
Hello,

I was following the tutorial for the asp.net core with google app engine and on the step 7 (deploy the app) after I type the command "gcloud app deploy --version v0" at the end of the process the console shows me the folowing error:

Updating service [default] (this may take several minutes)...failed.
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:
Error:
  An assembly specified in the application dependencies manifest (HelloWorldAspNetCore.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Mvc.Abstractions', version: '2.0.2'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Abstractions.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.5.xml

After studdy a little I came with 2 solutions:
1 - Include PublishWithAspNetCoreTargetManifest as false into my .csproj. But this bring all my dependencies to de Release folder
2 - Change the version of the component Microsoft.AspNetCore.Mvc.Abstractions on the HelloWorldAspNetCore.deps.json file to the version 2.0.0

I find the solution 2 better and I Think that the problem is because my container instance does not have the latest version of the component Microsoft.AspNetCore.Mvc.Abstractions or on the deploy process something happens and my instance can't download the dependencies da versão 2.0.2(that is the default version whe you create a new dotnet razor project)

Can you guys check the tutorial and see what's causing the error  :)?

Tanks :)

Current versions:

"dotnet --version" command:
2.1.4

"gcloud info" command:
Google Cloud SDK [187.0.0]

Platform: [Linux, x86_64] ('Linux', 'cs-6000-devshell-vm-6b21c629-947b-4b49-b32b-a7f2587817c2', '3.16.0-5-amd64', '#1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08)', 'x86_64', '')
Python Version: [2.7.13 (default, Nov 24 2017, 17:33:09)  [GCC 6.3.0 20170516]]
Python Location: [/usr/bin/python2]
Site Packages: [Disabled]

Installation Root: [/google/google-cloud-sdk]
Installed Components:
  kubectl: []
  app-engine-python: [1.9.66]
  pubsub-emulator: [2017.09.15]
  core: [2018.01.28]
  app-engine-java: [1.9.61]
  datalab: [20180119]
  app-engine-php: [ ]
  docker-credential-gcr: []
  app-engine-python-extras: [1.9.63]
  beta: [2017.09.15]
  gsutil: [4.28]
  cloud-datastore-emulator: [1.4.0]
  cbt: []
  alpha: [2017.09.15]
  gcd-emulator: [v1beta3-1.0.0]
  app-engine-go: []
  bq: [2.0.28]
Python PATH: [/google/google-cloud-sdk/lib/third_party:/google/google-cloud-sdk/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload]
Cloud SDK on PATH: [True]
Kubectl on PATH: [/google/google-cloud-sdk/bin/kubectl]

**Comment by meteatamel** [comment]
Sorry for the delay in realizing this bug. This shouldn't be an issue anymore. Can you try again and let us know if you still see the issue?

**Comment by meteatamel** [comment]
Closing it. Please re-open if you still see the issue.
