### ISSUE TITLE
Small Typo in PWA with Firebase, Polymerfire and Polymer

### ISSUE THREAD

**Issue by Giymo11** [googlecodelabs/feedback#35]
First of all, great work on the this tutorial!

I found a small typo: On slide [18](https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/index.html?index=..%2F..%2Findex#17), it says:

> To add it to our app, append the following HTML to the `<template>` in `public/note-app.html`:

However, you would want to append it after the element you added before (in this case `<na-login>`), as to add it as a child to the template. 

Had me confused for a second.

**Comment by x1ddos** [comment]
@robdodson and/or @cdata can you guys please take a look.

**Comment by cdata** [comment]
@crhym3 could you please assign issues related to this code lab to me? Thanks!

**Comment by cdata** [comment]
@Giymo11 Could you clarify what the confusion was for you? Is it unclear that you were meant to append to the inside of the `<template>`?

**Comment by Giymo11** [comment]
@cdata I was not sure if that meant I should add it _inside_ the template (as a child) or _after_ the template (as a sibling). Maybe this is because I am not a native english speaker, but then, so are many others too. So I thought I'd simply let you know and have you decide, if that's something that should be changed.

**Comment by cdata** [comment]
@Giymo11 thanks for the clarification. I'll improve the language to make it more explicit.

**Comment by x1ddos** [comment]
@cdata will do. need to add you to this googlecodelabs org first.
