### ISSUE TITLE
[cloud-hello-istio]: Section 5 - istio-egress service and pods no longer referenced

### ISSUE THREAD

**Issue by kenthua** [googlecodelabs/feedback#353]
To avoid installation verification confusion, istio-egress is no longer [used or referenced](https://github.com/istio/istio/pull/1202).  Should remove the reference in the outputs.

**Comment by alexismp** [comment]
Thanks for reporting this.
This should now be fixed with a new codelab update that was recently pushed.
Can you check?

**Comment by meteatamel** [comment]
I checked the outputs and they reflect the current state, so this bug is irrelevant now. Closing it.
