### ISSUE TITLE
[cloud-hello-istio]: Don't see Istio-Egress after installing istio-auth

### ISSUE THREAD

**Issue by panywei** [googlecodelabs/feedback#355]
I am following the instruction of Istio codelab, and at step 4. Installing Istio

$ kubectl apply -f install/kubernetes/istio-auth.yaml
$ kubectl get pods --all-namespaces
NAMESPACE      NAME                                                    READY     STATUS    RESTARTS   AGE
istio-system   istio-ca-2330594145-5lk2g                               1/1       Running   0          55s
istio-system   istio-ingress-2386781476-2ct5w                          1/1       Running   0          56s
istio-system   istio-mixer-1038678341-w8r29                            3/3       Running   0          1m
istio-system   istio-pilot-2673024744-2c7cn                            2/2       Running   0          56s

Don't see Istio-Egress as mentioned in the instruction.

**Comment by alexismp** [comment]
Thanks for reporting this.
This should now be fixed with a new codelab update that was recently pushed.
Can you check?

**Comment by meteatamel** [comment]
I checked and it's fixed. Closing.
