### ISSUE TITLE
[cloud-app-engine-springboot]: Step 8 code snippet & instructions are different commands

### ISSUE THREAD

**Issue by noahdietz** [googlecodelabs/feedback#356]
On step 8, "Deploying the Application into App Engine", where the reader should be deploying their application, the second code snippet uses the `appengine:update` goal, while the instruction right above it says to use `appengine:deploy`. Which one are we using?

Furthermore, the output in the code snippet following the `appengine:update` isn't all that helpful, it just includes the auth'n flow, but none of the expected output from a successful deployment. 

Lastly, the note immediately following this code snippet warns the user of the long first time deployments of the Flex environment, when this tutorial is about App Engine Standard. Not sure if I'm missing something or not, but I had to double take the tutorial I was on. 

Thanks!

**Comment by meteatamel** [comment]
Not relevant anymore in the latest codelab.
