### ISSUE TITLE
[cloud-hello-istio]: cannot find `Istio-Initializer` in designated path

### ISSUE THREAD

**Issue by kuma** [googlecodelabs/feedback#359]
At the end of section 4, `install/kubernetes/istio-initializer.yaml` seems missing in designated path in istio 0.5.1.

**Comment by alexismp** [comment]
Thanks for reporting this.
This should now be fixed with a new codelab update that was recently pushed.
Can you check?

**Comment by meteatamel** [comment]
Checked and it's fixed. Closing.
