### ISSUE TITLE
Missing line from code sample in Polymerfire code lab

### ISSUE THREAD

**Issue by hubgit** [googlecodelabs/feedback#36]
The second code block in section 16 of "[Build a Progressive Web App with Firebase, Polymerfire and Polymer Components](https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/)" is missing a line from the previous block:

``` html
<link rel="import" href="bower_components/app-storage/app-indexeddb-mirror/app-indexeddb-mirror.html">
```

**Comment by x1ddos** [comment]
@robdodson and/or @cdata can you guys please take a look.

**Comment by cdata** [comment]
Thanks for reporting, I'll take a look.

**Comment by cdata** [comment]
Yup, looks like it was missing. I've updated the code lab and it should be re-published shortly.
