### ISSUE TITLE
[cloud-hello-istio]:

### ISSUE THREAD

**Issue by leighawilliamson** [googlecodelabs/feedback#366]
Regarding the hello istio cloud lab step 4, I ran the curl command to get the latest istio code from the git repo but the install/kubernetes folder that resulted did not contain an istio-initializer.yaml file so the last instruction in step 4 (kubectl apply -f install/kubernetes/istio-initializer.yaml) failed.

I am attempting to soldier on with the lab using mixed instructions from https://istio.io/docs/setup/kubernetes/quick-start.html and the application information from the cloud lab, but wanted to mention this mismatch with the git repo.

**Comment by alexismp** [comment]
This should now be fixed with the codelab now updated to Istio 0.5.1
