### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by pabloki** [googlecodelabs/feedback#368]
Step 8 from [codelab](https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..%2Findex#7) "Deploy Spring Boot Application into AppEngine"  , `mvn appengine:deploy`  . I think deploy it's not a goal for appengine maven plugin.

**Comment by saturnism** [comment]
this should've been fixed a while back. also recently updated w/ the new java11 runtime w/ JAR deployment. PTAL. Thanks!
https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..spring#0
