### ISSUE TITLE
Build a Progressive Web App with Firebase, Polymerfire and Polymer Components

### ISSUE THREAD

**Issue by radumro** [googlecodelabs/feedback#37]
The application it's working fine on the development computer but not if it's accesed from the network.

if i acces the app from the network using the ip of the server and not the localhost the auth is not working.

for this to work i had to go to firebase>auth>sign in method OAuth domains and add the ip

please specify this step in the code lab for people using firebase for the first time

thanks

**Comment by cdata** [comment]
Hi @radumro . I'm considering adding this, but frankly I'm on the fence. There is a lot of Firebase-specific knowledge that is expected of you already, and this code lab is not meant to be an extensive tutorial of either Firebase or Polymer specifically.

**Comment by radumro** [comment]
it was just a sugestion. I faced this problem and i think it's was a good place to point a user into the right direction. it's up to you then
thanks for all your help
