### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by wilsonferro** [googlecodelabs/feedback#375]
Need to put this in pom.xml (for "./mvnw -DskipTests appengine:devserver" starts succesfull):
```
<build>
    <plugins>
        <plugin>
            <groupId>com.google.appengine</groupId>
            <artifactId>appengine-maven-plugin</artifactId>
            <version>1.9.60</version>
        </plugin>
    </plugins>
</build>

```
Source: https://stackoverflow.com/questions/25512591/plugin-not-found-for-prefix-app-engine-when-using-maven

**Comment by meteatamel** [comment]
Fixed in the latest update.
