### ISSUE TITLE
[cloud-spring-cloud-gcp-gcs]:

### ISSUE THREAD

**Issue by hshang09** [googlecodelabs/feedback#376]
Met error in reading cloud storage:
java.io.FileNotFoundException: Could not open ServletContext resource [/gs://gmstorage/art1.jpeg]

The file in the bucket is public shared.

**Comment by joaoandremartins** [comment]
@hshang09 Spring is trying to read that as a servlet resource, so you probably forgot to add the storage dependency.

```
        <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-gcp-starter-storage</artifactId>
        </dependency>
```

**Comment by ghost** [comment]
> @hshang09 Spring is trying to read that as a servlet resource, so you probably forgot to add the storage dependency.
> 
> ```
>         <dependency>
>                 <groupId>org.springframework.cloud</groupId>
>                 <artifactId>spring-cloud-gcp-starter-storage</artifactId>
>         </dependency>
> ```

Hi, I know this is a old issue, but i'm having the same problem, even though I have the dependency in my pom.xml. Here's what I've done:

Started the project from start.spring.io with gcp-storage, spring security, spring data and spring web.
Followed step by step the codelab availble in https://codelabs.developers.google.com/codelabs/spring-cloud-gcp-gcs/index.html#0 .

I still have this error like the gs protocol isn't being recognized. Is there anything else I should do?

**Comment by hshang09** [comment]
@RafaelPradoLima 
I used another way to access GCS files. It's not relying on the spring stuff. Just java apis provided by GCS.

High level ideas are like below.

import com.google.cloud.storage.*;
Storage storage = StorageOptions.newBuilder().setCredentials(credentials).build().getService();
BlobId blobId = BlobId.of(bucketName, filePath);
Blob blob = storage.get(blobId);

Hope it helps.

**Comment by hshang09** [comment]
@joaoandremartins 
Thanks for your reply. My bad I missed that months ago until today.

**Comment by chanseokoh** [comment]
The dependency mentioned in https://github.com/googlecodelabs/feedback/issues/376#issuecomment-389649774 is an [old one](https://github.com/spring-cloud/spring-cloud-gcp#repo-has-moved):

> This repository contains code for Spring Cloud GCP 1.2.x and below. Future work will be in our new repo, GoogleCloudPlatform/spring-cloud-gcp](https://github.com/GoogleCloudPlatform/spring-cloud-gcp).

By now, most likely you should use
```xml
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-storage</artifactId>
        </dependency>
```

**Comment by meteatamel** [comment]
Updated the codelab and tested that it works. Closing this issue.
