### ISSUE TITLE
[cloud-vision-intro]:

### ISSUE THREAD

**Issue by mdmalik** [googlecodelabs/feedback#379]
Its not a bug. 
A system should ask for a Survey at the end of a the steps.

In [this](codelabs.developers.google.com/codelabs/cloud-vision-intro/index.html) you are asking for survey like "How would rate your experience with Google Cloud Platform?" in Step #2
Should we complete the tutorial and then ask for Survey?

Again its not a bug :)

**Comment by PicardParis** [comment]
- Thank you for your feedback.
- The quick survey is at the beginning on purpose, to know your experience with GCP before you start the codelab.
