### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by pkonigsberg** [googlecodelabs/feedback#391]
I am not sure why I get a 401 Unauthorized response despite having key-values:
Content-Type application/json
Authorization Bearer <my access token>

These key-values were successful in bringing back a json full of the structure data so I am not sure why a subsequent request of 
https://developer-api.nest.com/devices/thermostats/<my-device-id>/device_id
gets a 401 Unauthorized response.

**Comment by hostirosti** [comment]
Hi pkonigsberg,

thank you for your feedback. Can you post the link to the codelab here and the which step?

**Comment by pkonigsberg** [comment]
Hi there. I'm doing the Quick Start codelab and am on step #5 Read from the API
https://codelabs.developers.google.com/codelabs/wwn-api-quickstart/#5
I was able to get the first part done where I can see the structures and devices. So I'm not sure why I wouldn't be authorized to run and API read command like the humidity example or even just the device_id command?

**Comment by Vyrastas** [comment]
@pkonigsberg Can you confirm the actual URL you made the unauthorized request to?  Is it actually what you put in the first comment?:

`https://developer-api.nest.com/devices/thermostats//device_id`

If so, that's an invalid URL in the API (two forward slashes and device_id is not a field).

After `thermostats` you'd put the actual `device_id` value you got from your initial successful call.  So if the `device_id` is `4zWYGlpfn0bwluRlV-adbawOEGhwC6HI` then the endpoint to call is:

`https://developer-api.nest.com/devices/thermostats/4zWYGlpfn0bwluRlV-adbawOEGhwC6HI/`

**Comment by pkonigsberg** [comment]
Yes I had my actual device id in the url. I didn’t think it was safe to post the device id on the internet.

**Comment by Vyrastas** [comment]
Ok, is your call successful when you use `https://developer-api.nest.com/devices/thermostats`?

**Comment by pkonigsberg** [comment]
No I get a 401 Unauthorized on that URL as well.

**Comment by Vyrastas** [comment]
Then it's either due to a [redirect](https://developers.nest.com/documentation/cloud/how-to-handle-redirects) or you simply need to reauthorize the connection.

If you're using Postman per the Codelab, it should be handling redirects for you, and you'll have to reauthorize the connection.  As for why that happened I couldn't say, it shouldn't just deauthorize something for no reason.

**Comment by pkonigsberg** [comment]
Yes I am using Postman. So repeat this step? :
https://codelabs.developers.google.com/codelabs/wwn-api-quickstart/#4

**Comment by Vyrastas** [comment]
Yes, get a new access token then try making API GET calls again.

**Comment by pkonigsberg** [comment]
OK I ran the POST to https://api.home.nest.com/oauth2/access_token
with my client_id, client_secret, code and grant_type authorization_code in the Body.
This is what I got back:
{
    "error": "oauth2_error",
    "error_description": "authorization code not found",
    "instance_id": "2167ff4f-5f02-4b12-a9d2-c501ce9f5629"
}

**Comment by Vyrastas** [comment]
Are you using the correct PIN in the `code` field?  A new PIN is required each time you authorize a connection, even for re-auth.

https://developers.nest.com/documentation/cloud/authorization-reference#authorization_code_not_found

**Comment by pkonigsberg** [comment]
Thank you. I got a new pin which gave me a new authorization code which I put in after "Bearer " in the Authorization Key value and ran 
https://api.home.nest.com/oauth2/access_token as a GET and got 
{
    "url": "/oauth2/access_token",
    "message": "404 Not Found"
}
and running it as a POST I got
{
    "error": "oauth2_error",
    "error_description": "authorization code not found",
    "instance_id": "7ec7e993-dab8-49b0-bcc4-9e68257ae6c5"
}

**Comment by pkonigsberg** [comment]
I ran through the exercise again and got a new pin and a new Bearer authorization code. 
I still get a 401 Unauthorized when I try to GET a thermostat device_id or locale (pretty innocuous requests I thought) but when I try to do it as a POST I get "error : Invalid content sent" and 400 Bad Request. Not sure if that helps explain what's going on or not.

**Comment by Vyrastas** [comment]
To be honest I'm not sure how to help you any further without actually watching you go through it. If you follow the instructions in the Codelab straight through exactly as written it should work (I just tried it myself).

I can only say make sure to use the right values for the right call, make sure they pasted correctly in Postman (not truncated), and use the right type of call - i.e. a GET for an access token, a GET for reading the API, a POST for changing a field in the API.  These are different types of calls which are all detailed in the Codelab.

**Comment by pkonigsberg** [comment]
I'm not using a simulated Nest thermostat. I'm using my actual thermostat in my house. Is that the issue? Maybe this codelab is only for the simulated devices?
    On Friday, April 13, 2018, 12:37:01 PM EDT, Jeff Bumgardner <notifications@github.com> wrote:  
 
 
To be honest I'm not sure how to help without watching you go through it. If you follow the instructions in the Codelab straight through exactly as written it should work (I just tried it myself).

I can only say make sure to use the right values for the right call, make sure they pasted correctly in Postman (not truncated), and use the right type of call - i.e. a GET for an access token, a GET for reading the API, a POST for changing a field in the API. These are different types of calls which are all detailed in the Codelab.

**Comment by Vyrastas** [comment]
It should work the same, just make sure when you use the authorization URL to get the PIN, that you are logged into the same nest.com account that contains your physical thermostat.  So like on this screen after pasting the authorization URL in a browser:

https://developers.nest.com/documentation/cloud/authorization-overview#nest_permissions

Whatever email is logged in (top right of that screen) is the Nest account you are authorizing API access for.

**Comment by pkonigsberg** [comment]
I double checked that I am logged in to the developer console with the same email address as my Nest account is registered with devices. (It's the address I get the monthly Nest home reports on.)
When you make a GET call when requesting from real devices should the URL still be developer-api.nest.com? Or is that only for testing? Maybe it should be api.nest.com ?
Also, is it acceptable to still have the same Content-Type and Authorization variables in the GET request as we did to get the original structure data? Lastly, I think I also left the data from the prior POST request in the Body tab. Is that ok? Still trying to figure out why none of this works.... Thanks!

**Comment by hostirosti** [comment]
Can you try the codelab with a simulated device? Does that work? Are there any settings in the nest account for your real device to allow / deny api access?

**Comment by Vyrastas** [comment]
It works the same whether the device is real or simulated.

Unfortunately I don't know how else I can help.  The process to access the API described in the Codelab works if followed exactly as written.

EDIT: The only other thing I can think of is your internet network is blocking some port related to the call, perhaps in a redirect (most calls to the API are redirected).

Also, we have a developer forum that might be better suited for a longer conversation: https://nestdevelopers.io/

**Comment by pkonigsberg** [comment]
I solved this issue and thought I would post the solution here for anyone else who might be looking / wondering. Somewhere in the creation process of the "Works With Nest" product on the Nest site I put the app in the camera category. Therefore only the camera API functions can be accessed with my authorization through this app. That's why the example CodeLab calls with thermostats were returning unauthorized.

**Comment by Vyrastas** [comment]
Ah!  It makes sense now why the root endpoint was working but not the thermostat one, I didn't even think about permissions.  Glad to hear you figured out the issue.

This scenario should be in the documentation for the Unauthorized error code, I'll get that added.

**Comment by pkonigsberg** [comment]
Hi Jeff. I was wondering if I could ask a more generic Nest programming question.In trying to log in via python code the sample code from the Nest - 10 Tips for Success code seems to get a token with an authorization_code variable.I can't seem to find what value this variable should have or where it comes from.Hopefully it isn't the Pin code from the Postman examples because that required a user log into the Nest web site and read off a pin code...
Thank you,Paul

    On Wednesday, April 18, 2018, 11:45:06 AM EDT, Jeff Bumgardner <notifications@github.com> wrote:  
 
 
Ah! It makes sense now why the root endpoint was working but not the thermostat one, I didn't even think about permissions. Glad to hear you figured out the issue.

This scenario should be in the documentation for the Unauthorized error code, I'll get that added.

**Comment by Vyrastas** [comment]
@pkonigsberg If you're following this Codelab:
https://codelabs.developers.google.com/codelabs/nest-ten-tips-for-success/index.html?index=..%2F..%2Findex#0

Which uses that code, then you shouldn't need to know what the `authorization_code` is, it'll store and use it behind the scenes once you authorize the connection.  If you follow the directions in the accompanying Codelab it should work.  

If you're still having problems can you please log it as a new issue on the [nest-python repo](https://github.com/nestlabs/nest-python/issues), instead of here?  This older issue should have been closed.
