### ISSUE TITLE
[cloud-hello-istio]:

### ISSUE THREAD

**Issue by yuriylesyuk** [googlecodelabs/feedback#396]
The step in 3. Setup your Kubernetes/GKE cluster does not work anymore:

$ gcloud container clusters create hello-istio     --cluster-version=1.9.2-gke.1
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Version "1.9.2-gke.1" is invalid.

The 1.9.4-gke.1 is required now.

**Comment by hungnt-me** [comment]
I'm facing the same issue

```
gcloud.container.clusters.create) ResponseError: code=400, message=Version "1.9.4-gke.1" is invalid.
```

**Comment by hungnt-me** [comment]
https://cloud.google.com/kubernetes-engine/release-notes

**Comment by meteatamel** [comment]
Instructions changed and this bug is not relevant anymore.
