### ISSUE TITLE
[cloud-mongodb-statefulset]:

### ISSUE THREAD

**Issue by koolhandluke** [googlecodelabs/feedback#398]
After running:
curl -O https://storage.googleapis.com/kubernetes-release/release/v1.5.2/kubernetes-client-linux-amd64.tar.gz && \
  tar -xzvf kubernetes-client-linux-amd64.tar.gz && \
  sudo cp kubernetes/client/bin/kubefed /usr/local/bin && \
  sudo chmod +x /usr/local/bin/kubefed

I am unable to run /usr/local/bin/kubefed. 
"/usr/local/bin/kubefed: cannot execute binary file"

- I tries running as root
- I tried v1.8.6
- FYI , I also tried the run the kubectl in the same tar download and had the same issue. Although the kubectl isntalled prev using  "gcloud components install" works.

**Comment by AKIvan** [comment]
Any news on this, i have the same issue.

**Comment by koolhandluke** [comment]
sorry. forgot what I did as a workaround. it was 9 months ago.
