### ISSUE TITLE
gcloud container clusters create guestbook --num-nodes 2 returns error

### ISSUE THREAD

**Issue by pauhlbarnes** [googlecodelabs/feedback#4]
running gcloud container clusters create guestbook --num-nodes 2 returns an error

error validating "redis-pod.yaml": error validating data: found invalid field metadata for v1.PodSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by x1ddos** [comment]
@pauhlbarnes which codelab is this, can you post the link to it?

**Comment by hostirosti** [comment]
This should be fixed in https://codelabs.developers.google.com/codelabs/cloud-compute-kubernetes. Please reopen if the bug still exists.
