### ISSUE TITLE
The buton do not exists

### ISSUE THREAD

**Issue by bharatiadkar** [googlecodelabs/feedback#40]
Click the Run/Debug Configuration, and select . Android Studio auto-generates this  

The button in the text do not exist in the Android Studio 2.2.

Please update the tutorial to use the Toolbar command instead.

**Comment by x1ddos** [comment]
@bharatiadkar which codelab are you referring to. Can you post a link here.
Thanks.

**Comment by bharatiadkar** [comment]
https://codelabs.developers.google.com/codelabs/android-studio-jni/index.html?index=..%2F..%2Findex#5

**Comment by ggfan** [comment]
done, will be there in the next update. thanks
