### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by dinakaranonline** [googlecodelabs/feedback#417]
**Failed at Step 8 : deploy your application into App Engine environment, run mvn appengine:deploy:** 

**Logs**

INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.861 s
[INFO] Finished at: 2018-05-07T22:19:27+05:30
[INFO] Final Memory: 10M/27M
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'deploy' in plugin com.google.appengine:appengine-maven-plugin:1.9.60 among available goals backends_configure, backends_delete, backends_rollb
ack, backends_start, backends_stop, backends_update, create-property, debug, devserver, devserver_start, devserver_stop, endpoints_get_client_lib, endpoints_get_discovery_
doc, endpoints_get_swagger_doc, enhance, migrate_traffic, rollback, set_default_version, start_module_version, stop_module_version, update, update_cron, update_dispatch, u
pdate_dos, update_indexes, update_queues, vacuum_indexes -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException

**Comment by Sygyzmundovych** [comment]
Seems like you are using deprecated Google plugin. Please see https://cloud.google.com/appengine/docs/standard/java/tools/maven and the link to the new documentation there.

**Comment by meteatamel** [comment]
Tested the latest codelab and everything worked for me.
