### ISSUE TITLE
[cloud-springboot-kubernetes]: Cleanup section does not exist

### ISSUE THREAD

**Issue by jaypatel512** [googlecodelabs/feedback#419]
As per the docs, it says there is a cleanup section later to make sure you do not keep this kubernetes cluster running. However, I did not find a way to clean it up. Also, this could easily be the last section of the Summary/Congratulations.

![image](https://user-images.githubusercontent.com/1309895/40025509-6e0fe87a-5797-11e8-9716-7a6ce074ce0c.png)

**Comment by meteatamel** [comment]
There's a cleanup section in the last step.
