### ISSUE TITLE
This is request to add information to JNI tutorial

### ISSUE THREAD

**Issue by bharatiadkar** [googlecodelabs/feedback#42]
Hi,

Please can you add to this tutorial how to add an external compiled libXYZ.so to the app in the Android Studio. Where hello-android-jni.c now in turn calls functions from a C library.

I am trying to figure how to do this, The app build but add runtime it cannot find the library.

Thanks.

**Comment by bharatiadkar** [comment]
Please can you post a small single page help to show how to add precompiled C library to hello jni project.

**Comment by ggfan** [comment]
https://github.com/googlesamples/android-ndk, project hello-libs:
 follow the app/build.gradle, 2 shared libs are used there with detailed comment

see if you could use that one.  If you want to use cmake plugin, it is in master-cmake branch [the same sample name ]

**Comment by bharatiadkar** [comment]
Hi,
This example that you are pointing to has the source and header file included in the project. I don't have the source for the library, I just have the .so and the header. 
How do set up the build.gradle file for this scenario. 

Thanks,
Bharati

**Comment by ggfan** [comment]
pretty much you could ignore the building the shared lib part, just look at the app: how the shared lib is used. that will get you going for sure -- 
 only look at the app/build.gradle,  and pointing to your local directory hosting your shared lib(s). that is all  needed

3 things there:
   1) declare a lib as import and tell where the location of the real *.so file; and also the header file
   2) add you declared lib as jni dependency
   3) add it into the jniLibs so it will be packed into APK and send to target for loading

that does the trick.  For API level earlier than 18, you will need manually load all of the shared lib in the right sequence in your Java code ( It may be a bug back then); newer API, no need to worry I think. 

the libs sample demo how to produce AND consume shared lib, they are 2 independent things; just to save the space.

if you meet problems, you could post issues there [it should work].

**Comment by ggfan** [comment]
closing down this, it should work. you could re-open it if it does not work.  thanks
