### ISSUE TITLE
[cloud-spring-petclinic-cloudsql]:

### ISSUE THREAD

**Issue by iolalla** [googlecodelabs/feedback#427]
Hi,

I've repeated the codelab and I've found two minor bugs:
- In Step 5, after modifying the pom.xml as suggested I got this error:
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.scope' for org.springframework.cloud:spring-cloud-gcp-dependencies:pom must be one of [provided, compile, runtime, test, system] but is 'import'. @ line 117, column 18
[ERROR] 'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-gcp-starter-sql-mysql:jar is missing. @ line 121, column 19
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.springframework.samples:spring-petclinic:2.0.0.BUILD-SNAPSHOT (/home/iolalla/src/spring-petclinic/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-gcp-starter-sql-mysql:jar is missing. @ line 121, column 19
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
------------------------------------------------------------------------------------------------------------------------
In order to solve it I modified the pom to add runtime instead of import:
     
     <dependency>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-gcp-dependencies</artifactId>
          <version>1.0.0.M3</version>
          <type>pom</type>
          <scope>runtime</scope>
      </dependency>

Then after this I needed to rerun the dependencies with the command, cause I was getting this error "[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-gcp-starter-sql-mysql:jar is missing. @ line 121, column 19" :

$ mvn dependency:resolve

and then finally:
$./mvnw spring-boot:run

And now with the changes every run smoothly.

**Comment by meteatamel** [comment]
Tested and it works. Please reopen if you still see the issue.
