### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by zevt** [googlecodelabs/feedback#429]
I follow this sample how to deploy a springboot application on google app engine standard
https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..%2Findex#6
At step 7 I found this error:

INFO] java.lang.NullPointerException
[INFO]  at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:947)
[INFO]  at org.eclipse.jetty.annotations.ClassInheritanceHandler.addToInheritanceMap(ClassInheritanceHandler.java:72)
[INFO]  at org.eclipse.jetty.annotations.ClassInheritanceHandler.handle(ClassInheritanceHandler.java:58)
[INFO]  at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.visit(AnnotationParser.java:476)
[INFO]  at org.objectweb.asm.ClassReader.accept(ClassReader.java:650)
[INFO]  at org.objectweb.asm.ClassReader.accept(ClassReader.java:525)
[INFO]  at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:978)
[INFO]  at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:958)
[INFO]  at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:902)
[INFO]  at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
[INFO]  at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
[INFO]  at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:546)
[INFO]  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
[INFO]  at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
[INFO]  at java.base/java.lang.Thread.run(Thread.java:844)
[INFO] 2018-05-27 02:23:54.211:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=673ms
[INFO] May 27, 2018 7:23:54 AM com.google.appengine.tools.development.ApiProxyLocalImpl log
[INFO] INFO: javax.servlet.ServletContext log: 1 Spring WebApplicationInitializers detected on classpath

**Comment by kamuie** [comment]
got the same issue, did you manage how to solve?

**Comment by saturnism** [comment]
that is pretty weird :/ i've updated the code lab to use JAR deployment in the java11 runtime (beta).
PTAL if same issue persists. https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..spring#0
