### ISSUE TITLE
touch not found: Build a Progressive Web App with Firebase, Polymerfire and Polymer Components

### ISSUE THREAD

**Issue by peterennisrda** [googlecodelabs/feedback#43]
Windows 7
Using cmd as shell
touch not found
![capture3876](https://cloud.githubusercontent.com/assets/1280523/16100613/621d4868-3314-11e6-94ee-ae7bc710d387.png)

**Comment by peterennisrda** [comment]
Windows does not have a touch command. Use:

type NUL > public/manifest.json

**Comment by cdata** [comment]
Thanks for reporting! I've added a note about this in the code lab so that future Windows users will be aware of what to do.
