### ISSUE TITLE
[cloud-vision-api-python]:

### ISSUE THREAD

**Issue by selmon1** [googlecodelabs/feedback#430]
"5. Start Interactive Python
In this codelab, we'll use an interactive Python interpreter called iPython. Start a session by running `iPython` in the cloud shell. This command runs the Python interpreter in an interactive Read, Eval, Print, Loop (REPL) session."

`ipython` (lowercase p) had to be entered in to initiate the interpreter.

**Comment by PicardParis** [comment]
This was fixed a few months ago. Closing this issue...
