### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by nishesh** [googlecodelabs/feedback#433]
On Page 8 here:
https://codelabs.developers.google.com/codelabs/cloud-slack-bot/index.html#8
It mentions to use 
gcloud docker -- push gcr.io/${PROJECT_ID}/slack-codelab:v1

However running this command shows a message about gcloud docker use being deprecated. Can this page be updated with the correct supported command?

**Comment by tswast** [comment]
You're correct. The new commands are documented at https://cloud.google.com/container-registry/docs/pushing-and-pulling

Authorize docker
```
gcloud auth configure-docker
```

Then use
```
docker push gcr.io/${PROJECT_ID}/slack-codelab:v1
```
to upload.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
