### ISSUE TITLE
[cloud-spring-cloud-gcp-gcs]:

### ISSUE THREAD

**Issue by ericsawler** [googlecodelabs/feedback#437]
Running the codelab sample throws a file io exception:
java.io.FileNotFoundException: class path resource [gs://ericstest/my-file.txt] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
gsutil can see the file, and it shows in the console storage browser.

**Comment by meteatamel** [comment]
Updated the codelab and tested that it works. Closing this issue.
