### ISSUE TITLE
[cloud-speech-intro]: confusing curl command

### ISSUE THREAD

**Issue by deadkennedy-90210** [googlecodelabs/feedback#438]
Please excuse me if I'm using the terms incorrectly (I've migrated to a Linux environment and still getting use to it).

Nothing seems to happen when I execute the curl command in Step 8. Call the Speech API. I'm unsure whether I've typed in properly, and so I'm not sure whether it's:

curl -s -X POST -H "Content-Type: application/json" --data-binary @request.json \"https://speech.googleapis.com/v1beta1/speech:syncrecognize?key=${API_KEY}"
OR
curl -s -X POST -H "Content-Type: application/json" --data-binary @request.json \ "https://speech.googleapis.com/v1beta1/speech:syncrecognize?key=${API_KEY}"

With the former command, I just get the normal shell(?) response:
[username]@[projectname]:~$_
And with the latter command, it seems to go into bash(?):
>_

It would also be great to make the sentence, "Your response should look something like...", less ambiguous, because I initially thought that the below was what I should be responding with, which obviously doesn't make sense. A screen shot of what the shell should look like when I execute the curl command would be helpful too.

Thanks!

**Comment by alexismp** [comment]
Thanks for the report.
The \ character indicates that the command carries over to the next line. The on-liner looks like this : 

`curl -s -X POST -H "Content-Type: application/json" --data-binary @request.json "https://speech.googleapis.com/v1/speech:recognize?key=${API_KEY}"`

... where `${API_KEY}` is replaced by the key generated in step 6

I've slightly edited the sentence.
