### ISSUE TITLE
Create Hello-JNI with Android Studio

### ISSUE THREAD

**Issue by njuwangchen** [googlecodelabs/feedback#44]
https://codelabs.developers.google.com/codelabs/android-studio-jni/index.html?index=..%2F..%2Findex#3

I cannot make this work when I come to step 3. Got error message like The project may be using a version of the Android Gradle plug-in that does not contain the method.

**Comment by ggfan** [comment]
issue is resolved off-line with submitter, no code change needed.
 right now we have 3 options for android studio + native development
-  gradle-experimental  ( this codelab is about it)
-  cmake    ( this is gaining momentum )
-  ndk-build
  it might cause some confusion, but it should soon settle down as whichever is convenient will help the most.

Closing it for now, feel free to re-open if more info is necessary
