### ISSUE TITLE
[cloud-vision-intro]:

### ISSUE THREAD

**Issue by krisspadea** [googlecodelabs/feedback#441]
when calling the api, I am getting this error:
{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Expected , or } after key:value pair.\n        },\n        \"features\": [\n       \n                    ^",
    "status": "INVALID_ARGUMENT"
  }
}

**Comment by PicardParis** [comment]
- The error message indicates a malformed json, most probably a typo in `request.json`.
- Retried the codelab, everything is fine.
