### ISSUE TITLE
[cloud-running-a-container]: Dockerfile has been updated

### ISSUE THREAD

**Issue by Fleker** [googlecodelabs/feedback#442]
In the codelab, here: https://codelabs.developers.google.com/codelabs/cloud-running-a-nodejs-container/index.html?index=..%2F..%2Findex#3

The Dockerfile contains the instructions:

```
FROM node:4
EXPOSE 8080
COPY server.js .
CMD node server.js
```

However, after cloning and looking at the file in my cloud shell, I see it is using a newer version of Node.js:

```
FROM node:6-alpine
EXPOSE 8080
COPY server.js .
CMD node server.js
```

**Comment by alexismp** [comment]
this has now been fixed
