### ISSUE TITLE
[cloud-kubernetes-aspnetcore]: Invalid Command "PROJECT_ID" is not wrapped with ${}

### ISSUE THREAD

**Issue by muhihsan** [googlecodelabs/feedback#444]
On this URL https://codelabs.developers.google.com/codelabs/cloud-kubernetes-aspnetcore/index.html?index=..%2F..%2Findex#11

`gcloud docker -- push gcr.io/PROJECT_ID/hello-dotnet:v2`

PROJECT_ID should be wrapped with **${}**

`gcloud docker -- push gcr.io/${PROJECT_ID}/hello-dotnet:v2`

![image](https://user-images.githubusercontent.com/18164621/42258685-4cf7f3e0-7fa0-11e8-84f5-419b5f463a57.png)

Same goes to this part

![image](https://user-images.githubusercontent.com/18164621/42258727-7e936a56-7fa0-11e8-8f50-ad7d6a326c6c.png)

**Comment by meteatamel** [comment]
Fixed. The second part doesn't need to be wrapped, it needs to be replaced with the actual project id.
