### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by rajdhandus** [googlecodelabs/feedback#445]
```
raj_dhandus@cloudshell:~/gae-standard-example (my-nodejs-codelab-1217-190421)$ gcloud app create --region us-central
You are creating an app for project [my-nodejs-codelab-1217-190421].
WARNING: Creating an App Engine application for a project is irreversible and the region
cannot be changed. More information about regions is at
<https://cloud.google.com/appengine/docs/locations>.
ERROR: (gcloud.app.create) The project [my-nodejs-codelab-1217-190421] already contains an App Engine application. You can deploy your application using `gcloud app deploy`.
raj_dhandus@cloudshell:~/gae-standard-example (my-nodejs-codelab-1217-190421)$ gcloud app deploy
WARNING: Automatic app detection is deprecated and will soon be removed. As an alternative, create an app.yaml file yourself using the directions at https://cloud.google.com/appengine/docs/flexible/python/confi
guring-your-app-with-app-yaml (App Engine Flexible Environment) or https://cloud.google.com/appengine/docs/standard/python/config/appref (App Engine Standard Environment) under the tab for your language.
Deployment to Google App Engine requires an app.yaml file. This
command will run `gcloud beta app gen-config` to generate an app.yaml
file for you in the current directory (if the current directory does
not contain an App Engine service, please answer "no").

Do you want to continue (Y/n)?  Y

ERROR: (gcloud.app.deploy) Could not identify an app in the current directory.
Please prepare an app.yaml file for your application manually and deploy again.
```

**Comment by rajdhandus** [comment]
raj_dhandus@cloudshell:~/gae-standard-example (my-nodejs-codelab-1217-190421)$ ./mvnw -DskipTests appengine:deploy
/home/raj_dhandus/gae-standard-example
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.227 s
[INFO] Finished at: 2018-07-10T14:39:25-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'deploy' in plugin com.google.appengine:appengine-maven-plugin:1.9.60 among available goals backends_configure, backends_delete, backends_rollback, backends_start, backends_stop, bac
kends_update, create-property, debug, devserver, devserver_start, devserver_stop, endpoints_get_client_lib, endpoints_get_discovery_doc, endpoints_get_swagger_doc, enhance, migrate_traffic, rollback, set_default_version, start_module_version, stop_module_version, update, update_cron, update_dispatch, update_dos, update_indexes, update_queues, vacuum_indexes -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException

**Comment by PicardParis** [comment]
- Rechecked the codelab: it runs fine.
- The `MojoNotFoundException` error seems to indicate that the plugin `appengine-maven-plugin` was not correctly added in `pom.xml`.
