### ISSUE TITLE
[cloud-app-engine-springboot]: description discrepancy 

### ISSUE THREAD

**Issue by jungejason** [googlecodelabs/feedback#450]
In [step 8](https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..%2Findex#7) of "Deploy Spring Boot Application in App Engine standard
 ", which is to deploy the app on app engine, the doc mentioned to run `mvn appengine:deploy`, but actually it's to run `./mvnw -DskipTests appengine:update`. It's a little confusing. 

![image](https://user-images.githubusercontent.com/643706/42978654-ff19c588-8b82-11e8-8b65-8b22e274772f.png)

**Comment by saturnism** [comment]
i think this was fixed a while back. thnx!
