### ISSUE TITLE
[cloud-springboot-cloudshell]: Missing verb

### ISSUE THREAD

**Issue by elharo** [googlecodelabs/feedback#460]
sentence fragment: "With Cloud Shell, the Cloud SDK gcloud command and tools you need to build a Java application, such as the JVM, Maven, and Gradle."

**Comment by elharo** [comment]
Probably meant to say something like, "With Cloud Shell, the Cloud SDK gcloud command-line tool and other tools you need to build a Java application are always available, up to date and fully authenticated."

**Comment by meteatamel** [comment]
Not relevant anymore
