### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by pHag** [googlecodelabs/feedback#464]
https://codelabs.developers.google.com/codelabs/cloud-slack-bot/index.html?index=..%2F..%2Findex#5

"Open the code editor"
The way to open the code editor has been changed since this lab was written.
Now you are instead supposed to click on the pen in the upper righthand corner.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
