### ISSUE TITLE
[cloud-spring-cloud-gcp-gcs]:

### ISSUE THREAD

**Issue by prakashayappan** [googlecodelabs/feedback#466]
How to setup GCP credentials to be integrated with Spring based application from Non-GCP / localhost.

**Comment by meltsufin** [comment]
There are several ways. Here's [a good article on various options](https://medium.com/google-cloud/local-remote-authentication-with-google-cloud-platform-afe3aa017b95).

**Comment by meteatamel** [comment]
Updated the codelab and tested that it works. Closing this issue.
