### ISSUE TITLE
Track changes for code lab - Build a Progressive Web App with Firebase, Polymerfire and Polymer Components

### ISSUE THREAD

**Issue by peterennisrda** [googlecodelabs/feedback#47]
Working on this and I noticed it is updated today.
How do I know what is fixed since I worked on it yesterday?
![capture3881](https://cloud.githubusercontent.com/assets/1280523/16137280/75cc4bac-33e6-11e6-8436-d58a16c801d0.png)

**Comment by x1ddos** [comment]
@peterennisrda we don't have diffs but I assume @cdata would've closed the other issues which have been fixed.

**Comment by MrCsabaToth** [comment]
Which is the source code repository for that codelab? I cannot find it.

**Comment by x1ddos** [comment]
https://github.com/polymerlabs/note-app is what you meant? Everything else is described directly in the codelab, e.g. https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/#6

**Comment by MrCsabaToth** [comment]
@crhym3 Thanks, I guess that can be a good starting point.
