### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by sruthi87** [googlecodelabs/feedback#471]
[ERROR] Could not find goal 'deploy' in plugin com.google.appengine:appengine-maven-plugin:1.9.64 among available goals backends_configure, backends_delete, backends_rollbac
k, backends_start, backends_stop, backends_update, create-property, debug, devserver, devserver_start, devserver_stop, endpoints_get_client_lib, endpoints_get_discovery_doc,
 endpoints_get_swagger_doc, enhance, migrate_traffic, rollback, set_default_version, start_module_version, stop_module_version, update, update_cron, update_dispatch, update_
dos, update_indexes, update_queues, vacuum_indexes -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException

**Comment by meteatamel** [comment]
Tested and the codelab worked for me.
