### ISSUE TITLE
[cloud-hello-istio]:

### ISSUE THREAD

**Issue by rross** [googlecodelabs/feedback#479]
In step # 3 the directions say to use the following command:

gcloud container clusters create hello-istio \
    --cluster-version=latest \
    --num-nodes 4

This doesn't work because you need to specify either a zone or region.  It needs to be updated:

1. Choose a region using the following command:

`gcloud compute regions list`

2. Set your region to one from the above list:

`REGION=us-central1 `

3. Create the cluster: 

```
gcloud container clusters create hello-istio \
    --cluster-version=latest \
    --num-nodes 4 \
    --region $REGION
```

**Comment by meteatamel** [comment]
Actually, the previous step tells you to set the region but it's good to mention again in this step. Fixed.
