### ISSUE TITLE
[cloud-hello-istio]:

### ISSUE THREAD

**Issue by rross** [googlecodelabs/feedback#480]
In Step # 11, the cleanup command does not work: 

`gcloud container clusters delete hello-istio`

The error is that it needs a region or a zone.  This should be changed to match the updated step # 3 to add the --region command like this:

`gcloud container clusters delete hello-istio --region $REGION`

**Comment by meteatamel** [comment]
I think you forgot to set the region in gcloud but I added a note to warn people. Thanks.
