### ISSUE TITLE
[cloud-tensorflow-mnist]:

### ISSUE THREAD

**Issue by SinanGabel** [googlecodelabs/feedback#481]
Hi!

A minor issue at "8. Lab: special care for deep networks": 

tf.nn.softmax_cross_entropy_with_logits() 
has changed to: 
tf.nn.softmax_cross_entropy_with_logits_v2()

**Comment by martin-gorner** [comment]
Thank you for reporting this. The lab was rewritten for modern Tensorflow 1.14+ and Keras. This line of code is not used anymore.
