### ISSUE TITLE
[cloud-slack-bot]: Deprecated 'gcloud docker' command and missing '--record' flag

### ISSUE THREAD

**Issue by vatervonacht** [googlecodelabs/feedback#486]
Great codelab.  Learned a lot.  At a couple points in this lab the instructions say to use the following command to push the image to the registry:

      $  `gcloud docker -- push gcr.io/${PROJECT_ID}/slack-codelab:v<#>`.  

There is a deprecation message that I get when I do this.  The new approach should be to first establish `gcloud` as credential helper for docker.  Then run the `docker push` command directly.   For example

     $ gcloud auth configure-docker
     $ docker push gcr.io/${PROJECT_ID}/slack-codelab:v<#>

Also, in the extra credit section, the `--record` option should be appended to the `kubectl apply -f` command.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
