### ISSUE TITLE
[cloud-tensorflow-mnist]:

### ISSUE THREAD

**Issue by jpmolinamatute** [googlecodelabs/feedback#496]
I think tensorflow-without-a-phd/tensorflow-mnist-tutorial/mnist_1.0_softmax.py got out of sync with the tutorial https://codelabs.developers.google.com/codelabs/cloud-tensorflow-mnist/#5.

The code in mnist_1.0_softmax.py has some lines that the tutorial doesn't have and vice versa

**Comment by martin-gorner** [comment]
Thank you for your feedback. The entire lab was revamped for modern Tensorflow and now uses Keras as its high-level API. The code files have been rewritten too and they are now in sync.
(The code files referenced from the lab. Yes, the old files like tensorflow-without-a-phd/tensorflow-mnist-tutorial/mnist_1.0_softmax.py are still in the GitHub repo but nothing links to them anymore. I'll clean this up later)
