### ISSUE TITLE
[cloud-kubernetes-aspnetcore]: Slide no 4 does not run according to instructions at all

### ISSUE THREAD

**Issue by abdulsattar** [googlecodelabs/feedback#497]
`dotnet run` can't start the development server because it says it can't trust the certificate. It presents `dotnet dev-certs https` as a solution but even after running that it listens on 5000 for HTTP and 5001 for HTTPS, so 'Preview on port 8080' doesn't work. Even if we change it to port 5000 and run it fails with the following error:

```
Failed to authenticate HTTPS connection.
System.IO.IOException: The handshake failed due to an unexpected packet format.
```

**Comment by meteatamel** [comment]
Thanks for the feedback. Just tested and this works in the current version of Cloud Shell. Please try again and lets us know if it's still an issue.

**Comment by meteatamel** [comment]
Closing. Please re-open if you still see the issue.
