### ISSUE TITLE
Formatting issue in Hello Node Kubernetes lab

### ISSUE THREAD

**Issue by saadnabs** [googlecodelabs/feedback#5]
In Step 4, at the part where it says "Let's stop the container", the code display shows:
   docker ps
   .... {the output here}...    $docker stop

But when viewed in HTML, the stop does not show, so would make sense to push it down to a new line.

**Comment by hostirosti** [comment]
Thank you for reporting this @saadnabs!
The issue is fixed at https://codelabs.developers.google.com/codelabs/cloud-hello-kubernetes/index.html?index=..%2F..%2Findex#3
