### ISSUE TITLE
Hello-libs

### ISSUE THREAD

**Issue by bharatiadkar** [googlecodelabs/feedback#50]
Hi,
I tried to use Hello-libs example to try to link a precompiled static library from a third party vendor, but I get error with the Gradle Sync

I have included my build.gradle(Modeule:app) here
apply plugin: 'com.android.model.application'

def lib_distribution_root = '../distribution'

model{
   repositories {
       libs(PrebuiltLibraries) {
           // Configure one pre-built lib: shared
           /_smi {
                // Inform Android Studio where header file dir for this lib
                //BA commenting out the include as there are no headers.
                headers.srcDir "/Users/bharati/Documents/workspace-android/SMITestLib/distribution/smi/include"
                // Inform Android Studio where lib is -- each ABI should have a lib file
                binaries.withType(StaticLibraryBinary) {
                    staticLibraryFile = "/Users/bharati/Documents/workspace-android/SMITestLib/distribution/smi/lib/libsmiaudioclientlib.a"
                }
            }_/
           // Configure another pre-built lib: shared;[change to static after Studio supports]
           // static lib generation. USING static lib is supported NOW, for that case,
           // simple change:
           //  SharedLibaryBinary --> StaticLibraryBinary
           //  sharedLibraryFile  --> staticLibraryFile
           //  *.so --> *.a
           smi {
               //headers.srcDir "${lib_distribution_root}/smi/include"
               binaries.withType(StaticLibraryBinary) {
                   staticLibraryFile = file("/Users/bharati/Documents/workspace-android/SMITestLib/libs/libsmiaudioclientlib.a")
               }
           }
       }
   }

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.smi.smitestlib"
        minSdkVersion.apiLevel 19
        targetSdkVersion.apiLevel 23
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles.add(file('proguard-android.txt'))
        }
    }
    // New code
    ndk {
        platformVersion = 21
        moduleName "helloandroidjni"
        toolchain = 'clang'
        stl = 'gnustl_static'
        cppFlags.addAll(['-std=c++11'])
        ldLibs.addAll(['android', 'log'])

    }
    // New code finished
    sources {
        main {
            jni {
                dependencies {
                   // library 'gmath' linkage 'shared'
                    // if gperf were *.a, change shared --> static
                    library 'smiaudioclientlib' linkage 'static'
                }
            }
            jniLibs {
                // for shared lib, lib need to be pushed to the target too
                // Once libs are copied into app/src/main/jniLibs directory,
                // Android Studio will pack them into APK's lib/ directory
                // Here we like to avoid another duplication by pointing
                // to the files that containing our libs' distribution location
                // so the same file is used by compiler at host, also packed
                // into APk to be used at Target (phone/tablet)
                source {
                    srcDir "/Users/bharati/Documents/workspace-android/SMITestLib/libs"
                    //srcDir "${lib_distribution_root}/gperf/lib"
                }
            }
        }
    }


}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha2'
    compile 'com.android.support:design:23.4.0'
    testCompile 'junit:junit:4.12'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support:support-annotations:23.4.0'
}

//  Unnecessary dependency management:
//  Make sure the libs are available when begin compiling application project
//  This could be ignored because in real scenario, the pre-built libs are
//  already given to us before creating application.

tasks.whenTaskAdded { task ->
    if (task.name.contains('compile')) {
        task.dependsOn ':smi:distributeLib'
        //task.dependsOn ':gperf:distributeLib'
    }
}
This file is model after your build.gradle(Module:app)

Please let me know what I am doing wrong or just add an example to add a static library in an jni project.

Thanks,
Bharati Adkar

**Comment by bharatiadkar** [comment]
I forgot to add the error that I see from gradle sync.

Gradle 'SMITestLib' project refresh failed
Error:Prebuilt library with name 'smiaudioclientlib' not found in repositories '[libs]'.

The exists in the folders in the build.gradle

**Comment by ggfan** [comment]
if you copied exact as is of your gradle file, the place trying to comment out code pace has a typo need
/\*  */,  not /smi{ ...}/

/smi {
// Inform Android Studio where header file dir for this lib
//BA commenting out the include as there are no headers.
headers.srcDir "/Users/bharati/Documents/workspace-android/SMITestLib/distribution/smi/include"
// Inform Android Studio where lib is -- each ABI should have a lib file
binaries.withType(StaticLibraryBinary) {
staticLibraryFile = "/Users/bharati/Documents/workspace-android/SMITestLib/distribution/smi/lib/libsmiaudioclientlib.a"
}
}/

could you confirm?

**Comment by ggfan** [comment]
how about we go work on this on Android-ndk repo, since this is directly related to that repo? if you are ok, create a bug there, we work there.  let me know, thanks

**Comment by bharatiadkar** [comment]
Hi Gerry,
I would be happy to file a bug at Android-ndk. Please can you point me to a
URL where I should file this bug.
Thanks,

**Comment by ggfan** [comment]
thank you!  here is the place:
  https://github.com/googlesamples/android-ndk
under issues. 

the trick to get static lib to work is to refer to the comment above gperf inside app/build.gradle.  let's work it out there. thank you a lot

**Comment by ggfan** [comment]
new issue opened:
https://github.com/googlesamples/android-ndk/issues/239

closing this one as it is being worked out there. thanks
