### ISSUE TITLE
[cloud-kubernetes-aspnetcore]: Missing "Google Cloud Container Builder API"

### ISSUE THREAD

**Issue by baloodevil** [googlecodelabs/feedback#502]
The "New API Library" in Google Cloud does not have "Google Cloud Container Builder API" as referenced [here](https://codelabs.developers.google.com/codelabs/cloud-kubernetes-aspnetcore/index.html?index=..%2F..%2Findex#12).

**Comment by meteatamel** [comment]
Thanks very much for the feedback. This has been fixed!
