### ISSUE TITLE
[cloud-create-a-vm]:

### ISSUE THREAD

**Issue by rossjs** [googlecodelabs/feedback#504]
On [Running Node.js on a Virtual Machine: 5. Install Node.js](https://codelabs.developers.google.com/codelabs/cloud-create-a-nodejs-vm/index.html?index=..%2F..%2Findex#4)

The fourth code block is `cd nodejs-docs-samples/appengine/hello-world/` but there are now options for both flex and standard environments in Node.js.

This should be changed to either `cd nodejs-docs-samples/appengine/hello-world/flexible` or `cd nodejs-docs-samples/appengine/hello-world/standard`

**Comment by alexismp** [comment]
Fixed. thanks for the report and sorry for the delay.
