### ISSUE TITLE
[cloud-tensorflow-mnist]: Code must be run from Command-Line / Console

### ISSUE THREAD

**Issue by richlysakowski** [googlecodelabs/feedback#507]
Not all instructions are included in the codelab source code for "TensorFlow and Deep Learning, without a PhD".   The programs MUST be run from a Console command line prompt. They cannot be run from Jupyter or Spyder.  

See:  https://stackoverflow.com/questions/42707081/error-with-tensorflow-1-0-mnist-code

The solution is to run the code from within the folder where all the code resides. Don't just copy the mnist_1.0_softmax.py code to your IDE and run it. Download or clone entire repo from the link below

https://github.com/martin-gorner/tensorflow-mnist-tutorial.git
Once cloned, you will see that in that folder there is file called tensorflowvisu.py. So this is not a module that you install from conda or pip. It's just a file that the author uses as module in this precise case. Go to that dir where all this code sits through command line and from there run

python mnist_1.0_softmax.py
Now it should work. You should see a pop up windows with 6 charts that get updated in real-time.

If you want to run it from your IDE, then open your IDE (in my case Atom) and there go to File > Open Folder > Click OK > choose your file mnist_1.0_softmax.py and press Ctrl+Shift+B. the same pop up window should appear. The most important thing is to open the file from within the dir provided by the author.

**Comment by martin-gorner** [comment]
Thank you for your feedback. The entire lab was revamped for modern Tensorflow and now uses Keras as its high-level API. Also, it now runs entirely in Colaboratory. I believe the issue you report is not relevant anymore.
