### ISSUE TITLE
[cloud-vision-intro]:

### ISSUE THREAD

**Issue by leegare** [googlecodelabs/feedback#529]
In "8. Create your Vision API request" after clicking on the built-in Orion editor in Cloud Shell, there are no fields in which I can paste the suggested code. (see image attached)
![capture d ecran 2018-12-11 a 22 36 08](https://user-images.githubusercontent.com/5898280/49851230-4686e480-fd95-11e8-9e3a-86877e0bd05f.png)

**Comment by PicardParis** [comment]
- Under the `File` menu, there's a `New File` option.
- Updated the codelab to mention this.
