### ISSUE TITLE
[cloud-app-engine-python]: Product updates for Overview page

### ISSUE THREAD

**Issue by aliciawilliams** [googlecodelabs/feedback#53]
Need to update this paragraph for languages: 
App Engine's environments, the Standard Environment and the Flexible environment, support a host of programming languages. The latest versions of Python 3.4, Java 8, and Node.js are available in the Managed VM environment, PHP is available in the standard environment only, and Go is available in both. The two environments give users maximum flexibility in how their application behaves since each environment has certain strengths. Read The App Engine Environments for more information.

Link to "Flexible environment" is missing the capital F.

**Comment by saturnism** [comment]
updated. ptal.
