### ISSUE TITLE
[cloud-hello-istio]: discrepancy between text and actual command snippet

### ISSUE THREAD

**Issue by sanjaypujare** [googlecodelabs/feedback#532]
The text says 

> we can use a convenient command to download and extract the 0.8.0 release automatically:

but the actual version referenced in the command snippet is 1.0.0 (I think).

`curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.0.0 sh -`

This could be confusing to users.

**Comment by meteatamel** [comment]
Instructions don't have this anymore.
