### ISSUE TITLE
[cloud-hello-istio]: virtual-service-all-v1-mtls.yaml doesn't exist

### ISSUE THREAD

**Issue by sanjaypujare** [googlecodelabs/feedback#533]
Step 8 has the following command at the end:

`kubectl delete -f samples/bookinfo/networking/virtual-service-all-v1-mtls.yaml`

But virtual-service-all-v1-mtls.yaml doesn't exist ! Instead virtual-service-all-v1.yaml exists and seems to work. Either create virtual-service-all-v1-mtls.yaml or change the reference.

**Comment by meteatamel** [comment]
Thanks for letting us know. Fixed.
