### ISSUE TITLE
[cloud-app-engine-springboot]: Standard or flexible

### ISSUE THREAD

**Issue by elongeau** [googlecodelabs/feedback#536]
Hello,

the title of the lab says "how to deploy a Spring app on AppEngine standard" but in the _Deploying the Application into App Engine_ there's a note that said it deploys to AppEngine flexible:
![image](https://user-images.githubusercontent.com/1712989/50963502-2f8afd80-14cd-11e9-809b-da6c2c4f702e.png)

What is the good one ?

**Comment by saturnism** [comment]
fixed :) https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..spring#7
