### ISSUE TITLE
[cloud-networking-101]:

### ISSUE THREAD

**Issue by Annie29** [googlecodelabs/feedback#543]
In Step 5: Check Latency between VMs

the command ping eu1-vm fails with the message:
ping: eu1-vm: Name or service not known

but pinging the external IP address does work.  

I know this has worked in the past, so assume something has changed somewhere to break it.

**Comment by Annie29** [comment]
Well, that was curious.  I tried the same steps from another account and it worked.

**Comment by giriarte** [comment]
Hello, the same is happening to me. For instances between different regions Im unable to ping by instance name
