### ISSUE TITLE
[cloud-bigquery-load-data]: Update open data set link, typo, what we covered

### ISSUE THREAD

**Issue by aliciawilliams** [googlecodelabs/feedback#55]
https://cloud.google.com/bigquery/public-data/

subredit -> subreddit

What we covered: this is not what we learned

**Comment by saturnism** [comment]
updated.

**Comment by aliciawilliams** [comment]
saturnism updated the "what we've covered" section.

I updated the other two items:

 https://cloud.google.com/bigquery/public-data/

subredit -> subreddit
