### ISSUE TITLE
[cloud-tensorflow-mnist]: grammatical errors/typos

### ISSUE THREAD

**Issue by protovist** [googlecodelabs/feedback#550]
"This where the TensorFlow magic happens."

"TensorFlow was build for distributed computing."

https://codelabs.developers.google.com/codelabs/cloud-tensorflow-mnist/#5

**Comment by protovist** [comment]
"For example, if your instruct it to run one part of the computation"

**Comment by martin-gorner** [comment]
Thank you for your feedback. The entire lab was revamped for modern Tensorflow and now uses Keras as its high-level API. The text was rewritten too and I think that the sentences containing the typos are not there anymore.
