### ISSUE TITLE
[cloud-endpoints-appengine]: deploy error due to Java version

### ISSUE THREAD

**Issue by murphyke** [googlecodelabs/feedback#552]
Using a qwiklabs environment in a class, I got this error:

```
[INFO] GCLOUD: ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Java 7 applications are prevented from being deployed to Google App Engine from any version of the SDK
, including older ones. If you need to continue to deploy Java 7 applications for compatibility reasons, you can request that your application be whitelisted for 
Java 7 deployment by visiting https://goo.gl/forms/qxeXfigRMccwAvoj1
```

When I edited the pom.xml to replace 1.7 with 1.8 and rebuilt, I got a different error.

```
[INFO] GCLOUD: Unable to stage app: Class file is Java 8 but max supported is Java 7: /home/google2446506_student/java-docs-samples/appengine/endpoints-frameworks
-v2/backend/target/echo-1.0-SNAPSHOT/WEB-INF/classes/com/example/echo/Echo.class
```

It looks like I need the Hogwarts Express version of Java.

Since I'm not a Java person, I will just try a different lab.

**Comment by lopezvit** [comment]
Run into the same problem, but got it solved.
After changing that what you changed, you have to go as well to `src/main/webapp/WEB-INF/appengine-web.xml`
and add `<runtime>java8</runtime>` after `<threadsafe>true</threadsafe>` in the line 18.

**Comment by alexismp** [comment]
Thanks for the reports.
This codelab has been updated and tested for Java 8.
Please re-open if the issue persists
