### ISSUE TITLE
[cloud-hello-istio]:

### ISSUE THREAD

**Issue by eclansky** [googlecodelabs/feedback#553]
In step 7: at the end of the page
kubectl delete -f samples/bookinfo/networking/virtual-service-all-v1-mtls.yaml

There is no virtual-service-all-v1-mtls.yaml file, but there is a virtual-service-all-v1.yaml file.
The documentation needs updating. 

Should be updated to:
kubectl delete -f samples/bookinfo/networking/virtual-service-all-v1.yaml

**Comment by meteatamel** [comment]
Thanks for letting us know. Fixed.
