### ISSUE TITLE
[cloud-app-engine-springboot]: missing "cleanup" section

### ISSUE THREAD

**Issue by hiwaylon** [googlecodelabs/feedback#555]
> Running through this codelab shouldn't cost you more than a few dollars, but it could be more if you decide to use more resources or if you leave them running (see "cleanup" section at the end of this document).

There's no cleanup section at the end of the document, that I could find. This is unfortunate because it's actual money on the line if we don't understand how to turn things off.

**Comment by meteatamel** [comment]
Thanks for reporting, cleanup section added.
