### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by marhan** [googlecodelabs/feedback#558]
Dear developers,

some of the WebUI screenshots of the Google Cloud console seems to be outdated. Sample given: In chapter "6. Create your cluster" the product is called "Cluster engine". Actually, in my console, it is named as "Kubernetes-Cluster". The describing text in the this tutorial also called it "Kubernetes-Cluster".

Kindly regards

Markus

**Comment by meteatamel** [comment]
Fixed
