### ISSUE TITLE
[Function to Update Google Sheets Codelab]: Step 9

### ISSUE THREAD

**Issue by phluks** [googlecodelabs/feedback#564]
This text is inconsistent with the code-examples:

"If all goes well, at this point you can:
...
 . see the CSV pop up in your spreadsheet!"

No! Because we have not yet invoked the functions that does this.

**Comment by alexismp** [comment]
Dropping the file in the bucket is what triggers the function so the data should indeed appear in the spreadsheet

**Comment by alexismp** [comment]
Codelab and snippets have now been updated. Hopefully this now works well for everyone.
