### ISSUE TITLE
[Function to Update Google Sheets Codelab]: Step 11

### ISSUE THREAD

**Issue by phluks** [googlecodelabs/feedback#565]
The text is inconsistent with the code-examples:

"Once everything is in place, simply upload a CSV file to the right bucket and watch your spreadsheet be updated with a new sheet with the file's content."

No! Because the example code references the "sheetName" variable, which has not been declared or set.

The only way to find a working code example seems to be following the link to the gist.

**Comment by alexismp** [comment]
This should now all be fixed. I've pushed updates to the codelabs as well as to the gist.
