### ISSUE TITLE
[cloud-speech-intro]: error with export API

### ISSUE THREAD

**Issue by HenrikFB** [googlecodelabs/feedback#566]
In step 6 "Create an API key" from https://codelabs.developers.google.com/codelabs/cloud-speech-intro/index.html?index=..%2F..index#5¨

The following step with the api key: export API_KEY=<YOUR_API_KEY> I get the error "-bash: export ´=': not a valid identifier".

I writing:  

export API_KEY = mykey

And had tried different thing. 

Had it changed? Or does I missing something with my credentials or API setup?

Thanks.

**Comment by HenrikFB** [comment]
no spaces :)

**Comment by alexismp** [comment]
Right, make sure you don't add spaces around the = sign
