### ISSUE TITLE
[cloud-bigquery-wikipedia]:Update "what we covered" (step 7)

### ISSUE THREAD

**Issue by aliciawilliams** [googlecodelabs/feedback#57]
Update "what we covered" (step 7)

**Comment by aliciawilliams** [comment]
also update subredit -> subreddit (typo)
also update link to open data sets: https://cloud.google.com/bigquery/public-data/

**Comment by saturnism** [comment]
updated.

**Comment by aliciawilliams** [comment]
@saturnism where did you update?
