### ISSUE TITLE
[Function to Update Google Sheets Codelab]: Wrong package.json format

### ISSUE THREAD

**Issue by Shimi** [googlecodelabs/feedback#570]
in [cloud-function2sheet](https://codelabs.developers.google.com/codelabs/cloud-function2sheet/#4), the final setup step shows bad JSON for package.json file.

instead of 
```{
    name: "function2sheet",
    version: "0.0.42",
    dependencies: {
        googleapis: "^35.0.0",
        @google-cloud/storage: "^2.3.1"
    }
}
```

it should be 
```
{
    "name": "function2sheet",
    "version": "0.0.42",
    "dependencies": {
        "googleapis": "^35.0.0",
        "@google-cloud/storage": "^2.3.1"
    }
}
```

If you try to deploy with what is written in the code, the deployment fail

**Comment by alexismp** [comment]
thanks, this is now fixed
