### ISSUE TITLE
[cloud-app-engine-springboot]: Please include Maven dependencies from Springboot Appengine Standard repo

### ISSUE THREAD

**Issue by dzuluaga** [googlecodelabs/feedback#572]
Hey there. Thanks for the tutorial. It was really easy to follow and to deploy to GAE Standard. One suggestion though, is to incorporate the steps from [Springboot Appengine Standard](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard#remove-tomcat-starter) related to modifying the pom.xml, which update to Servlet 3.1.0, remove spring-boot-starter-tomcat, and Exclude JUL to SLF4J Bridge. I run into hard to troubleshoot issues while I was testing WebServlet filters because these dependencies were missing in mine. Using Springboot Appengine Standard fix them. Thanks!

[Deploy Spring Boot Application in App Engine standard](https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..index#1)

**Comment by saturnism** [comment]
this has just been updated to use the new java11 runtime w/ JAR deployment. :)

https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..spring#4
