### ISSUE TITLE
[cloud-app-engine-python]: Tutorial assumes Python 2.7

### ISSUE THREAD

**Issue by LairBob** [googlecodelabs/feedback#578]
The tutorial assumes an outdated version of Python. It's possible to use:
`runtime: python37`
but then there is a series of other changes that need to be made to `threadsafe`, etc. before things will work correctly.

**Comment by PicardParis** [comment]
- Thank you very much for the feedback.
- There is a [Python 3 version](https://codelabs.developers.google.com/codelabs/cloud-app-engine-python3).
- I added a note at the beginning of this legacy codelab.
