### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by visacare** [googlecodelabs/feedback#579]
Hi Team,
We need your support in Deploying our project in Google Cloud.
We have followed the steps in the link below and able to complete till 8 steps.
https://codelabs.developers.google.com/codelabs/cloud-springboot-kubernetes/index.html#7 
Refer Image 2
 But at last when we try to access our application mentioned in the last paragraph in 8th step (You should now be able to reach the service by pointing your browser to this address: http://<EXTERNAL_IP>:8080) it is not accessible.
We are getting Site can't be reached.
Refer Image 1
Please let us know how to fix the same.

![image (2)](https://user-images.githubusercontent.com/42641913/57128836-4d4cdd00-6db2-11e9-805b-2dbf350e98bf.png)
![image (1)](https://user-images.githubusercontent.com/42641913/57128838-4de57380-6db2-11e9-9714-31963829ecd9.png)

**Comment by meteatamel** [comment]
Tested and was able to access the app with `http://<EXTERNAL_IP>:8080` url
