### ISSUE TITLE
[cloud-spanner-leaderboard-java]: Wrong button to add add new project

### ISSUE THREAD

**Issue by maksimu** [googlecodelabs/feedback#584]
On the [first page](https://codelabs.developers.google.com/codelabs/cloud-spanner-leaderboard-java/index.html?index=..%2F..io2019#1) it shows to click on "+" button, but there is no more "+" button, 

![image](https://user-images.githubusercontent.com/187306/57469526-b366b380-723b-11e9-89f7-ddb219a02192.png)

but a new button called "New Project"

![image](https://user-images.githubusercontent.com/187306/57469555-c9747400-723b-11e9-9e26-11f758e79bcf.png)

**Comment by jsimonweb** [comment]
Thanks for reporting this!

Fixed.
