### ISSUE TITLE
[keras-flowers-data]:

### ISSUE THREAD

**Issue by AntGul** [googlecodelabs/feedback#585]
Hi Martin, were you able to port your code on TF2.0 alpha?

**Comment by martin-gorner** [comment]
The next step is to port it to TF 1.14. Keras TPU support changes there. TF 2.0 fixes will come after that.

**Comment by AntGul** [comment]
check https://github.com/tensorflow/tensorflow/issues/24412

**Comment by martin-gorner** [comment]
Closing for now. The goal of this lab is to show how to work with TPUs in TF today (TF 1.13). Support for TF 2.0 will come as soon as TF 2.0 is ready with the necessary features.
