### ISSUE TITLE
[cloud-istio-aspnetcore-part2]: Missing Jaeger and ServiceGraph visualization

### ISSUE THREAD

**Issue by psmorandi** [googlecodelabs/feedback#593]
In the Overview of the lab it states:

> What you'll learn
> - How to query metrics with Prometheus.
> - How to visualize metrics with Grafana.
> - How to do distributed tracing with Jaeger.
> - How to visualize service dependencies with ServiceGraph.
> - How to create a new version of your service.
> - How to pin a service to a specific version.
> - How to split traffic between different versions.
> - How to inject faults in service calls.

However, there is no tutorial to install/configure Jaeger and Kiali for both distributed tracing and ServiceGraph.

**Comment by meteatamel** [comment]
Thanks for the feedback. We removed Jaeger and ServiceGraph references.
