### ISSUE TITLE
[cloud-istio-aspnetcore-part1]:

### ISSUE THREAD

**Issue by ghost** [googlecodelabs/feedback#595]
It is not possible to set up a 4 pod Kubernetes Cluster with n1-standard-2 machines using the quota limitations in the $300 free trial credit.

I had to drop the config down to: 2 pods, n1-standard-1 machines to keep it within the quote. 

ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=403, message=
        (1) insufficient regional quota to satisfy request: resource "CPUS": request requires '12.0' and is short '4.0'. project has a quota of '8.0' with '8.0' available. View and manage quotas at https://console.cloud.google.com/iam-admin/quotas?usage=USED&project={{*ProjectMasked*}}
        (2) insufficient regional quota to satisfy request: resource "IN_USE_ADDRESSES": request requires '12.0' and is short '4.0'. project has a quota of '8.0' with '8.0' available. View and manage quotas at https://console.cloud.google.com/iam-admin/quotas?usage=USED&project={{*ProjectMasked*}}

**Comment by meteatamel** [comment]
Istio requires 4 nodes with n1-standard-2 machines last time I checked, so not sure if there's a solution within $300 free trial.
