### ISSUE TITLE
Bad path for nginx in step 8 of Compute Engine & Kubernetes (Container Engine)

### ISSUE THREAD

**Issue by a14n** [googlecodelabs/feedback#6]
The step 8 _Startup Script_ has the following code snippet:

``` sh
#! /bin/bash
apt-get update
apt-get install -y nginx
service nginx start
sed -i -- 's/nginx/Google Cloud Platform - '"$HOSTNAME"'/' /usr/share/nginx/www/index.html
```

The last command line points to an unexisting file. It should be `/var/www/html/index.nginx-debian.html`.

**Comment by hostirosti** [comment]
@a14n thank you for reporting this :) It has been fixed in https://codelabs.developers.google.com/codelabs/cloud-compute-kubernetes/index.html?index=..%2F..%2Findex#7
