### ISSUE TITLE
[fido2-for-android]:  "re-authentication" is also known as "step-up" authn 

### ISSUE THREAD

**Issue by equalsJeffH** [googlecodelabs/feedback#601]
the "Your First Android FIDO2 API" codelab says in part:
> "Re-authentication" is a concept where user signs into an app once, then authenticate again when they come back to your app, or trying to access an important section of your app.

(there's also various grammatical errors)

It ought to perhaps say:
> "Re-authentication" is a concept where a user signs into an app, then _re-authenticates_ when they switch back to your app, or when trying to access an important section of your app. The latter case is also referred to as "step-up authentication".

**Comment by agektmr** [comment]
Thank you @equalsJeffH for the feedback. I'll ask a tech writer to go through the text.
