### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by ummabdullah** [googlecodelabs/feedback#619]
Hi, 

I used the simple command line on my machine (ubuntu OS) and it was able to start the server succesfully on my local machine.  However, I am not able to see any web preview icon at that point I realized we had to do it using cloud shell.  The steps to access the cloud shell  can be included here to make it more clear and apparent.  I had to explore to find it.

And now that I did, I can't recreate the steps to find it again :)

**Comment by meteatamel** [comment]
The codelab assumes Cloud Shell and mentions this at the beginning.
