### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by ummabdullah** [googlecodelabs/feedback#620]
Another missing step: require billing enabled. 

[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.4.0:build (default-cli) on project gs-spring-boot: Build image failed, perhaps
 you should make sure you have permissions for gcr.io/focal-psyche-248214/hello-java and set correct credentials. See https://github.com/GoogleContaine
rTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-forbidden-or-denied for help: Unauthorized for gcr.io/focal-psyche-
248214/hello-java: 403 Forbidden
[ERROR] {"errors":[{"code":"DENIED","message":"Token exchange failed for project 'focal-psyche-248214'. Please enable Google Container Registry API in 
Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=focal-psyche-248214 before performing this
 operation."}]}
[ERROR] -> [Help 1]

**Comment by saturnism** [comment]
fixed the code lab for this one. added steps to enable the API.

https://codelabs.developers.google.com/codelabs/cloud-springboot-kubernetes/index.html?index=..%2F..spring#4
