### ISSUE TITLE
[keras-flowers-transfer-learning]:

### ISSUE THREAD

**Issue by henrique** [googlecodelabs/feedback#621]
unfortunately your examples don't run anymore :/
https://codelabs.developers.google.com/codelabs/keras-flowers-transfer-learning/#4

W0801 11:11:22.784980 140566666332032 keras_support.py:217] Keras support is now deprecated in support of TPU Strategy. Please follow the distribution strategy guide on tensorflow.org to migrate to the 2.0 supported version.
W0801 11:11:58.613074 140566666332032 keras_support.py:1394] Keras support is now deprecated in support of TPU Strategy. Please follow the distribution strategy guide on tensorflow.org to migrate to the 2.0 supported version.
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-18-b6f85142dbc2> in <module>()
      1 if tpu:
      2   strategy = tf.contrib.tpu.TPUDistributionStrategy(tpu)
----> 3   tpu_model = tf.contrib.tpu.keras_to_tpu_model(model, strategy=strategy)

2 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in __init__(self, cpu_model, strategy)
   1426           self._cpu_model.sample_weight_mode,
   1427           self._cpu_model._compile_weighted_metrics,
-> 1428           self._cpu_model.target_tensors,
   1429       )
   1430 

AttributeError: 'Model' object has no attribute 'target_tensors'

probably due to: https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md ?

**Comment by martin-gorner** [comment]
Sorry about this. TPU support has changed between TF 1.13 and 1.14. I am working on fixing this.

**Comment by henrique** [comment]
+1
No problem, thank you!

btw, is there any chance that keras-tpu will support mixed/half precision?

**Comment by martin-gorner** [comment]
Everything has been updated to TF 2.1.
half-precision (bfloat16) support is automatic when using TPUs. You do not need to add bfloat16 code to your model. All matrix multiplications that get hardware-accelerated by the TPU automatically downcast their data float32->bfloat16 before the matmul. The result of a bfloat16 matmul is naturally a float32 number again.
