### ISSUE TITLE
[cloud-istio-aspnetcore-part1]:

### ISSUE THREAD

**Issue by hannanmumtaz** [googlecodelabs/feedback#623]
in step 
[5. Package the ASP.NET Core app in a Docker container](https://codelabs.developers.google.com/codelabs/cloud-istio-aspnetcore-part1/#4)

in **Dockerfile**
There output file name should be

**CMD ["dotnet", "out/HelloWorldAspnetCore.dll"]** 
instead of 
<s>CMD ["dotnet", "out/HelloWorldAspNetCore.dll"]</s>

**Comment by meteatamel** [comment]
Are you sure about this? The name **HelloWorldAspNetCore** comes from Step 3 when you create the project.

**Comment by meteatamel** [comment]
Closing the bug. Please re-open if it's still an issue.
