### ISSUE TITLE
[cloud-app-engine-springboot]: Type on page 5

### ISSUE THREAD

**Issue by maksimu** [googlecodelabs/feedback#629]
Page "5. Add App Engine Descriptor" ([HERE](https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..index#4)) has typo. From the first sentence need to remove the word "add" or "create".

Currently the sentence looks like this:

_To deploy the application into App Engine standard, you must **add** create a new src/main/webapp/WEB-INF/appengine-web.xml descriptor file:_

**Comment by meteatamel** [comment]
Not an issue anymore.
