### ISSUE TITLE
[cloud-run-hello-python3]: port missing in step #4

### ISSUE THREAD

**Issue by jamesr42** [googlecodelabs/feedback#631]
Step #4 says to run docker image with this command:

`docker run -p 8080:8080 $DOCKER_IMG`

but the port is missing that is referenced in the dockerfile, so should be this:

`docker run -p 8080:8080 -e PORT=8080 $DOCKER_IMG`

**Comment by PicardParis** [comment]
Thank you very much for your feedback. The Dockerfile has been updated to provide a default value.
