### ISSUE TITLE
[cloud-vision-api-python]: Issue with ECHO command

### ISSUE THREAD

**Issue by anindyakg** [googlecodelabs/feedback#636]
The below code is not correct and should be modified- 

echo GOOGLE_APPLICATION_CREDENTIALS - this should be changed to 
echo $GOOGLE_APPLICATION_CREDENTIALS. The variable should be preceded by a $ sign.

Same as above for echo PROJECT_ID.

**Comment by PicardParis** [comment]
Fixed/published
