### ISSUE TITLE
[cloud-vision-api-python]:issue with Landmark Detection api

### ISSUE THREAD

**Issue by anindyakg** [googlecodelabs/feedback#638]
The Landmark Detection api does not return the correct results. Instead of returning 'Eiffel Tower' it returns the below two results in the decreasing order of score.

1. Trocadero Gardens.
2. champ de mars.

The image should be cropped to put 'Eiffel Tower' more prominently in the middle if the intent is to return 'Eiffel Tower'. The other option is to put a priority algorithm in place that returns the most prominent landmark (if there are multiple ones in a single image) irrespective of the score.

**Comment by PicardParis** [comment]
Thank you for your comments.
1. Codelab output has been updated with current results.
2. Current Vision model version returns "Trocadéro Gardens" & "Eiffel Tower", which is expected.
