### ISSUE TITLE
[cloud-bq-campaign-finance]:

### ISSUE THREAD

**Issue by gustavmaskowitz** [googlecodelabs/feedback#64]
The doc says the dataset has been decompressed and copied to a bucket, but the code suggests that the bucket contains compressed zip files. I checked and the files in the bucket and .txt so no unzipping needed.

Please change 
$ gsutil cp gs://campaign-funding/indiv16.zip .
$ unzip -p /tmp/indiv16.zip | less

to 
$ gsutil cp gs://campaign-funding/indiv16.txt .

Regards
Gus

**Comment by hostirosti** [comment]
Thank you @gusmaskowitz for pointing this out and relates to #70. This was fixed and the updated version will be online shortly :)
