### ISSUE TITLE
Cannot read property 'signInWithPopup' of undefined

### ISSUE THREAD

**Issue by saidihasan** [googlecodelabs/feedback#65]
im just trying codelab at [this step](https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/index.html?index=..%2F..%2Findex#21)

and i think the problem is'nt a typo but in firebase-auth.html
![1](https://cloud.githubusercontent.com/assets/10250394/16711129/8402522e-4675-11e6-9c4c-e1aa71d81655.jpg)

here my snippet code : 
[code-snippet.zip]()

**Comment by evaldobarbosa** [comment]
https://github.com/firebase/polymerfire/issues/45

<firebase-app name="your-app-name" ...></firebase-app>

**Comment by cineq** [comment]
+1, I have the same Issue

**Comment by cdata** [comment]
Hi, this is a common symptom of typo-ing the `<firebase-app>` element configuration. Please double check that element's configuration and try again. There is a big warning about this on the step of the code lab where you configure the `<firebase-app>`.
