### ISSUE TITLE
Buggy/intermittent scrolling on the x-axis of code samples on Chrome on Android

### ISSUE THREAD

**Issue by mrkiffie** [googlecodelabs/feedback#66]
Hi. Yesterday I incorrectly logged an issue on [firebase/friendlychat #61](https://github.com/firebase/friendlychat/issues/61) regarding a scrolling issue I experienced while working through that particular code lab. 😊 

Would this be the appropriate place to report the issue? 😃 

Thanks in advance.

**Comment by x1ddos** [comment]
Yes. Thanks for the detailed report, @mrkiffie! Either me or @ebidel will look into it.

**Comment by ebidel** [comment]
Looking

**Comment by ebidel** [comment]
This issue was moved to googlecodelabs/codelab-components#30

**Comment by x1ddos** [comment]
This was fixed in the upstream by https://github.com/googlecodelabs/codelab-components/pull/31

I will keep this issue open until the upstream change is integrated into https://codelabs.developers.google.com.
