### ISSUE TITLE
[cloud-kubernetes-aspnetcore]:Mandatory network parameter during cluster creation

### ISSUE THREAD

**Issue by PadmanavAgarwal** [googlecodelabs/feedback#663]
In the step 7 ( Create a cluster ), the command suggested is 
`gcloud container clusters create hello-dotnet-cluster --cluster-version=latest --num-nodes 4 --zone europe-west1-b`
However, on trying, I had to provide a mandatory 'network' to successfully create a cluster. This is probably not captured explicitly in the article. It will be great if we touch upon some details about the network specification as well, in the article.

**Comment by meteatamel** [comment]
Really? I tried both from gcloud and Cloud Shell and in none of them, I had to specify network. Can you provide more detail? What do you need to provide in the network config?

**Comment by meteatamel** [comment]
Closing the issue. Please re-open if needed.
