### ISSUE TITLE
[cloud-spring-cloud-gcp-pubsub-integration]:

### ISSUE THREAD

**Issue by anguillanneuf** [googlecodelabs/feedback#665]
The dependencies in this tutorial are out of date. The `receiver` app works! But `sender` app throws the following error with the current configs: 

> `java.lang.NoClassDefFoundError: org/springframework/integration/support/utils/PatternMatchUtils`

Updating `spring-cloud-gcp-dependencies` to `1.1.3.RELEASE` for the `sender` app on this [page](https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-pubsub-integration/index.html#4) alone wouldn't fix the issue. 

It's likely not be obvious for people who get this error to know how to fix it. 😕 

Suggested edits: 
1. Update to **`2.2.1.RELEASE`** in [Step 4: Initialize Spring Boot Applications](https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-pubsub-integration/index.html#3).
1. Update to **`1.1.3.RELEASE`** in [Step 5: Create an Application to Send Messages](https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-pubsub-integration/index.html#4) and [Step 6: Create an Application to Receive Messages](https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-pubsub-integration/index.html#5).

**Comment by elefeint** [comment]
I'll fix it, thanks!!

**Comment by elefeint** [comment]
Step 6 needs help, too:
```
<dependency>
                        <groupId>org.springframework.cloud</groupId>
                        <artifactId>spring-cloud-gcp-dependencies</artifactId>
                        <version>1.0.0.RELEASE</version>*
                        <type>pom</type>
                        <scope>import</scope>
 </dependency>
```

**Comment by elefeint** [comment]
@anguillanneuf Could you send me the two pom files from your test? We should definitely update all codelabs to latest versions, but I could not reproduce the issue that you had.

**Comment by anguillanneuf** [comment]
Thanks @elefeint for looking into it!

I suspect Java version matters. I developed locally too. The Codelab asks me to use Cloud Console. 

Here is my working `pom.xml` for the Sender app (`spring-boot-starter-parent` 2.0.6.RELEASE together with `spring-cloud-gcp-dependencies` 1.0.0.RELEASE do not work for me in the Sender app locally, but they work fine for the Receiver app):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.1.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-gcp-dependencies</artifactId>
				<version>1.1.3.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- Add Pub/Sub Starter -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
		</dependency>

		<!-- Add Spring Integration -->
		<dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-core</artifactId>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by meltsufin** [comment]
Fixed: https://github.com/spring-guides/gs-messaging-gcp-pubsub/pull/28
