### ISSUE TITLE
[cloud-spring-cache-memorystore]

### ISSUE THREAD

**Issue by neilghosh** [googlecodelabs/feedback#666]
The memorystore instance cannot be accessed via telnet as its not public

**Comment by meltsufin** [comment]
@dmitry-s PTAL

**Comment by dmitry-s** [comment]
Yes, It is not public. And that is why it should be accessed from the same Compute instance on which we run the Spring Boot app.

I guess that's not clear from the codelab. I will update it to clarify that.

**Comment by neilghosh** [comment]
Thanks
