### ISSUE TITLE
[cloud-spring-datastore]:alexismp

### ISSUE THREAD

**Issue by neilghosh** [googlecodelabs/feedback#667]
The app can not be deployed in appengine flex with shell enabled. May be it should be optional or profile based.

**Comment by meltsufin** [comment]
@dmitry-s PTAL

**Comment by dmitry-s** [comment]
This app is not intended to be deployed in appengine flex. This is a sample of a CLI application.

**Comment by neilghosh** [comment]
This comes up as first think when searched for spring+datastore. At least it should bring up the docker container. I have not really tested it. All right, this is probably something to take up with with appengine flex team.
