### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by jrhy** [googlecodelabs/feedback#670]
In *6. Create your cluster*, you mention:

> Alternatively, you could create this cluster via the Console shown above: Compute > Kubernetes Engine > Container Clusters > Create a container cluster.

I got a bit stuck doing this because kubectl was trying to connect to localhost:8080.  Could you please add this step?:

> You'll need to run `gcloud container clusters get-credentials <CLUSTER-NAME> --region <REGION>` before running `kubectl`.

**Comment by meteatamel** [comment]
The codelab assumes Cloud Shell, so you don't need that step.
