### ISSUE TITLE
[keras-flowers-transfer-learning]:

### ISSUE THREAD

**Issue by gombergere** [googlecodelabs/feedback#671]
J'ai essayé cet exemple...qui marche. Très intéressant et très didactique.
Je vais m'empresser d'en faire une copie pour mon petit-fils qui entame sa derniere année de Master en CS/IA à l'Imperial College of London.
X.Leroy xavleroy@gmail.com

**Comment by martin-gorner** [comment]
Merci, je viens d'en rajouter un qui arrive a 95% de precision en partant d'un modele pre-entraine (Xception) et en laissant tous les poids libres d'evoluer au cours de l'entrainement (fine-tuning):
https://codelabs.developers.google.com/codelabs/keras-flowers-tpu/#11

L'atelier a ete porte en entier a Tensorflow 2.1
