### ISSUE TITLE
[cloud-bigquery-nodejs]: codelabs/cloud-bigquery-nodejs/ error in step 6

### ISSUE THREAD

**Issue by pedrogalv** [googlecodelabs/feedback#677]
Codelabs: Using BigQuery with Node.js

In step 6, the the following command is shown:
![image](https://user-images.githubusercontent.com/18317449/70393710-9bbafd80-19cb-11ea-9a1b-4e91a79ab99a.png)

The `dotnet` command is used to open the Windows .NET IDE, but this tool is not specified as a requirement. In case of not having it installed, it can mislead novice people to think that some error happened.

**Comment by meteatamel** [comment]
Already fixed
