### ISSUE TITLE
[cloud-compute-kubernetes]:

### ISSUE THREAD

**Issue by adrukh** [googlecodelabs/feedback#68]
Step 10, running

```
gcloud compute forwarding-rules create nginx-lb \
         --port-range 80 \
         --target-pool nginx-pool
```

Generates a warning:
`WARNING: The --port-range flag is deprecated. Use equivalent --ports=80 flag.`

Change to:

```
gcloud compute forwarding-rules create nginx-lb \
         --ports 80 \
         --target-pool nginx-pool
```

Furthermore, the `create` command does not output the details of the created object. This requires `gcloud compute forwarding-rules list` to run.

**Comment by saturnism** [comment]
thnx! this has been updated.
