### ISSUE TITLE
[cloud-bigquery-load-data]: Congratulations has GCE text instead of BigQuery text

### ISSUE THREAD

**Issue by Splaktar** [googlecodelabs/feedback#69]
As you can see below and at [this link](https://codelabs.developers.google.com/codelabs/cloud-bigquery-load-data/index.html?index=..%2F..%2Findex#4), this BigQuery code lab says that we've covered GCE, VMs, and machine types. Which is obviously wrong, since the code lab is on BigQuery and didn't cover any of those things.
1. Congratulations!

You've learned how to import CSV files into BigQuery. You can also import JSON files and/or stream data into BigQuery using the API. Finally, for very large datasets, you can upload the data file into Google Cloud Storage first and then import that into BigQuery. Learn more about loading data into BigQuery.

What we've covered
- Google Compute Engine
- How to create a virtual machine
- Predefined machine types and custom machine types

Next Steps
Check out the BigQuery subredit for how others are using BigQuery today
Find open datasets available in BigQuery and other interesting queries others are using.

**Comment by saturnism** [comment]
Hiya - thanks for the feedback! This will been updated and will be pushed.
