### ISSUE TITLE
[cloud-vision-api-ruby]:  undefined method `new' for Google::Cloud::Vision:Module

### ISSUE THREAD

**Issue by markaschneider** [googlecodelabs/feedback#692]
Following the tutorial at https://codelabs.developers.google.com/codelabs/cloud-vision-api-ruby/index.html?index=..%2F..cloudai#7

In irb:
require "google/cloud/vision"
-> true

vision = Google::Cloud::Vision.new
-> NoMethodError (undefined method `new' for Google::Cloud::Vision:Module)

**Comment by markaschneider** [comment]
I was using the latest commit rather than the commit specified in the tutorial.

**Comment by realmocaccino** [comment]
Same shit here.
Google documentation is the same as nothing.
