### ISSUE TITLE
[cloud-kubernetes-aspnetcore]:

### ISSUE THREAD

**Issue by btompkinson** [googlecodelabs/feedback#693]
While performing the tutorial "Deploy ASP.NET Core app to Kubernetes on Google Kubernetes Engine" I get the following error in cloud shell at "Step 6: Package the ASP.NET Core app as a Docker container" at the command "docker build -t gcr.io/${PROJECT_ID}/hello-dotnet:v1 ." No changes were made other then those called for by the tutorial.

/usr/share/dotnet/sdk/2.2.207/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or l
ower, or use a version of the .NET SDK that supports .NET Core 3.0. [/app/HelloWorldAspNetCore.csproj]
The command '/bin/sh -c dotnet restore' returned a non-zero code: 1

**Comment by meteatamel** [comment]
Thanks for reporting. Fixed the issue. Please try again and let us know if you run into issues.
