### ISSUE TITLE
Incorrect link for tutorial for using Cloud Vision with Node.js:

### ISSUE THREAD

**Issue by SN2014J** [googlecodelabs/feedback#699]
There seems to be an error in the links in the Google Cloud tutorials.

When I navigate to 'Solve with Google Cloud' and enter the query 'vision' [like this](https://cloud.google.com/docs/tutorials#vision), one of the options is entitled 'Codelab: Using Cloud Vision with Node.js'. When I click on that link, I expect to be sent to [this tutorial for Cloud Vision with Node.js](https://codelabs.developers.google.com/codelabs/cloud-vision-nodejs/#0) (which is a url I only finally discovered after manually digging around elsewhere). However, where I actually incorrectly end up is at [this tutorial for uploading objects to cloud storage](https://codelabs.developers.google.com/codelabs/cloud-upload-objects-to-cloud-storage/#0). Thus, it seems like some tutorial links have been mixed up.

**Comment by PicardParis** [comment]
Hello @SN2014J,
- Thank you very much for your feedback.
- The search index has been fixed and refreshed (see 2nd result):
  <https://cloud.google.com/docs/tutorials#vision%20node>.
- If you're looking for tutorials in particular, you may find our Codelabs site of interest:
  https://codelabs.developers.google.com
