### ISSUE TITLE
https://codelabs.developers.google.com/codelabs/android-studio-jni/index.html

### ISSUE THREAD

**Issue by bharatiadkar** [googlecodelabs/feedback#7]
Hi,

I am new to ANdroid and jni. I am trying to follow your example I get 
Users/xxxxxxx/Documents/HelloAndroidJni/app/src/main/jni/hello-android-jni.c
Error:(1, 17) jni.h: No such file or directory

Please help me resolve the issue since I would like to implement a jni soluntion.

**Comment by x1ddos** [comment]
@ggfan could you take a look?

**Comment by ggfan** [comment]
normally jni.h is inside your ndk package: 
  "your-installed-ndk-dir"/platforms/android-21/arch-x86/usr/include/jni.h

inside your local.properties, please check if you have ndk.dir configured to point to your "your-installed-ndk-dir", something like this:

sdk.dir=/Users/test/dev/sdk_current // <== android studio will set this up automatically
ndk.dir="your-installed-ndk-dir"  // <=== this needs to be set up manually by you

I suspect your ndk.dir was not set up in your local.properties file., may you check it out.
