### ISSUE TITLE
[cloud-bq-campaign-finance]: typo in step 4

### ISSUE THREAD

**Issue by ivoysey** [googlecodelabs/feedback#70]
the file `gs://campaign-funding/indiv16.zip` doesn't exist, but the file `gs://campaign-funding/indiv16.txt` does, so the first command in step four fails, and the thing that you get if you download the other file doesn't need to be unzipped.

**Comment by hostirosti** [comment]
Thank you for pointing this out @ivoysey! I changed it in the lab and it'll be online soon.
