### ISSUE TITLE
[cloud-bigquery-nodejs]:

### ISSUE THREAD

**Issue by ihateids** [googlecodelabs/feedback#700]
on page --> https://codelabs.developers.google.com/codelabs/cloud-bigquery-nodejs/index.html?index=..%2F..index#10

this link --->Node.js on Google Cloud Platform: https://cloud.google.com/nodejs/

redirects to --> https://cloud.google.com/dotnet/

which is most probably by mistake :)

**Comment by meteatamel** [comment]
Thanks for reporting, fixed.
