### ISSUE TITLE
[cloud-picadaily-lab1]: enable api cloud shell command

### ISSUE THREAD

**Issue by jabbson** [googlecodelabs/feedback#707]
Pic-a-daily: Lab 1
Step 3: Enable APIs:
At the bottom of the page, enabling Vision API with **disable** command:

![image](https://user-images.githubusercontent.com/39545309/77212331-79b23a80-6ae5-11ea-8b1a-660e73a9a93d.png)

Should it be **enable** instead?

**Comment by glaforge** [comment]
Well spotted!
I'll fix it.
