### ISSUE TITLE
[cloud-picadaily-lab2]: create gsutil notification 

### ISSUE THREAD

**Issue by jabbson** [googlecodelabs/feedback#709]
Pic-a-daily: Lab 2
Step 10: Setup GCS event notification via Pub/Sub

Not an issue, more of a question, is there a web interface version of the following command:
`gsutil notification create -t ${TOPIC_NAME} -f json gs://${BUCKET_PICTURES}`
and if so where can one find it?

Thank you.

**Comment by glaforge** [comment]
I think so. If you create a new function, triggered by a GCS event, it should do this transparently, without the whole topic setup.
