### ISSUE TITLE
Grammar correction [cloud-create-a-vm]:

### ISSUE THREAD

**Issue by trayo** [googlecodelabs/feedback#71]
1. Create a new instance, with gcloud

Rather than using the Google Cloud Console to create an virtual machine instance, you can also use the command line tool called gcloud.

Should read
1. Create a new instance, with gcloud

Rather than using the Google Cloud Console to create **a** virtual machine instance, you can also use the command line tool called gcloud.

**Comment by hostirosti** [comment]
Thank you for pointing this out @trayo! Will be updated shortly :)
