### ISSUE TITLE
[cloud-vision-intro]: incorrect range mentioned in the 'Call the Vision APIs' page.

### ISSUE THREAD

**Issue by amithjkamath** [googlecodelabs/feedback#711]
In this page: https://codelabs.developers.google.com/codelabs/cloud-vision-intro/index.html#8

there's text like this: "The API was able to identify the specific type of donuts these are (beignets), cool! For each label the Vision API found, it returns a description with the name of the item. It also returns a score, a number from 0 - 100 indicating how confident it is that the description matches what's in the image. The mid value maps to the item's mid in Google's Knowledge Graph. You can use the mid when calling the Knowledge Graph API to get more information on the item. "

The scores returned are not actually in the range 0 - 100, it's normalized between 0-1.

**Comment by PicardParis** [comment]
Hello @amithjkamath;
Thanks a lot for your feedback. The codelab has been fixed accordingly.
