### ISSUE TITLE
[cloud-picadaily-lab3]: setting up Cloud Scheduler

### ISSUE THREAD

**Issue by jabbson** [googlecodelabs/feedback#712]
Pic-a-daily: Lab 3
Step 3: Set up Cloud Scheduler:

Cloud scheduler is created with beta argument:
`gcloud beta scheduler jobs create http`

Is `beta` argument necessary and if so how is it different from running without it, like so:

```
gcloud scheduler jobs create http collage-schedule-job --schedule "* * * * *" \
    --http-method=POST \
    --uri=${SERVICE_URL} \
    --oidc-service-account-email=${SERVICE_ACCOUNT}@${GOOGLE_CLOUD_PROJECT}.iam.gserviceaccount.com \
    --oidc-token-audience=${SERVICE_URL}
```

**Comment by glaforge** [comment]
Since Cloud Scheduler has been available for a little while, we shouldn't need the `beta` argument anymore. I'll update the codelab accordingly. Thank you.
