### ISSUE TITLE
[cloud-app-engine-aspnetcore]:

### ISSUE THREAD

**Issue by mouleja** [googlecodelabs/feedback#718]
In step 7, the deployment fails with the following error:

Step #0: No valid .NET Core runtime version found for the app or it is not a supported app.

**Comment by meteatamel** [comment]
Thanks for the feedback. I updated the instructions to include an extra step to set the right .NET Core version for App Engine: 

https://codelabs.developers.google.com/codelabs/cloud-app-engine-aspnetcore/index.html?index=..%2F..windows#2
