### ISSUE TITLE
[cloud-springboot-cloudshell]:

### ISSUE THREAD

**Issue by magdalene-lim** [googlecodelabs/feedback#719]
springboot app was unable to compile initially, had to add the following to pom file

```
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
```
Also, after adding that, springboot app was able to build successfully but keeps terminating automatically. Added the following to pom file again and then it works and I can preview in web browser.

```
        <dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
```

**Comment by meteatamel** [comment]
I tested and this works.
