### ISSUE TITLE
Typo [cloud-speech-intro]

### ISSUE THREAD

**Issue by trayo** [googlecodelabs/feedback#72]
You'll notice that we called the syncreocgnize method in our request above. The Speech API supports both synchronous and asynchronous speech to text transcription. In this example we sent it a complete audio file, but you can also use the asyncrecognize method to perform streaming speech to text transcription while the user is still speaking.

Should read:

You'll notice that we called the **syncrecognize** method in our request above. The Speech API supports both synchronous and asynchronous speech to text transcription. In this example we sent it a complete audio file, but you can also use the asyncrecognize method to perform streaming speech to text transcription while the user is still speaking.

**Comment by hostirosti** [comment]
Thank you for pointing this out @trayo! Will be updated shortly :)
