### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by magdalene-lim** [googlecodelabs/feedback#720]
As the codelab asked to create new springboot app, pom file will need to be updated with the web dependencies like in an earlier issue i submitted. Also, the Hello controller is missing here.. I assume it's similar to the [cloud-springboot-cloudshell] codelab? 

After making edits to pom file and including Hello controller it works fine though. 
https://springboot-codelab-273304.appspot.com/

**Comment by meteatamel** [comment]
Fixing with cl/523700032.

**Comment by meteatamel** [comment]
Fixed
