### ISSUE TITLE
[cloud-run-csharp]: .NET version in .csproj does not match .NET version in Dockerfile

### ISSUE THREAD

**Issue by inouiw** [googlecodelabs/feedback#726]
Error message when running "gcloud builds submit --tag gcr.io/$GOOGLE_CLOUD_PROJECT/helloworld":

```
/usr/share/dotnet/sdk/3.0.103/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(127,5): error NETSDK1045: The current .NET SDK doe
s not support targeting .NET Core 3.1.  Either target .NET Core 3.0 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. [/app/helloworld-c
sharp.csproj]
```

The code for the Dockerfile in the following link should be updated to used .NET 3.1. See https://codelabs.developers.google.com/codelabs/cloud-run-hello-csharp/index.html?index=..%2F..index#3

**Comment by meteatamel** [comment]
Thanks for letting us know. Updated the Dockerfile with 3.1.
