### ISSUE TITLE
[cloud-vision-intro]:  donuts.png to donuts.jpeg

### ISSUE THREAD

**Issue by salvadorrueda** [googlecodelabs/feedback#727]
In the step number 7 Upload an Image to ... the downloaded file is in jpeg file format (donuts.jpeg) instead of png file format (donuts.png) as documentation said. It also occurs with "selfie.png".

**Comment by PicardParis** [comment]
Hello @salvadorrueda,
Thanks a lot for your feedback. The codelab has been fixed.
