### ISSUE TITLE
[cloud-slack-bot]: Failed to import doc in codelab

### ISSUE THREAD

**Issue by TastyToast** [googlecodelabs/feedback#73]
It looks like one of the [codelab docs](https://codelabs.developers.google.com/codelabs/cloud-slack-bot/index.html?index=..%2F..%2Fio2016#3) did not import correctly. 

![screen shot 2016-08-03 at 9 04 43 am](https://cloud.githubusercontent.com/assets/572037/17372594/6443374a-5959-11e6-8780-31a4e7ead413.png)

**Comment by x1ddos** [comment]
@TastyToast thanks for reporting!
@hostirosti this seems like a claat regression. I'll check this out.

**Comment by x1ddos** [comment]
This has been fixed by https://github.com/googlecodelabs/tools/commit/2e0b2ef53fc5379409241a8a5cafcb251bb2d0a7 and I've just updated the codelab.

Thanks again.
