### ISSUE TITLE
Replace misspelled "confzziguration" with "configuration"

### ISSUE THREAD

**Issue by jmound** [googlecodelabs/feedback#731]
On this page: https://codelabs.developers.google.com/codelabs/anthos-sample-deployment/index.html?index=..%2F..anthos-samples#8

**Comment by PicardParis** [comment]
- Thanks a lot for taking the time to let us know. The codelab is in the process of being updated.
- If you're interested, here is an updated tutorial: https://cloud.google.com/anthos/docs/tutorials/explore-anthos
- Keeping this issue open until fully solved...

**Comment by PicardParis** [comment]
- The codelab was updated to refer to the canonical doc page: [Explore Anthos](https://cloud.google.com/anthos/docs/tutorials/explore-anthos)
- Closing this bug.
