### ISSUE TITLE
[keras-flowers-data]:

### ISSUE THREAD

**Issue by bekir-sedat** [googlecodelabs/feedback#732]
I think there is an error on name of function called here: It should be filenames_dataset.map(decode_jpeg_and_label)

def decode_jpeg_and_label(filename):
  bits = tf.read_file(filename)
  image = tf.image.decode_jpeg(bits)
  label = ... # extract flower name from folder name
  return image, label

image_dataset = filenames_dataset.map(decode_jpeg)
# this is now a dataset of (image, label) pairs

**Comment by martin-gorner** [comment]
Good catch. Thank you. Fixed.
(please allow some time for the site to update)
