### ISSUE TITLE
[cloud-spring-cloud-gcp-trace]:

### ISSUE THREAD

**Issue by daneshzaki** [googlecodelabs/feedback#740]
curl https://start.spring.io/starter.tgz -d packaging=jar   -d dependencies=web,lombok,cloud-gcp,cloud-starter-sleuth   -d baseDir=trace-service-one | tar -xzvf -   && cd trace-service-one

gives 
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by meteatamel** [comment]
I tested this and it works.
