### ISSUE TITLE
[Function to Update Google Sheets Codelab]:

### ISSUE THREAD

**Issue by robertomaldonado** [googlecodelabs/feedback#750]
This code lab does not show where to put the presented code. Maybe it is meant for people that have expertise in cloud functions? I thought it was an introductory code demo, but it does not specify scopes of functions and related. Can a final code snippet for the .JS file be shown?

**Comment by alexismp** [comment]
Thanks for the feedback Roberto.
I've now made a pass on the codelab trying to clarify that all the code belongs in the one cloud function that we're building throughout the lab.
There is also a link to the entire resulting code available as a gist: https://gist.github.com/alexismp/86315a74cdf887003b11f4ceade924de

**Comment by robertomaldonado** [comment]
Thank you, that clarifies a lot! Marking this as a closed issue.
