### ISSUE TITLE
[cloud-vision-api-csharp]:

### ISSUE THREAD

**Issue by lizravenwood** [googlecodelabs/feedback#754]
not a mistake but I'm a super newbie, so I don't even know how to compile/deploy anything from the cloud shell or editor ----  so when there is the code to be changed and it jumps to "here is the output you should see" I'm just not there yet.  I am hunting down how to find out how to run the thing.  Thanks though.  I am having fun!  :-)

**Comment by meteatamel** [comment]
`dotnet build` to build code and `dotnet run` to run it..

**Comment by lizravenwood** [comment]
WOW  Thank you so much.  What a quick response and so helpful.  Have a great day.
