### ISSUE TITLE
[cloud-run-csharp]: ERROR: (gcloud.builds.submit) This may be due to network connectivity issues. Please check your network settings, and the status of the service you are trying to reach.

### ISSUE THREAD

**Issue by sourav-paul** [googlecodelabs/feedback#756]
Running ASP.NET Core 3.1 app. Followed all instructions.

Cloud Run, Cloud Build, Cloud Container Registry APIs are enabled.

But every time getting this error. What am I missing?

**Comment by meteatamel** [comment]
I'm not sure why you're seeing this problem. Are you trying from Cloud Shell or locally with gcloud? I'd try both and see what happens. If not, you can always use Docker to build and push to gcr.io.

**Comment by sourav-paul** [comment]
> I'm not sure why you're seeing this problem. Are you trying from Cloud Shell or locally with gcloud? I'd try both and see what happens. If not, you can always use Docker to build and push to gcr.io.

I'm trying locally with gcloud. It's a 200MB+ project. 

I get the same error when trying to upload on App Engine as well.

**Comment by meteatamel** [comment]
Can you try building and pushing with docker?

**Comment by meteatamel** [comment]
I retested the codelab and it worked for me. Closing it, please reopen if you still see the issue.
