### ISSUE TITLE
Build a PWA: offline != !online

### ISSUE THREAD

**Issue by jongmana** [googlecodelabs/feedback#76]
The 'online' attribute from Polymer.AppNetworkStatusBehavior works when I really disconnect.
However when I open the Chrome Dev Tools and select Offline in the Network settings the online attribute value keeps to be true; this is not what I had expected. 
Is this a Dev Tool problem, a bug or is my expectation wrong?

**Comment by cdata** [comment]
Hi, thanks for reporting. Yes, this was a bug in Chrome Dev Tools. However, it has been fixed. Please try again!
