### ISSUE TITLE
[cloud-hello-istio]: Update version of Istio in sample repo

### ISSUE THREAD

**Issue by tushgup** [googlecodelabs/feedback#760]
The 5th step talks about cloning Istio onto your machine

`curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.0.0 sh -
`
This command should be replaced with 
`curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.6.1 sh -
`
as the old version doesn't work properly when running the config.yaml file later in the tutorial.

**Comment by craigbox** [comment]
Done!
