### ISSUE TITLE
[cloud-spring-datastore]:alexismp

### ISSUE THREAD

**Issue by tioback** [googlecodelabs/feedback#771]
At step 9 of the **[Spring Boot application with Cloud Datastore](https://codelabs.developers.google.com/codelabs/cloud-spring-datastore/index.html?index=..%2F..index#8)**, I was supposed to be able to see my data in the `GCP Console > Menu > Datastore > Entities`, however, all I get is a message saying "Since your database is empty, you can still switch to Cloud Firestore in Native mode to get more features."

I followed every single step to the letter, so I believe there is some missing information there, or some bug in the Datastore funcionality.

**Comment by meteatamel** [comment]
Fixed
