### ISSUE TITLE
[cloud-hello-istio]: Fix the istio version

### ISSUE THREAD

**Issue by ghost** [googlecodelabs/feedback#773]
https://codelabs.developers.google.com/codelabs/cloud-hello-istio/index.html?index=..%2F..index#4

The command is 
curl -L https://git.io/getLatestIstio | ISTIO_VERSION=1.0.0 sh -

The bookinfo.yaml uses following Deployment API, which is no longer available in k8s 1.6.x. 
unable to recognize "samples/bookinfo/platform/kube/bookinfo.yaml": no matches for kind "Deployment" in version "
extensions/v1beta1"

This solves the problem.
curl -L https://git.io/getLatestIstio | sh -

**Comment by craigbox** [comment]
Done!
