### ISSUE TITLE
[cloud-text-speech-python3]:

### ISSUE THREAD

**Issue by mitchsmith** [googlecodelabs/feedback#776]
In step 8, List available voices, the line: from google.cloud.texttospeech import enums
raises an ImportError, but isn't needed, as SsmlVoiceGender() is defined in the already
imported texttospeech, but it doesn't define any enums for language_code

**Comment by PicardParis** [comment]
Thanks a lot for your feedback @mitchsmith.
- The codelab was written with version `1.0.1` and newer version (`2.1.0`) is more simple to use
- `list_voices()` parameter is not positional anymore (+likewise for `synthesize_speech()`)
- Supported languages switched from 33 to 40
- English voices switched from 34 to 36
- All code samples have been rechecked/updated for version `2.1.0`
- ✔️ Fully rechecked codelab [Using the Text-to-Speech API with Python](https://codelabs.developers.google.com/codelabs/cloud-text-speech-python3)

**Comment by mitchsmith** [comment]
Formidable! Merci Laurent.
