### ISSUE TITLE
[keras-flowers-squeezenet]:

### ISSUE THREAD

**Issue by gitgithan** [googlecodelabs/feedback#778]
There may be a mistake in the helper function  for printing in the notebook of  https://colab.research.google.com/github/GoogleCloudPlatform/training-data-analyst/blob/master/courses/fast-and-lean-data-science/07_Keras_Flowers_TPU_xception_fine_tuned_best.ipynb.

It is missing a uint8 casting to make to plots show up properly in their normal colours and not look overexposed.
The change to plot the images normally again could be in 
```
def dataset_to_numpy_util(dataset, N):
  dataset = dataset.unbatch().batch(N)
  for images, labels in dataset:
    numpy_images = images.numpy()
    numpy_labels = labels.numpy()
    break;  
  return numpy_images, numpy_labels
```
by changing `numpy_images = images.numpy()` to `numpy_images = images.numpy().astype(np.uint8)`.

I discovered this issue firstly by seeing my images plot normally 1 day, then become whitish and unreadable another day.  I looked back at another notebook https://colab.research.google.com/github/GoogleCloudPlatform/training-data-analyst/blob/master/courses/fast-and-lean-data-science/03_Flower_pictures_to_TFRecords.ipynb and discovered in 
```
def display_9_images_from_dataset(dataset):
  plt.figure(figsize=(13,13))
  subplot=331
  for i, (image, label) in enumerate(dataset):
    plt.subplot(subplot)
    plt.axis('off')
    plt.imshow(image.numpy().astype(np.uint8))
    plt.title(label.numpy().decode("utf-8"), fontsize=16)
    subplot += 1
    if i==8:
      break
  #plt.tight_layout()
  plt.subplots_adjust(wspace=0.1, hspace=0.1)
  plt.show()
```
there is uint8 casting in `plt.imshow(image.numpy().astype(np.uint8))`. 

Why does float32 plot badly while uint8 presents images well?

**Comment by martin-gorner** [comment]
I looked at it and images display fine for me.
The generic dataset_to_numpy_util does not have a cast to unit8 because it is supposed to work both on uint8 and on float32 images.
