### ISSUE TITLE
Incomplete sentence in note following step 4.4

### ISSUE THREAD

**Issue by bartonstanley** [googlecodelabs/feedback#78]
There is an incomplete sentence in the note following step 4.4, see highlighted text 'The "Build" step' in the attached file.

![jni-4 4-note1](https://cloud.githubusercontent.com/assets/6025531/17629396/c0285554-607f-11e6-9c91-af31b6b45f91.png)

**Comment by ggfan** [comment]
thanks, fixed. will be inside next publish.
