### ISSUE TITLE
[cloud-springboot-kubernetes]:please add cleanup steps at the end of this codelab

### ISSUE THREAD

**Issue by jay-xzj** [googlecodelabs/feedback#787]
In this tutorial STEP2 mentioned : 
Running through this codelab shouldn't cost you more than a few dollars, but it could be more if you decide to use more resources or if you leave them running (**see "cleanup" section at the end of this document**).

But there is NO cleanup section at the end.

**Comment by meteatamel** [comment]
There's a cleanup section in the last `Congratulations` step
