### ISSUE TITLE
[keras-flowers-data]: parse_single_example error

### ISSUE THREAD

**Issue by rfbr** [googlecodelabs/feedback#789]
Hi ! 

In this [tutorial](https://codelabs.developers.google.com/codelabs/keras-flowers-data/#4) about TPU, you wrote in the 7th code snippet:
`tf_record = tf.parse_single_example(data, features)`
I think it should be:
`tf_record = tf.io.parse_single_example(data, features)`

Thank you for all you have done !

**Comment by martin-gorner** [comment]
good catch. Thank you. Updated
(please allow some time for the web site to update)
