### ISSUE TITLE
[cloud-networking-101]: flag deprecation warning

### ISSUE THREAD

**Issue by thefirstofthe300** [googlecodelabs/feedback#79]
On page 13, changing `$ gcloud compute firewall-rules create nginx-81 --allow tcp:81 --network codelab --source-range 0.0.0.0/0 --target-tags nginx-81` to `$ gcloud compute firewall-rules create nginx-81 --allow tcp:81 --network codelab --source-ranges 0.0.0.0/0 --target-tags nginx-81` will solve a deprecation warning and avoid future issues.

**Comment by thesmiler** [comment]
Thank you. This was now fixed and will be rolled out shortly.
