### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by itsalexschwartz** [googlecodelabs/feedback#792]
In step 8, the tutorial states "When prompted, specify the region us-central1.". This is superfluous and the installation does not ask you to specify a region since we specified it in an earlier step.

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
