### ISSUE TITLE
[cloud-functions-csharp]:

### ISSUE THREAD

**Issue by dharmeshsharma** [googlecodelabs/feedback#795]
**gcloud functions deploy hello-http-function --runtime dotnet3 --trigger-http --entry-point HelloHttpFunction.Function --allow-unauthenticated**
not working. getting error

**ERROR: (gcloud.functions.deploy) ResponseError: status=[400], code=[Bad Request], message=[The request has errors
Problems:
runtime:
Incorrect runtime value
]**

**Comment by meteatamel** [comment]
Did you follow this?

Important: This feature is currently in Early Access Program (EAP) or Alpha, might be changed in backward-incompatible ways and is not subject to any SLA or deprecation policy. Make sure you request access to the program by filling this form before attempting the codelab.

**Comment by meteatamel** [comment]
Please re-open again if you're already white-listed for Cloud Functions.

**Comment by dharmeshsharma** [comment]
I have follow the steps as given in documents but still getting same and its .net core 3 document and im also using same.
I have filled form three time.

**Comment by meteatamel** [comment]
You filled the form but did you get an email stating that your project is whitelisted?

**Comment by dharmeshsharma** [comment]
No I didn't get any confirmation email

**Comment by meteatamel** [comment]
That's why you cannot deploy the Cloud Function with `dotnet3` runtime. Wait for a couple of days to receive the email. If not, ping me here with your email and I'll ask whether your project is added to the list.
