### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by wmaxfield** [googlecodelabs/feedback#8]
This error occurs with Android Studio 1.5.1, if you have updated to the latest sdk.
  Another step needs to be added for this error, the Rendering choice for the latest (Android N) is faulty, please instruct the users to choose API 23, Android 6.0 in the tutorial

**Comment by wmaxfield** [comment]
In addition, the rendering fails after selecting another version with additional errors.  This appears to be a no-win situation.  Googling for a fix does not cover the error that occurs. It appears you have to live with a bad render and hope your project will actually work.

**Comment by slinzner** [comment]
Hey, thanks for reporting this to us! The Android N developer preview requires Android Studio 2.1 and will not work with 1.5.1, reason being the new Java 8 (java version 52.0) support. See this link for more details (http://developer.android.com/preview/setup-sdk.html)

I'm happy to update the instructions on the codelab to make it more clear which tool/framework combinations to use, however you would need to provide us with more details to fix the issue. From your description I'm not sure which codelab exactly you are referring to? Also are you talking about rendering errors in Android Studio or the app itself?

**Comment by wmaxfield** [comment]
```
 The code lab was the JNI tutorial code lab.

 The error message comes up in Android Studio 2.0, because the Design tab on AS2.0 DEFAULTS to N.
```

**Comment by x1ddos** [comment]
@ggfan I think this is also yours, although a bit late and might be obsolete now. If so, please close.

**Comment by ggfan** [comment]
yes, updated the codelab to version 2.2, it needs java 8.   thanks.
