### ISSUE TITLE
[cloud-networking-101]: pg 7 equation could be better

### ISSUE THREAD

**Issue by g-lok** [googlecodelabs/feedback#80]
Hello,
As I was going through the (quite excellent) networking 101 cloud tutorial, I noticed that on page 7 (checking latency), there is a demo equation to find the ideal latency between two locations.  While the equation itself is correct, as a former scientist, I find it a little sloppy to exclude the unit conversion for the s -> ms.  Although this is a simple conversion, for people not good at math or accustomed to unit conversions/metric, it may result in confusion or accidental omissions for their own measurements or scripts.  Showing it there reminds people that one should convert s to ms, and how that is done in this particular context.  It seems like a minor point, but for anybody that didn't catch that, it can result in some serious errors down the road.  It is always better to show _all_ your work.

**Comment by thesmiler** [comment]
Hi,
thank you for pointing that out, and thank you for the nice words! 
I have changed this in the source so it should be fixed in the next publishing run!
