### ISSUE TITLE
[cloud-speech-text-python3]: 403 error

### ISSUE THREAD

**Issue by bhaskarbanerjee** [googlecodelabs/feedback#802]
I get a PermissionDenied error (403).
I have verified the following steps during the Authenticate API requests step.

echo $GOOGLE_APPLICATION_CREDENTIALS
cat $GOOGLE_APPLICATION_CREDENTIALS
You should see something similar to:
{
"type": "service_account",
"project_id": "PROJECT_ID",
...
}
What else might I be missing. Do I need to attach any role the service account that I have created?

**Comment by PicardParis** [comment]
Did you retry a few seconds later? I cannot check right now but I believe this can happen if you use the service immediately after creating the service account (rights sometimes can take a few seconds to be propagated).

**Comment by PicardParis** [comment]
If anyone runs into this again, make sure that you export the `GOOGLE_APPLICATION_CREDENTIALS` environment variable before launching `ipython`:
```
export GOOGLE_APPLICATION_CREDENTIALS=~/key.json
```
