### ISSUE TITLE
[cloud-run-django]:

### ISSUE THREAD

**Issue by ajsay** [googlecodelabs/feedback#807]
Why does the instruction for the Dockerfile say "FROM python:3.8-slim" but cloudshell is not 3.8?

**Comment by PicardParis** [comment]
Hi @ajsay,
- A container image is built independently from the development and production environments. Local software packages are not used to build the image.
- `python:3.8-slim` is one of the official Debian base images offering a Python runtime: https://hub.docker.com/_/python
