### ISSUE TITLE
[cloud-networking-102]: --source-range for creating firewall rules deprecated

### ISSUE THREAD

**Issue by thefirstofthe300** [googlecodelabs/feedback#81]
In section 4, a deprecation warning is thrown when running

```
    $ gcloud compute firewall-rules create nw102-allow-internal --network nw102 --source-range 192.168.10.0/24 --allow tcp,udp,icmp
```

Changing the command to

```
    $ gcloud compute firewall-rules create nw102-allow-internal --network nw102 --source-ranges 192.168.10.0/24 --allow tcp,udp,icmp
```

will get rid of the error.  The flag will be disabled in release 132.0.0 according to the warning.

**Comment by thefirstofthe300** [comment]
Looking through the rest of the lab, there are multiple places where this same issue exists.

**Comment by thesmiler** [comment]
Hi,
thank you for reporting this and sorry for the delay. I fixed this and the fixes should be rolled out shortly in both Networking 101 and 102.
