### ISSUE TITLE
[cloud-run-wagtail]:

### ISSUE THREAD

**Issue by excelsior091224** [googlecodelabs/feedback#811]
Step6. Configure your project

> myproject/wsgi.py line (before)
> `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings.dev")`
> myproject/wsgi.py line (**before**)
> `os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")`

The "before" is twice in a row, and the later has to be changed to "after".

**Comment by glasnt** [comment]
Thanks for reporting this @excelsior091224. This has been fixed.
