### ISSUE TITLE
[cloud-vision-intro]:

### ISSUE THREAD

**Issue by ztony1** [googlecodelabs/feedback#815]
I find this code when I was trying to add a new Entity of Group, and Name of allUsers. 

"Could not find group "allUsers"."

**Comment by PicardParis** [comment]
Hi @ztony1,
Does the following work?
- When you add a permission entry, under "Entity", select "Public" (instead of "Group").
- This should automatically put "allUsers" under "Name".

Can you please confirm whether that works? (the UI has evolved; I'll update the lab accordingly tomorrow)

**Comment by PicardParis** [comment]
Updated the codelab:
- Authenticating with service account instead of API key
- New bucket object permissions screenshots
- `curl` with access token instead of API key
- Wording and consistency

Feel free to reopen the ticket if anything is unclear...
