### ISSUE TITLE
[cloud-run-hello-python3]:

### ISSUE THREAD

**Issue by chuklee** [googlecodelabs/feedback#818]
It's not write that we need to pay to do the cloud run:

![image](https://user-images.githubusercontent.com/43914606/94954188-0b652080-04e9-11eb-835e-87137bd9b6b0.png)

**Comment by PicardParis** [comment]
Hi @chuklee,
There won't be any cost to run this command, as it will be covered by the Free Tier: the first 120 build-minutes per day are free. The association with a billing account is just a protection to avoid abuse. You can check the Free Tier list: https://cloud.google.com/free/docs/gcp-free-tier#free-tier-usage-limits

Closing this ticket. Feel free to reopen if you have more questions.
