### ISSUE TITLE
[cloud-run-django]:typo

### ISSUE THREAD

**Issue by kakiang** [googlecodelabs/feedback#819]
In the step *8. Run the migration steps*, section *Allow access to components*, the first sentence reads "For this step, we're going to use Cloud Build to run Django commands, so **CLoud Run** will need access to the Django configuration stored in Secret Manager." I think it is Cloud Build Instead of CLoud Run that will need access to the config.

**Comment by glasnt** [comment]
Thanks for reporting this issue, @kakiang; this has been fixed.
