### ISSUE TITLE
Uncaught TypeError: Cannot read property 'signInWithPopup' of undefined

### ISSUE THREAD

**Issue by bkr32** [googlecodelabs/feedback#82]
while going through this tutorial https://codelabs.developers.google.com/codelabs/polymer-firebase-pwa/index.html?index=..%2F..%2Findex#20

i ended up getting this error `Uncaught TypeError: Cannot read property 'signInWithPopup' of undefined`

**Comment by cdata** [comment]
Hi, thanks for reporting. I believe this is an issue with an incorrectly configured `<firebase-app>`. Please check and make sure that you used valid HTML for your attributes when configuring the `<firebase-app>` element. I will add a note about this to the codelab as well.
