### ISSUE TITLE
[cloud-run-wagtail]: Errors because modules are not imported into requirements.txt yet

### ISSUE THREAD

**Issue by elsatch** [googlecodelabs/feedback#823]
As I was following the steps detailed in this codelab on step five I had to configure myproject/settings.py with:

```
# Import the original settings from each template
from .basesettings import *

try:
    from .local import *
except ImportError:
    pass

# Pulling django-environ settings file, stored in Secret Manager
import environ
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
env_file = os.path.join(BASE_DIR,  ".env")

SETTINGS_NAME = "application_settings"

if not os.path.isfile('.env'):
    import google.auth
    from google.cloud import secretmanager_v1beta1 as sm

    _, project = google.auth.default()

    if project:
        client = sm.SecretManagerServiceClient()
        path = client.secret_version_path(project, SETTINGS_NAME, "latest")
        payload = client.access_secret_version(path).payload.data.decode("UTF-8")

        with open(env_file, "w") as f:
            f.write(payload)

env = environ.Env()
env.read_env(env_file)

# Setting this value from django-environ
SECRET_KEY = env("SECRET_KEY")

# Could be more explicitly set (see "Improvements")
ALLOWED_HOSTS = ["*"]

# Default false. True allows default landing pages to be visible
DEBUG = env("DEBUG")

# Setting this value from django-environ
DATABASES = {"default": env.db()}

INSTALLED_APPS += ["storages"] # for django-storages
if "myproject" not in INSTALLED_APPS:
   INSTALLED_APPS += ["myproject"] # for custom data migration

# Define static storage via django-storages[google]
GS_BUCKET_NAME = env("GS_BUCKET_NAME")
STATICFILES_DIRS = []
DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
STATICFILES_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
GS_DEFAULT_ACL = "publicRead"
```

The editor returns the following errors:
```
{
	"resource": "file:///home/cesar/wagtail-cloudrun/myproject/settings.py",
	"owner": "file:///home/cesar/wagtail-cloudrun/myproject/settings.py",
	"code": "import-error",
	"severity": 1,
	"message": "Unable to import 'environ'",
	"source": "pylint",
	"startLineNumber": 9,
	"startColumn": 0,
	"endLineNumber": 9,
	"endColumn": 0
}
{
	"resource": "file:///home/cesar/wagtail-cloudrun/myproject/settings.py",
	"owner": "file:///home/cesar/wagtail-cloudrun/myproject/settings.py",
	"code": "no-name-in-module",
	"severity": 1,
	"message": "No name 'secretmanager_v1beta1' in module 'google.cloud'",
	"source": "pylint",
	"startLineNumber": 19,
	"startColumn": 4,
	"endLineNumber": 19,
	"endColumn": 4
}
```

By the end of step five, you add some lines into requirements.txt to include those modueles. So I would suggest either changing the order of the steps to prevent errors in the editor or add a note that the editor errors are not relevant as those will go away after adding the requirements in the final container image.

**Comment by glasnt** [comment]
Hi @elsatch. Thanks for the feedback!

`pylint` checks in the Cloud Shell editor are run against the python3 environment on the Cloud Shell; it's doesn't take into account the relative requirements.txt.

With `settings.py` open, if you go to View > Output, and change the right-hand dropdown in this new view to Python, you can see `pylint` is run when you save changes to the file. If you run the same command in the Cloud Shell terminal it will produce the same output.

By default there are some Google packages installed by default in a Cloud Shell environment, so those packages aren't returning import errors. `django-environ` is not installed, hence the error. This tutorial was using an earlier version of `google-secret-manager`; later versions removed v1beta1, hence the error (I'm working on updating this codelab to the latest version, thanks for the report!). 

I hope this explanation helps!
