### ISSUE TITLE
[cloud-speech-text-python3]:

### ISSUE THREAD

**Issue by qvintillion** [googlecodelabs/feedback#824]
After getting an error for using too many positional arguments for:
response = client.recognize(config, audio)

Using Speech v2.0, replaced with:
response = client.long_running_recognize(request={"config":config, "audio":audio})

**Comment by PicardParis** [comment]
Thanks @qvintillion.
- The following should work:
  `response = client.recognize(config=config, audio=audio)`
- I need to update the codelab...

**Comment by PicardParis** [comment]
- All code samples have been updated for client library 2.0.0
- ✔️ Fully rechecked codelab "[Using the Speech-to-Text API with Python](https://codelabs.developers.google.com/codelabs/cloud-speech-text-python3)"
- Feel free to reopen if needed
