### ISSUE TITLE
[cloud-speech-text-python3]: recognize() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by yilmazhasan** [googlecodelabs/feedback#826]
When I call speech_to_text(config, audio), I'm getting this error:

_response = client.recognize(config, audio)
TypeError: recognize() takes from 1 to 2 positional arguments but 3 were given_

**Comment by PicardParis** [comment]
Hi @yilmazhasan,
Thank you for reporting the issue. The function signatures have evolved in a breaking way.
- The following should work:
  `response = client.recognize(config=config, audio=audio)`
- I'll recheck and update the codelab within the next days...

**Comment by PicardParis** [comment]
- All code samples have been updated for client library 2.0.0
- ✔️ Fully rechecked codelab "[Using the Speech-to-Text API with Python](https://codelabs.developers.google.com/codelabs/cloud-speech-text-python3)"
- Feel free to reopen if needed
