### ISSUE TITLE
[cloud-spring-cloud-gcp-pubsub-integration]: Missing versionID in pom and project command

### ISSUE THREAD

**Issue by soumyadipDe** [googlecodelabs/feedback#829]
Lab is not working in the correct form.
Need version in pom for `spring-boot-starter-web`,`spring-cloud-gcp-starter-pubsub`,`spring-integration-core`
Need to put google project id command to work in receiver.

**Comment by meteatamel** [comment]
I went through the lab with the current instructions and everything worked for me. Please reopen if you still see an issue.
