### ISSUE TITLE
[cloud-networking-101]: page 16 - google-daemon and google-address-manager git links are broken

### ISSUE THREAD

**Issue by g-lok** [googlecodelabs/feedback#83]
Hello,
As stated in the title, the git links for google-daemon and google-address-manager on page 16 of the networking 101 codelabs tutorial are broken, and result in 404 errors.

**Comment by thesmiler** [comment]
Thanks again for the feedback Garrett. I also fixed this and we will roll the fixes out shortly.

The tools have been renamed:
This is now part of the Compute Engine Linux Guest Environment:
https://github.com/GoogleCloudPlatform/compute-image-packages
and the address manager has been renamed IP forwarding daemon:
https://github.com/GoogleCloudPlatform/compute-image-packages/tree/master/google_compute_engine/ip_forwarding

**Comment by g-lok** [comment]
THank you!
