### ISSUE TITLE
[cloud-speech-text-python3]: Error Report

### ISSUE THREAD

**Issue by msdhss** [googlecodelabs/feedback#830]
> 7. Transcribe audio files
> https://codelabs.developers.google.com/codelabs/cloud-speech-text-python3/index.html?index=..%2F..index#6

Hi, thank you for sharing the nice tutorial above.

I have found one error below executing the sample code in the cloud shell in the current GCP environment. 

> TypeError: recognize() takes from 1 to 2 positional arguments but 3 were given

I changed the code below and then can get the output.

(before) response = client.recognize(config, audio)
   (after) response = client.recognize(config=config, audio=audio)

**Comment by PicardParis** [comment]
Thank you @hisashimasuda. Codelab update is planned.

**Comment by PicardParis** [comment]
- All code samples have been updated for client library 2.0.0
- ✔️ Fully rechecked codelab "[Using the Speech-to-Text API with Python](https://codelabs.developers.google.com/codelabs/cloud-speech-text-python3)"
- Feel free to reopen if needed
