### ISSUE TITLE
[cloud-vision-python]:

### ISSUE THREAD

**Issue by jadentoh** [googlecodelabs/feedback#838]
error on vision.types.Ismage()

Traceback (most recent call last):
  File "label_detect.py", line 7, in <module>
    image = vision.types.Image()
AttributeError: module 'google.cloud.vision' has no attribute 'types'

after removing the types the code works
  image = vision.Image()

**Comment by PicardParis** [comment]
Codelab "[Using the Vision API with Python](https://codelabs.developers.google.com/codelabs/cloud-vision-api-python)"
- 🙏 Thanks for your feedback @jadentoh 
- ✔️ Updated code samples (client library 1.0.0 → 2.0.0)
- 👋 Feel free to reopen if needed
