### ISSUE TITLE
[cloud-translation-python3]:

### ISSUE THREAD

**Issue by weikunhu0428** [googlecodelabs/feedback#844]
Hi,
Just have a question. In the cloud doc (https://cloud.google.com/translate/docs/basic/quickstart), it uses **translate_v2**, but in the codelabs, it uses **translate**. Just wondering what are the differences? Thanks.

**Comment by PicardParis** [comment]
Hi,
- There are 2 versions of the client library: the legacy `translate_v2` and the newer `translate_v3` (also called "Basic" and "Advanced").
- `from google.cloud import translate` actually uses the latest default `translate_v3`.
- `from google.cloud import translate_v2` sticks to the legacy version.
- The `translate_v3` library is richer and also allows using your own translation model (created with AutoML Translate, if you have domain specific text).
- So, in the codelab, we're using the latest and more comprehensive version.
- I hope this answers your question. Feel free to reopen...
