### ISSUE TITLE
[cloud-spring-petclinic-cloudsql]:

### ISSUE THREAD

**Issue by kharmaodo** [googlecodelabs/feedback#849]
Use https instead of http for 

      
      <repository>
        <id>repository.spring.milestone</id>
        <name>Spring Milestones Repository</name>
        <url>http://repo.spring.io/milestone</url>
      </repository>
    </repositories>

Correction
      
      <repository>
        <id>repository.spring.milestone</id>
        <name>Spring Milestones Repository</name>
        **<url>https://repo.spring.io/milestone</url>
      </repository>**
    </repositories>

**Comment by meteatamel** [comment]
Already the case.
