### ISSUE TITLE
[cloud-spring-spanner]:alexismp Code model to ddl mapping error

### ISSUE THREAD

**Issue by MMerzinger** [googlecodelabs/feedback#850]
Hello everyone

The "Spring Boot application with Spanner" Codelab seems to have a mistake. (https://codelabs.developers.google.com/codelabs/cloud-spring-spanner#4)

The Order entity definition contains a field "timestamp", but in the ddl the field is called "creation_timestamp". This causes the following runtime error:
io.grpc.StatusRuntimeException: NOT_FOUND: Column not found in table orders: timestamp
resource_type: "spanner.googleapis.com/Column"

To fix this issue I had to rename the timestamp field of the Order entity to creation_timestamp and in the OrderController I had to rename the setter from setTimestamp to setCreation_timestamp.

Cheers 
Marc

**Comment by meteatamel** [comment]
Thanks for reporting. I went through the codelab and I didn't run into the issue. Please reopen if you think it's still an issue.
