### ISSUE TITLE
[cloud-istio-aspnetcore-part1]: Section 8 - aspnetcore.yaml error on kubectl apply

### ISSUE THREAD

**Issue by georgesavill** [googlecodelabs/feedback#852]
In section 8 - Deploy the application, when applied the aspnetcore.yaml deployment produces the following error:
`error: unable to recognize "aspnetcore.yaml": no matches for kind "Deployment" in version "extensions/v1beta1`

**Comment by meteatamel** [comment]
Thanks for reporting, fixed

**Comment by georgesavill** [comment]
That's great, thank you!
