### ISSUE TITLE
[cloud-istio-aspnetcore-part2]: Section 5 - install-grafana.yaml not available for Istio version 1.4.10-gke.7

### ISSUE THREAD

**Issue by georgesavill** [googlecodelabs/feedback#854]
The curl command for install-grafana.yaml doesn't work for Istio version 1.4.10-gke.7

This is the URL I am requesting:
https://storage.googleapis.com/gke-release/istio/release/1.4.10-gke.7/patches/install-prometheus.yaml

**Comment by meteatamel** [comment]
Yes. I need to test both part 1 and part 2 of labs with the latest Istio. It's not just Grafana but all other plugins won't work with the current instructions. Not sure when I'll get to it but will update this bug once I have an update.

**Comment by meteatamel** [comment]
Changed both part1 and part2 to use latest Istio 1.8.x
