### ISSUE TITLE
[cloud-slack-bot]:

### ISSUE THREAD

**Issue by rnusser** [googlecodelabs/feedback#855]
Just wanted to let you know that the filter in the service-accounts list command doesn't seem to work:

Step 8: Deploy the App to Cloud Run

`export SERVICE_ACCOUNT=$(gcloud iam service-accounts list --format 'value(EMAIL)' --filter 'NAME:Default compute service account')`

This command does work for me if I remove **_NAME:_** form the filter, ie:

`export SERVICE_ACCOUNT=$(gcloud iam service-accounts list --format 'value(EMAIL)' --filter 'Default compute service account')`

Otherwise, thanks for the great lab!

**Comment by PicardParis** [comment]
Hi,
- The codelab has been updated: https://codelabs.developers.google.com/codelabs/cloud-slack-bot
- as well as its source code: https://github.com/googlecodelabs/cloud-slack-bot
- Thank you for your feedback (and sorry it was not addressed earlier). Closing this ticket. Feel free to reopen it or create a new one if you see any issue.
