### ISSUE TITLE
[cloud-spring-cloud-gcp-secret-manager]:

### ISSUE THREAD

**Issue by ShadowRajnsih** [googlecodelabs/feedback#857]
ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: mysql:mysql-connector-java:jar -> version (?) vs 8.0.20 @ line 64, column 21
[ERROR] 'dependencies.dependency.version' for com.google.cloud:spring-cloud-gcp-starter-secretmanager:jar is missing.

**Comment by meteatamel** [comment]
I tested and it worked for me. Please reopen if you still see the issue.
