### ISSUE TITLE
[cloud-app-engine-aspnetcore]:

### ISSUE THREAD

**Issue by itsudhiryadav** [googlecodelabs/feedback#859]
URL - https://codelabs.developers.google.com/codelabs/cloud-app-engine-aspnetcore#0

When user clicks on "_Build and launch ASP.NET Core app from Google Cloud Shell_" link, user gets 404 error.

**Comment by meteatamel** [comment]
Thanks a lot for reporting this. After your bug, we realized that a number of codelabs were missing after a migration. Everything should be fixed now. Thanks.
