### ISSUE TITLE
[cloud-networking-101]: --image flag changed in gcloud compute instance create Step 4

### ISSUE THREAD

**Issue by miketruty** [googlecodelabs/feedback#86]
$ gcloud -q --user-output-enabled=false compute instances create us-vm2 --network codelab --zone us-central1-f --image centos-7 &

$ WARNING: Image aliases are deprecated and will be removed in a future version. Please use --image-family=centos-7 and --image-project=centos-cloud instead.

**Comment by thesmiler** [comment]
This was also changed in the startup script. Thank you for reporting!
