### ISSUE TITLE
[cloud-text-speech-python3]: AttributeError: 'coroutine' object has no attribute 'audio_content'

### ISSUE THREAD

**Issue by jcmachicao** [googlecodelabs/feedback#868]
AttributeError: 'coroutine' object has no attribute 'audio_content'

**Comment by PicardParis** [comment]
Hi @jcmachicao,
I went through the codelab and couldn't reproduce your issue (I do get proper WaveNet speech, as expected).
Do you have more details?
Is there any error when you call `client.synthesize_speech`?

**Comment by PicardParis** [comment]
Closing this ticket. Please reopen if you have more details...
