### ISSUE TITLE
[cloud-run-django]:

### ISSUE THREAD

**Issue by gagamil** [googlecodelabs/feedback#869]
Hi!

To create the database schema in your Cloud SQL database and populate your Cloud Storage bucket with your *media* assets, you need to run migrate and collectstatic.

Iso *media* I would prefer to see *static files* or simply *static*. This is more accurate in Django. Media is used for dynamic user files.

https://docs.djangoproject.com/en/3.1/topics/files/
https://docs.djangoproject.com/en/3.1/howto/static-files/

**Comment by glasnt** [comment]
Thank you for the feedback, we'll ensure this gets updated.
