### ISSUE TITLE
[cloud-app-engine-aspnetcore]: Confusing wording on slide 6 about "publish" folder

### ISSUE THREAD

**Issue by garybryan** [googlecodelabs/feedback#884]
Slide 6 says:

> The app.yaml file describes how to deploy the app to App Engine, in this case, the App Engine flexible environment. Create an app.yaml file inside publish folder.
> 
> Edit the generated app.yaml file and specify the environment as flex and runtime as aspnetcore.

There is no publish folder called "publish" after running the previous step. This seems to actually mean that the file should be created in the folder in which the `dotnet publish` command was run, but the wording is misleading especially as `publish` is highlighted so looks like a specific name.

Additionally, it says to edit the "generated" file, implying that the file has been generated by another process and already contains text, when in reality it is a newly created file.

**Comment by meteatamel** [comment]
Thanks for reporting this. We actually mean publish folder but I agree the wording is confusing. I made some updates, please take a look and reopen if you think it's still not clear.
