### ISSUE TITLE
[cloud-dataproc-gcloud]: the path of spark-examples.jar is wrong

### ISSUE THREAD

**Issue by guyoun** [googlecodelabs/feedback#89]
The jar file path in command line on [6. Submit a Spark job to your cluster](https://codelabs.developers.google.com/codelabs/cloud-dataproc-gcloud/index.html?index=..%2F..%2Fspringone#5)  is wrong. 
Change from `/usr/lib/spark/lib/spark-examples.jar`  to `/usr/lib/spark/examples/jars/spark-examples.jar`
There are same problems in quickstart for dataproc. 
#### current

```
$ gcloud dataproc jobs submit spark --cluster dplab \
  --class org.apache.spark.examples.SparkPi \
  --jars file:///usr/lib/spark/lib/spark-examples.jar 1000
```
#### fix

```
$ gcloud dataproc jobs submit spark --cluster dplab \
  --class org.apache.spark.examples.SparkPi \
  --jars file:///usr/lib/spark/examples/jars/spark-examples.jar 1000
```

**Comment by alexismp** [comment]
Fixed a while ago. thanks for the report.
