### ISSUE TITLE
[cloud-run-wagtail]:

### ISSUE THREAD

**Issue by estaar** [googlecodelabs/feedback#894]
When I work with my existing project I am getting homepage overidden by the default wagtail page instead of my homepage and its not the case for the other pages

**Comment by glasnt** [comment]
Hello @estaar. This is probably caused by having debugging enabled for the project. When debugging is enabled the default landing page appears on the home directory. 
You can either remove the `DEBUG=True` line from your environment settings, or change `DEBUG=False` in `settings.py`.

**Comment by estaar** [comment]
Hi @glasnt Thanks for the advice. I have changed the value to False but I am still getting that my debug is set to True. I have tried to redeploy but still the same error. Nor sure what I need to change to make the container realize that debug is set to false.

**Comment by estaar** [comment]
@glasnt thanks for the advice. It works okay now.
