### ISSUE TITLE
[cloud-run-events]:

### ISSUE THREAD

**Issue by hsachdevah** [googlecodelabs/feedback#899]
While creating trigger on step 8, getting this error:

ERROR: (gcloud.eventarc.triggers.create) Error parsing [trigger].
The [trigger] resource is not properly specified.
Failed to find attribute [location]. The attribute can be set in the following ways:
- provide the argument [--location] on the command line
- set the property [eventarc/location]

**Comment by meteatamel** [comment]
In step 5, we ask people to set the eventarc/location. Could you please set that and try again? Comment here if it still does not work.
