### ISSUE TITLE
cloud-nodejs codelab "report a bug" link is buggy

### ISSUE THREAD

**Issue by dbs** [googlecodelabs/feedback#9]
The cloud-nodejs codelab's "report a bug" link at https://gcplab.me/codelabs/cloud-nodejs/index.html leads to a 404. It currently links to:

```
https://github.com/googlecodelabs/gcp-codelabs/cloud-nodejs/issues/new?label=content-platform
```

but probably should link to:

```
https://github.com/googlecodelabs/cloud-nodejs/issues/new?label=content-platform
```

**Comment by hostirosti** [comment]
Thank you @dbs for reporting!

The link has been changed to https://github.com/googlecodelabs/cloud-nodejs/issues/new?labels[]=content-platform&labels[]=cloud
