### ISSUE TITLE
[cloud-app-engine-springboot]:All image references are missing

### ISSUE THREAD

**Issue by bogdan-marian** [googlecodelabs/feedback#916]
Int *Deploy a Spring Boot app to App Engine standard environment* all the images are missing.
[Code lab page URL](https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot#1)

**Comment by meteatamel** [comment]
The latest codelab has the images: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot?hl=en#1
