### ISSUE TITLE
[cloud-run-hello-python3]:

### ISSUE THREAD

**Issue by peeterss** [googlecodelabs/feedback#919]
how to use, run commands on the just deployed containter?  thanks for adding !

**Comment by PicardParis** [comment]
Hi @peeterss,
- If you'd like to test and run the container, you first need to pull it locally:
  `docker pull $DOCKER_IMG`
- Then you can run it:
  `docker run -p 8080:8080 $DOCKER_IMG`
- This can be done before (usually) or after the deployment, and is described at [step 5](https://codelabs.developers.google.com/codelabs/cloud-run-hello-python3#4).

Does it answer your question?

**Comment by peeterss** [comment]
hi ,

t y !  managed to run the commands on a local instance in the windows
shell. i'm very new to docker and cloud run.

is it possible to run docker-like command against a running
cloud run instance ?
[https://cloud.google.com/run/docs/testing/local#docker-with-gcp-access
seems possible ]

( good to not stop a guide just at the deletion of a project. )


all good for now.  tnx

gr,
seppe

**Comment by PicardParis** [comment]
- To my knowledge, it's not possible to access the container of a Cloud Run instance (at least for security reasons) but, to test the image, you can pull it and run it in a reproducible way anywhere.
- I'm closing the issue. Feel free to reopen if you have more details.
