### ISSUE TITLE
[keras-flowers-squeezenet]:

### ISSUE THREAD

**Issue by kbjohnson96** [googlecodelabs/feedback#922]
Hello,

I am a graduate researcher for the US Department of Energy.  I currently have a journal paper under production that uses and cites the SqueezeNet graphic within this codelab.  The publishing entity has asked for me to obtain permission for this particular image, but I cannot find any contact information other than this feedback link.  Any help would be appreciated.

Thank you,

Kristyn

**Comment by martin-gorner** [comment]
not a bug
