### ISSUE TITLE
[cloud-app-engine-springboot]: I can't see images

### ISSUE THREAD

**Issue by curogom** [googlecodelabs/feedback#923]
Please check this image.
https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot#1

![image](https://user-images.githubusercontent.com/78242788/110724643-83cecb00-8259-11eb-9d77-6d71b4db1c80.png)

**Comment by meteatamel** [comment]
Images are visible in the latest update: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot?hl=en#1
