### ISSUE TITLE
[cloud-run-django]:

### ISSUE THREAD

**Issue by RodandoSH** [googlecodelabs/feedback#925]
Hello,

In that codelabs, in 5 part, when we going to "Create the storage bucket", with the instruction "GS_BUCKET_NAME=${PROJECT_ID}-media" the shell report: "InvalidUrlError: Invalid bucket name in URL "-media"."

Could you please explain that.

Thanks.

**Comment by glasnt** [comment]
In step 5, you were asked to create a variable `PROJECT_ID`. This and other variables are used throughout the tutorial to assist in the creation of uniquely named resources. If you see any errors like this, confirm that any `$VARIABLE` or `${VARIABLE}` values are defined by checking their value: 

```
$ echo $VARIABLE
```

**Comment by RodandoSH** [comment]
Thanks glasnt,

It's possible, I did the codelab in severals times, and when I retorned I need to star the shell, and it's possible that I need define one more time all variables. I am going to do all and tell you the results.

Thank you very much
