### ISSUE TITLE
[cloud-run-django]: Error import environ

### ISSUE THREAD

**Issue by RodandoSH** [googlecodelabs/feedback#926]
Hello,

Line 4: I have a problemen with the code of settings.py . Tell me error in line "import environ" (unable to import 'environ' )

line 6: "from google.cloud import secretmanager as sm" (no name "secretmanager" in module (google.cloud)

line 22: name = f... (that "f" tell me is wrong)

Thanks

**Comment by glasnt** [comment]
Hi @RodandoSH,

Where are you getting these issues? When trying to run the app, or in Cloud Shell Editor? It sounds like you're only up to Section 6 of this codelab. 

This codelab is designed to run the code you create only within a container that uses Python 3.8 (which supports f-strings, see your line 22 error), and installs the requirements (see both other errors). 

PyLint may be running in Cloud Shell Editor to show you these potential issues, but these checks are running outside of the context this code is designed to run. 

If you continue to Section 7 and are still experiencing issues, please reopen this issue.
