### ISSUE TITLE
[cloud-app-engine-springboot]: the url of app is different from o/p of glcoud app browse

### ISSUE THREAD

**Issue by abhishekdanej** [googlecodelabs/feedback#927]
Thanks for the great tutorial. For me, the gcloud app browse command shows url as https://learn1-b94e6.uc.r.appspot.com/, but it is actually running on https://learn1-b94e6.appspot.com/. Also, can we run only 1 app in App Engine in a given project?

**Comment by meteatamel** [comment]
Yes, you can only have App Engine instance a project. The difference is due to region id, you can read more about it here: https://cloud.google.com/appengine/docs/standard/how-requests-are-routed?tab=python#region-id
