### ISSUE TITLE
Step-4 of [cloud-spring-cache-memorystore] - outdate jdk package for apt-get install

### ISSUE THREAD

**Issue by prafullkotecha** [googlecodelabs/feedback#928]
`openjdk-8-jdk-headless` is no longer available when I `ssh` into the `compute instance` vm created, and run `sudo apt-get install` command as shown in the codelab's step 4.
The output I get looks like this:
```
E: Package 'openjdk-8-jdk-headless' has no installation candidate
```

**Comment by meteatamel** [comment]
Thanks for reporting, fixed now.
