### ISSUE TITLE
[cloud-run-wagtail]:

### ISSUE THREAD

**Issue by StaysafeUK** [googlecodelabs/feedback#929]
Googlecodelabs,  

Subject: Wagtail on Cloud Run Deployment

 See below log that shows an issue when selecting a different name other than the default myinstance for Postgres SQL:

 as per step  8 when creating the cloudmigrate.yaml 

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "gcr.io/$PROJECT_ID/wagtail-cloudrun",
         "-s", "${PROJECT_ID}:${_REGION}:myinstance",
         "--", "python", "manage.py", "migrate"]

- name: "gcr.io/google-appengine/exec-wrapper"
  args: ["-i", "gcr.io/$PROJECT_ID/wagtail-cloudrun",
         "-s", "${PROJECT_ID}:${_REGION}:myinstance",
         "--", "python", "manage.py", "collectstatic", "--no-input"]
Unless I have made a mistake in the configuration

When the myinstance is changed to another name it causes the following error.
if this was  variable ${myinstance}  that would resolve the problem for the script.

Step #2: ---------- CONNECT CLOUDSQL ----------
Step #2: cloud_sql_proxy is running.
Step #2: Connections: *************:europe-north1:postgresdb.
Step #2: 
Step #2: ---------- EXECUTE COMMAND ----------
Step #2: python manage.py migrate
Step #2: Traceback (most recent call last):
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Step #2:     self.connect()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
Step #2:     self.connection = self.get_new_connection(conn_params)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
Step #2:     connection = Database.connect(**conn_params)
Step #2:   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
Step #2:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Step #2: psycopg2.OperationalError: could not connect to server: No such file or directory
Step #2:        Is the server running locally and accepting
Step #2:        connections on Unix domain socket **"**/cloudsql/***********:europe-north1:myinstance/.s.PGSQL.5432"?****

**Comment by StaysafeUK** [comment]
This was on the second run using the same config with a rebuild of the image.

Looks like psycopg2 module isn't getting the updated myinstance name:  from the file it's referencing.

connection = Database.connect(**conn_params)
Step #2:   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
Step #2:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Step #2: psycopg2.OperationalError: could not connect to server: No such file or directory
Step #2:        Is the server running locally and accepting
Step #2:        connections on Unix domain socket "/cloudsql/**********:europe-north1:myinstance/.s.PGSQL.5432"?

Further up the log 

connects but doesn't write the new instance name of the Postgres SQL DB
---------- CONNECT CLOUDSQL ----------
Step #2: cloud_sql_proxy is running.
Step #2: Connections: *************:europe-north1:DATABASE_RENAMED (Fine).
Step #2: 
Step #2: ---------- EXECUTE COMMAND ----------
Step #2: python manage.py migrate
Step #2: Traceback (most recent call last):
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
Step #2:     self.connect()
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
Step #2:     self.connection = self.get_new_connection(conn_params)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
Step #2:     return func(*args, **kwargs)
Step #2:   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connect

name: "gcr.io/google-appengine/exec-wrapper"
args: ["-i", "gcr.io/$PROJECT_ID/wagtail-cloudrun",
"-s", "${PROJECT_ID}:${_REGION}:myinstance",

name: "gcr.io/google-appengine/exec-wrapper"
args: ["-i", "gcr.io/$PROJECT_ID/wagtail-cloudrun",
"-s", "${PROJECT_ID}:${_REGION}:myinstance",
"--", "python", "manage.py", "collectstatic", "--no-input"]

Let me know if there is anything I am doing wrong apart from not using myinstance in 
cloudmigrate.yaml.

**Comment by glasnt** [comment]
Hi @StaysafeUK 

Can you confirm that the `DATABASE_URL` setting in the `application_settings` secret you created matches what you expect? Edit: if you changed your instance name you will have to also update this secret to match. 

You can check the value of this secret by running the following: 

```
gcloud secrets versions access latest --secret application_settings
```

**Do not share the value of this secret in this issue, as it contains your database password**

**Comment by StaysafeUK** [comment]
Glasnt,


I found a workaround by creating a new project and using myinstance instead of a custom name for the Postgres instance.
