### ISSUE TITLE
[cloud-spring-datastore]:alexismp

### ISSUE THREAD

**Issue by Cristianfllc3** [googlecodelabs/feedback#931]
Hello, 
Big Fan of GCP and quick labs

Running the step In section:

8. Run the application
To build and start the application, execute this command in Cloud Shell (from the root of the project datastore-example/ where the pom.xml is located) :

I could run this BUT..
$ mvn spring-boot:run

Then when i try to run other comands the shell >>
trying to save, findall, delete

"Permission denied on resource project springboot-clouddatastor.
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace."

I really dont know if it is my mistake for not know how give access.

**Comment by meteatamel** [comment]
Fixed
