### ISSUE TITLE
[cloud-text-speech-python3]: Typo 

### ISSUE THREAD

**Issue by baderj** [googlecodelabs/feedback#943]
There is a very small typo on the page https://codelabs.developers.google.com/codelabs/cloud-text-speech-python3#8 , first paragraph of "9. Synthesize audio from text":

```selecting a unique voice or modulating the output in pitch, volumn, speaking rate, and sample rate.```

``volumn`` should be ``volume``

**Comment by PicardParis** [comment]
- Thanks a lot Johannes. I had planned to update the codelab with the new languages but would have missed the typo.
- Just in case, here are the new languages:
  - es-US (Spanish, US)
  - af-ZA (Afrikaans, South Africa)
  - bg-BG (Bulgarian, Bulgaria)
  - ca-ES (Catalan, Spain)
  - is-IS (Icelandic, Iceland)
  - lv-LV (Latvian, Latvia)
  - sr-RS (Serbian, Cyrillic)
- The update should be complete by tomorrow. Will close this ticket when this is effective.

**Comment by PicardParis** [comment]
The codelab is up to date (49 languages) with the typo fixed. Thanks again Johannes.
