### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by BrigitteFre** [googlecodelabs/feedback#947]
Hello. 
The Spring Boot version at the "Create a new Spring Boot web app" -step should be updated to 2.2.2.RELEASE. The current version results in an error: "status":400,"error":"Bad Request","message":"Invalid Spring Boot version '2.1.8.RELEASE', Spring Boot compatibility range is >=2.2.2.RELEASE","path":"/starter.tgz"

**Comment by meteatamel** [comment]
Fixed in the latest update.
