### ISSUE TITLE
[cloud-video-intelligence-python3]:

### ISSUE THREAD

**Issue by wreckzone007** [googlecodelabs/feedback#948]
I can't import enums in codelabs.
![image](https://user-images.githubusercontent.com/54477470/115494872-10c56500-a299-11eb-9911-52803522eb2b.png)

**Comment by PicardParis** [comment]
Hi @wreckzone007,
- You must be using a different version of the client library.
- As a quick fix, when you install the library, use the version specified in step 6:
  `pip install google-cloud-videointelligence==1.16.1`
- I'll update the code samples with the latest library asap. Keeping this ticket open. Will close it when the codelab is updated.

**Comment by wreckzone007** [comment]
> I can't import enums in codelabs.
> ![image](https://user-images.githubusercontent.com/54477470/115494872-10c56500-a299-11eb-9911-52803522eb2b.png)

Hi! I did your code and it still says that I cannot import enums.

**Comment by wreckzone007** [comment]
> Hi @wreckzone007,
> 
> * You must be using a different version of the client library.
> * As a quick fix, when you install the library, use the version specified in step 6:
>   `pip install google-cloud-videointelligence==1.16.1`
> * I'll update the code samples with the latest library asap. Keeping this ticket open. Will close it when the codelab is updated.

Hi! I did this as well and it still says that it still can't import enums

**Comment by PicardParis** [comment]
- Which version do you see installed?
   ```
   pip freeze | grep google-cloud-videointelligence
   ```
- If you have an earlier version installed (I suspect `2.1.0`), this should restore the codelab version (`1.16.1`):
   ```
  pip uninstall google-cloud-videointelligence
  pip install google-cloud-videointelligence==1.16.1
   ```

**Comment by PicardParis** [comment]
- The codelab has been updated using the client library version `2.1.0`.
- You may find the new code samples more pleasant to read.
- I'm closing this ticket. Feel free to reopen it if there's any issue.
