### ISSUE TITLE
[cloud-spring-petclinic-cloudsql]: images are not shown

### ISSUE THREAD

**Issue by tmsanchez** [googlecodelabs/feedback#949]
In codelab _Connect a Spring Boot app to Cloud SQL_ from _Build, containerize, and deploy Spring Boot apps on Google Cloud_ images are not shown

403. That’s an error.

Your client does not have permission to get URL /7dEydANjWCFC31v6VR_a59vRqEKRnTJ3l0h4A7QfecSym9mdoHUXFRs15locxZm6ET0xBaI5XAZpfbFYRK75tCLKCFN5KAUg4pa8QXGSATCxpE8lcS8_EICLHAXW1uHEpvzViUB4 from this server. (Client IP address: the_ip_address)

ACL Denied That’s all we know.

**Comment by meteatamel** [comment]
Not an issue anymore.
