### ISSUE TITLE
[cloud-app-engine-springboot]:

### ISSUE THREAD

**Issue by shookie10** [googlecodelabs/feedback#951]
curl https://start.spring.io/starter.tgz \
  -d bootVersion=2.1.8.RELEASE \
  -d dependencies=web \
  -d baseDir=gae-standard-example | tar -xzvf -

Does not work in cloud console

curl https://start.spring.io/starter.tgz   -d bootVersion=2.1.8.RELEASE   -d dependencies=web   -d baseDir=gae-standard-example | tar -xzvf -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   281    0   210  100    71   2000    676 --:--:-- --:--:-- --:--:--  2676

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

![image](https://user-images.githubusercontent.com/2156815/116000378-f0114e00-a5bd-11eb-9437-c476c4758c40.png)

**Comment by meteatamel** [comment]
Fixed in the latest update: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot
