### ISSUE TITLE
[cloud-springboot-kubernetes]:

### ISSUE THREAD

**Issue by adriancruz88** [googlecodelabs/feedback#954]
The instructions or images of the codelab load incorrectly
https://codelabs.developers.google.com/codelabs/cloud-springboot-kubernetes#1

in the requests you see responses with code 403 

Example:

curl 'https://lh6.googleusercontent.com/MIsCwOp-0U1r3jQ74M8pVqrxXo0G_vjvdgyXkOS740hp0Qn8BFsHZCgjs3Ok3JJFABjY-lTCRbuy2hYvuTXX5yRuPUNTv_s1SKcKjqYDJ-rBRe7ktWeWe1KJl7gLXglMB-oV3__vxA' \
  -H 'Referer: https://codelabs.developers.google.com/codelabs/cloud-springboot-kubernetes' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36' \
  --compressed

**Comment by meteatamel** [comment]
Not an issue anymore
