### ISSUE TITLE
[cloud-spring-datastore]:alexismp

### ISSUE THREAD

**Issue by ldelpozo6** [googlecodelabs/feedback#957]
there is an error in pom.xml : spring-cloud-gcp-starter-data-datastore had to add version.
Also there is an error starting up the app: The bean 'gcpProjectIdProvider', defined in class path resource [org/springframework/cloud/gcp/autoconfigure/core/GcpContextAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/google/cloud/spring/autoconfigure/core/GcpContextAutoConfiguration.class] and overriding is disabled.
I had to add in the application.properties: spring.main.allow-bean-definition-overriding=true
Finally if you run everything from gcp cloud shell you have to enable "Cloud Datastore API" so when that save-book command can run.
Thank you! have a great day

**Comment by meteatamel** [comment]
Fixed
