### ISSUE TITLE
[cloud-spring-cloud-gcp-trace]:

### ISSUE THREAD

**Issue by ldelpozo6** [googlecodelabs/feedback#958]
Hi error: The bean 'gcpProjectIdProvider', defined in class path resource [org/springframework/cloud/gcp/autoconfigure/core/GcpContextAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/google/cloud/spring/autoconfigure/core/GcpContextAutoConfiguration.class] and overriding is disabled.
added in the application.properties: spring.main.allow-bean-definition-overriding=true

**Comment by meteatamel** [comment]
I tested the latest codelab and everything works. Please reopen if it's still an issue.
