### ISSUE TITLE
[cloud-spring-petclinic-cloudsql]:

### ISSUE THREAD

**Issue by DmiProps** [googlecodelabs/feedback#960]
On many pages you can see stubs instead of pictures.
<img width="770" alt="Screenshot 2021-05-03 at 12 49 02" src="https://user-images.githubusercontent.com/17944943/116862807-f7fc6e00-ac0d-11eb-9285-d7dd18517cea.png">

**Comment by meteatamel** [comment]
Not an issue anymore, closing.
