### ISSUE TITLE
[cloud-app-engine-python3]:

### ISSUE THREAD

**Issue by ddgunter** [googlecodelabs/feedback#962]
I get 502 Bad gateway when trying this tutorial:

ddgunter@cloudshell:~/helloworld (massive-weft-198714)$ curl https://massive-weft-198714.nn.r.appspot.com
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
ddgunter@cloudshell:~/helloworld (massive-weft-198714)$

**Comment by ddgunter** [comment]
Figured it out. Commenting out this code solved the problem:
```
if __name__ == "main":
   app.run(host="localhost", port=8080, debug=True)
```

**Comment by PicardParis** [comment]
Hello @ddgunter,
- I rechecked the codelab. It's working as expected.
- What happened is that you typed `"main"` instead of `"__main__"`, which got `app.run` to be executed in all cases (instead of just for local tests).

**Comment by ddgunter** [comment]
Thanks! Sorry about that.
