### ISSUE TITLE
[cloud-springboot-cloudshell]: Image broken 

### ISSUE THREAD

**Issue by vivekbhatnagar** [googlecodelabs/feedback#968]
Hi Team, the image is broken:

![image](https://user-images.githubusercontent.com/28641909/119205656-1df09200-ba99-11eb-8e89-41480c3b7d29.png)

at:
https://developers.google.com/codelabs/cloud-springboot-cloudshell?continue=https%3A%2F%2Fdevelopers.google.com%2Flearn%2Fpathways%2Fjava-cloud-fundamentals%3Fhl%3Den%23codelab-https%3A%2F%2Fdevelopers.google.com%2Fcodelabs%2Fcloud-springboot-cloudshell&hl=en#1

**Comment by meteatamel** [comment]
This is the old link. The new link works fine: https://codelabs.developers.google.com/codelabs/cloud-springboot-cloudshell
