### ISSUE TITLE
[cloud-networking-101]: typo in a command in step 17 Test HTTP Load Balancer

### ISSUE THREAD

**Issue by piotrekjanisz** [googlecodelabs/feedback#97]
There is a typo in a command to create forwarding-rule:
`gcloud compute forwarding-rules create global-lb --global --target-http-proxy global-proxy --port 80`

the 
**--port** option is invalid, should be **--ports**

see attached screenshot
![17_test_http_lb](https://cloud.githubusercontent.com/assets/645006/18835167/0b3ffbc6-83fa-11e6-9658-b5b5bd2a94d7.png)

**Comment by thesmiler** [comment]
Thank you, this has been fixed, should be online soon!
