### ISSUE TITLE
[cloud-spring-petclinic-cloudsql]: Images do not load and instead show their id tags

### ISSUE THREAD

**Issue by ZMobile** [googlecodelabs/feedback#971]
Example (pasted from the codelabs tutorial): 

If you've never started Cloud Shell before, you'll be presented with an intermediate screen (below the fold) describing what it is. If that's the case, click Continue (and you won't ever see it again). Here's what that one-time screen looks like:

6xHyeTqcyGXbrw8oJPqVDtHH8EXFvD24gk31peCHFGHGGNJnp_pLsU7nC5B4kCkrrpTmOv3vD72SeOnvzIIpXt0YGZfQlbqHvrYqP0VY3pyBnakiKRYMePtVhmrkY905Y0AmhEl7nw

It should only take a few moments to provision and connect to Cloud Shell.

oWAyZqnI8MxiiWGA6naHP-CvYx4hAZEqO-Q1qapIR8Q187VB0OON-i5CLKMGdSZh35pcITfGbrdCCZq1L88ljOGToFNtP1utm17j8qV9pBCctDHIQlDawcyNzIkQhSSwNM6pu5tLGw

This virtual machine is loaded with all the development tools you'll need.

**Comment by matjag** [comment]
![image](https://user-images.githubusercontent.com/22679485/124749279-50a8f980-df24-11eb-871d-99b1865691f1.png)
Same problem, it looks like the server responds with 403.

**Comment by meteatamel** [comment]
Not an issue anymore. Closing.
