### ISSUE TITLE
[cloud-app-engine-springboot]: Images not loading on web page, 403 error

### ISSUE THREAD

**Issue by mperry2** [googlecodelabs/feedback#973]
On page https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot#1 the images are not loading. Trying to open the images in a new tab gives the following error (I've redacted my IP address):

403. That’s an error.

Your client does not have permission to get URL /MIsCwOp-0U1r3jQ74M8pVqrxXo0G_vjvdgyXkOS740hp0Qn8BFsHZCgjs3Ok3JJFABjY-lTCRbuy2hYvuTXX5yRuPUNTv_s1SKcKjqYDJ-rBRe7ktWeWe1KJl7gLXglMB-oV3__vxA from this server. (Client IP address: [redacted])

ACL Denied That’s all we know.

**Comment by ozkanpakdil** [comment]
same here...

**Comment by meteatamel** [comment]
Images are visible in the latest update: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot?hl=en#1
