### ISSUE TITLE
[cloud-networking-101]: 18 Optional - Test HTTPS load balancer - no need for sudo when creating ssl certificate

### ISSUE THREAD

**Issue by piotrekjanisz** [googlecodelabs/feedback#98]
There is no need for **sudo** in a command to create ssl-certificate resource:
`sudo gcloud compute ssl-certificates create ssl --certificate my.crt --private-key my.key`

![screenshot from 2016-09-26 15 21 30](https://cloud.githubusercontent.com/assets/645006/18835767/1fd7d312-83fd-11e6-844a-dcd881933b22.png)

**Comment by thesmiler** [comment]
Thanks, this will also be fixed in the next implementation of the codelab.
