### ISSUE TITLE
[cloud-istio-aspnetcore-part1]:

### ISSUE THREAD

**Issue by mprogers** [googlecodelabs/feedback#988]
docker run -p 8080:8080 gcr.io/${GOOGLE_CLOUD_PROJECT}/hello-dotnet:v1
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

**Comment by meteatamel** [comment]
Thanks for the bug. Cloud Shell was updated to use .NET 5.0 but Dockerfile was still referring to .NET Core 3.1. Changed Dockerfile to also point to .NET 5.0 now.
