### ISSUE TITLE
[cloud-spring-cloud-gcp-gcs]:

### ISSUE THREAD

**Issue by alsafi2** [googlecodelabs/feedback#989]
curl https://start.spring.io/starter.tgz \
> -d dependencies=web,cloud-gcp-storage -d baseDir=spring-gcs | tar -xzvf -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   239    0   186  100    53    120     34  0:00:01  0:00:01 --:--:--   155

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

curl https://start.spring.io/starter.tgz -d dependencies=web,cloud-gcp-storage -d baseDir=spring-gcs
{"timestamp":"2021-08-01T02:03:55.298+00:00","status":400,"error":"Bad Request","message":"Dependency 'cloud-gcp-storage' is not compatible with Spring Boot 2.5.3","path":"/starter.tgz"}

**Comment by meteatamel** [comment]
Updated the codelab and tested that it works. Closing this issue.
