### ISSUE TITLE
[cloud-networking-101][18 Optional - Test HTTPS load balancer] - wrong option name in command to create forwarding-rules

### ISSUE THREAD

**Issue by piotrekjanisz** [googlecodelabs/feedback#99]
In a command to create a forwarding-rule:
`gcloud compute forwarding-rules create ssl-lb --global --target-https-proxy ssl-proxy --port 443`

the option **--port** is invalid. Should be **--ports**

![screenshot from 2016-09-26 15 24 34](https://cloud.githubusercontent.com/assets/645006/18835878/a2885372-83fd-11e6-8242-6d7ad356971a.png)

**Comment by thesmiler** [comment]
Thanks for your comment, this will be fixed with the next rollout!
