### ISSUE TITLE
[cloud-tensorflow-mnist]: Dead link to MNIST

### ISSUE THREAD

**Issue by jockebech** [googlecodelabs/feedback#992]
In the Overview of "TensorFlow, Keras and deep learning, without a PhD" it's said that:

_This codelab uses the [MNIST](http://yann.lecun.com/exdb/mnist/) dataset, a collection of 60,000 labeled digits that has kept generations of PhDs busy for almost two decades. You will solve the problem with less than 100 lines of Python / TensorFlow code._

The MNIST link isn't working.

**Comment by martin-gorner** [comment]
That link has issues from time to time.  It's a personal website and sometimes it does not keep up with the traffic apparently. The link is good and is working today.
Thank you for the report.
