### ISSUE TITLE
[cloud-run-django]: secretmanager import error

### ISSUE THREAD

**Issue by uijin** [googlecodelabs/feedback#997]
The 4th line in myproject/migrations/0001_createsuperuser.py should be modified from
`from google.cloud import secretmanager as sm`
to
`import google.cloud.secretmanager as sm`
according to StackOverflow article: [google.cloud namespace import error in __init__.py](https://stackoverflow.com/a/68835916/1229778)

**Comment by glasnt** [comment]
Thanks for logging this issue, @uijin 

It looks like that SO question refers to `google-cloud-secret-manager>=0.2.0`, which is very out of date. 

I cannot reproduce this issue using `2.4.0` (the version currently in the codelab) or `2.7.2` (the current most recent version)
